/**
 * worksheetActivityMeta.ts
 * Etkinlik Oluşturucu Stüdyosu — 32 Etkinlik Şablon Metadata
 * 4 Kategori × 8 Şablon = 32 Etkinlik
 * 
 * Elif Yıldız: Her şablon ZPD uyumlu, yaparak öğrenme odaklı.
 */

import {
  Grid3X3, FlipHorizontal2, Copy, Search, LetterText, Navigation, Shapes, Route,
  HelpCircle, CheckCircle, TextCursorInput, ListOrdered, Lightbulb, Link2, UserSearch, ArrowRightLeft,
  Scissors, Combine, ArrowLeftRight, GitCompare, Tags, LayoutList, Table, SpellCheck,
  Triangle, Square, LayoutGrid, Clock, Coins, TrendingUp, BarChart3, Calculator
} from 'lucide-react';
import type { WorksheetTemplateMeta, WorksheetActivityCategory } from '../../../types/worksheetActivity';

// ── Kategori Yapılandırması ──────────────────────────────────────────────────

export interface WorksheetCategoryConfig {
  id: WorksheetActivityCategory;
  label: string;
  icon: string;
}

export const WORKSHEET_CATEGORIES: WorksheetCategoryConfig[] = [
  { id: 'ws-visual-spatial', label: 'Görsel & Mekansal', icon: 'Eye' },
  { id: 'ws-reading-comprehension', label: 'Okuduğunu Anlama', icon: 'BookOpen' },
  { id: 'ws-language-literacy', label: 'Okuma & Dil', icon: 'Languages' },
  { id: 'ws-math-logic', label: 'Matematik & Mantık', icon: 'Calculator' },
];

// ── 32 Etkinlik Şablon Metadatası ────────────────────────────────────────────

export const WORKSHEET_TEMPLATES_META: WorksheetTemplateMeta[] = [
  // ─── Kategori 1: GÖRSEL & MEKANSAL (8 şablon) ─────────────────────────
  {
    id: 'pattern-completion',
    categoryId: 'ws-visual-spatial',
    title: 'Desen Tamamlama',
    description: 'Verilen desendeki eksik parçayı bulup çizer.',
    studentAction: 'Eksik deseni grid üzerinde çizer ✏️',
    icon: 'Grid3X3',
    supportsOffline: true,
    supportsAI: true,
    defaultSectionCount: 4,
  },
  {
    id: 'symmetry-drawing',
    categoryId: 'ws-visual-spatial',
    title: 'Simetri Tamamlama',
    description: 'Görselin diğer yarısını simetrik olarak çizer.',
    studentAction: 'Şeklin aynadaki yansımasını çizer ✏️',
    icon: 'FlipHorizontal2',
    supportsOffline: true,
    supportsAI: false,
    defaultSectionCount: 3,
  },
  {
    id: 'grid-copy',
    categoryId: 'ws-visual-spatial',
    title: 'Kare Kopyalama',
    description: 'Grid üzerindeki deseni boş grid\'e birebir kopyalar.',
    studentAction: 'Grid üzerindeki deseni kopyalar ✏️',
    icon: 'Copy',
    supportsOffline: true,
    supportsAI: false,
    defaultSectionCount: 3,
  },
  {
    id: 'spot-difference',
    categoryId: 'ws-visual-spatial',
    title: 'Farkı Bul',
    description: 'İki benzer dizi arasındaki farkları tespit eder.',
    studentAction: 'Farkları bulup daire içine alır ✏️',
    icon: 'Search',
    supportsOffline: true,
    supportsAI: true,
    defaultSectionCount: 4,
  },
  {
    id: 'word-search-grid',
    categoryId: 'ws-visual-spatial',
    title: 'Kelime Bulmaca',
    description: 'Harf grid\'inde gizli kelimeleri bulur.',
    studentAction: 'Gizli kelimeleri bulup çizer ✏️',
    icon: 'LetterText',
    supportsOffline: true,
    supportsAI: true,
    defaultSectionCount: 1,
  },
  {
    id: 'directional-tracking',
    categoryId: 'ws-visual-spatial',
    title: 'Yön İz Sürme',
    description: 'Okları takip ederek hedefi bulur.',
    studentAction: 'Okları takip edip harfleri toplar ✏️',
    icon: 'Navigation',
    supportsOffline: true,
    supportsAI: false,
    defaultSectionCount: 3,
  },
  {
    id: 'shape-counting',
    categoryId: 'ws-visual-spatial',
    title: 'Şekil Sayma',
    description: 'İç içe geçmiş şekilleri sayar.',
    studentAction: 'Şekilleri sayıp cevabı yazar ✏️',
    icon: 'Shapes',
    supportsOffline: true,
    supportsAI: true,
    defaultSectionCount: 4,
  },
  {
    id: 'maze',
    categoryId: 'ws-visual-spatial',
    title: 'Labirent',
    description: 'Başlangıçtan hedefe yolu bulur.',
    studentAction: 'Yolu bulup çizer ✏️',
    icon: 'Route',
    supportsOffline: true,
    supportsAI: false,
    defaultSectionCount: 2,
  },

  // ─── Kategori 2: OKUDUĞUNU ANLAMA (8 şablon) ──────────────────────────
  {
    id: 'five-w-one-h-questions',
    categoryId: 'ws-reading-comprehension',
    title: '5N1K Soruları',
    description: 'Metni okuyup 5N1K sorularını cevaplar.',
    studentAction: 'Metni okur, soruları yazar ✏️',
    icon: 'HelpCircle',
    supportsOffline: false,
    supportsAI: true,
    defaultSectionCount: 6,
  },
  {
    id: 'true-false',
    categoryId: 'ws-reading-comprehension',
    title: 'Doğru / Yanlış',
    description: 'Metne göre cümlelerin doğruluğunu belirler.',
    studentAction: 'D veya Y işaretler ✏️',
    icon: 'CheckCircle',
    supportsOffline: false,
    supportsAI: true,
    defaultSectionCount: 8,
  },
  {
    id: 'fill-in-blanks',
    categoryId: 'ws-reading-comprehension',
    title: 'Boşluk Doldurma',
    description: 'Cümledeki boşluğa uygun kelimeyi yazar.',
    studentAction: 'Boşlukları doldurur ✏️',
    icon: 'TextCursorInput',
    supportsOffline: false,
    supportsAI: true,
    defaultSectionCount: 6,
  },
  {
    id: 'event-sequencing',
    categoryId: 'ws-reading-comprehension',
    title: 'Olay Sıralama',
    description: 'Karışık olayları doğru sıraya koyar.',
    studentAction: 'Sıra numaralarını yazar ✏️',
    icon: 'ListOrdered',
    supportsOffline: false,
    supportsAI: true,
    defaultSectionCount: 5,
  },
  {
    id: 'main-idea',
    categoryId: 'ws-reading-comprehension',
    title: 'Ana Fikir Bulma',
    description: 'Paragrafın ana fikrini belirler.',
    studentAction: 'Ana fikri yazar ✏️',
    icon: 'Lightbulb',
    supportsOffline: false,
    supportsAI: true,
    defaultSectionCount: 3,
  },
  {
    id: 'inference',
    categoryId: 'ws-reading-comprehension',
    title: 'Çıkarım Yapma',
    description: 'Metinden çıkarım yaparak soruları cevaplar.',
    studentAction: 'Çıkarımları yazar ✏️',
    icon: 'Link2',
    supportsOffline: false,
    supportsAI: true,
    defaultSectionCount: 4,
  },
  {
    id: 'character-analysis',
    categoryId: 'ws-reading-comprehension',
    title: 'Karakter Analizi',
    description: 'Hikayedeki karakterin özelliklerini analiz eder.',
    studentAction: 'Karakter özelliklerini yazar ✏️',
    icon: 'UserSearch',
    supportsOffline: false,
    supportsAI: true,
    defaultSectionCount: 4,
  },
  {
    id: 'cause-effect-matching',
    categoryId: 'ws-reading-comprehension',
    title: 'Neden-Sonuç Eşleştirme',
    description: 'Nedenleri sonuçlarla eşleştirir.',
    studentAction: 'Çizgi çekerek eşleştirir ✏️',
    icon: 'ArrowRightLeft',
    supportsOffline: false,
    supportsAI: true,
    defaultSectionCount: 5,
  },

  // ─── Kategori 3: OKUMA & DİL (8 şablon) ───────────────────────────────
  {
    id: 'syllable-splitting',
    categoryId: 'ws-language-literacy',
    title: 'Hece Ayırma',
    description: 'Kelimeleri hecelerine ayırır.',
    studentAction: 'Kelimeleri hecelerine ayırıp yazar ✏️',
    icon: 'Scissors',
    supportsOffline: true,
    supportsAI: true,
    defaultSectionCount: 8,
  },
  {
    id: 'syllable-combining',
    categoryId: 'ws-language-literacy',
    title: 'Hece Birleştirme',
    description: 'Dağınık heceleri birleştirip kelime oluşturur.',
    studentAction: 'Heceleri birleştirip kelimeyi yazar ✏️',
    icon: 'Combine',
    supportsOffline: true,
    supportsAI: true,
    defaultSectionCount: 6,
  },
  {
    id: 'synonym-matching',
    categoryId: 'ws-language-literacy',
    title: 'Eş Anlamlı Eşleştirme',
    description: 'Eş anlamlı kelimeleri çizgi çekerek eşleştirir.',
    studentAction: 'Çizgi çekerek eşleştirir ✏️',
    icon: 'ArrowLeftRight',
    supportsOffline: true,
    supportsAI: true,
    defaultSectionCount: 6,
  },
  {
    id: 'antonym-matching',
    categoryId: 'ws-language-literacy',
    title: 'Zıt Anlamlı Eşleştirme',
    description: 'Zıt anlamlı kelimeleri çizgi çekerek eşleştirir.',
    studentAction: 'Çizgi çekerek eşleştirir ✏️',
    icon: 'GitCompare',
    supportsOffline: true,
    supportsAI: true,
    defaultSectionCount: 6,
  },
  {
    id: 'root-suffix-analysis',
    categoryId: 'ws-language-literacy',
    title: 'Kök-Ek Ayrıştırma',
    description: 'Kelimelerin kökünü ve eklerini ayırır.',
    studentAction: 'Kökü ve ekleri kutulara yazar ✏️',
    icon: 'Tags',
    supportsOffline: true,
    supportsAI: true,
    defaultSectionCount: 6,
  },
  {
    id: 'sentence-elements',
    categoryId: 'ws-language-literacy',
    title: 'Cümle Ögesi Bulma',
    description: 'Cümlenin ögelerini (Ö-Y-N-TÜ-DT) belirler.',
    studentAction: 'Cümle ögelerini yazar ✏️',
    icon: 'LayoutList',
    supportsOffline: false,
    supportsAI: true,
    defaultSectionCount: 5,
  },
  {
    id: 'word-type-classification',
    categoryId: 'ws-language-literacy',
    title: 'Kelime Türü Sınıflandırma',
    description: 'Kelimeleri türlerine göre tabloya yerleştirir.',
    studentAction: 'Kelimeleri tabloya yazar ✏️',
    icon: 'Table',
    supportsOffline: true,
    supportsAI: true,
    defaultSectionCount: 1,
  },
  {
    id: 'spelling-rules',
    categoryId: 'ws-language-literacy',
    title: 'Yazım Kuralları',
    description: 'Doğru yazılışı belirler veya yanlışı düzeltir.',
    studentAction: 'Doğru yazılışı seçer/yazar ✏️',
    icon: 'SpellCheck',
    supportsOffline: true,
    supportsAI: true,
    defaultSectionCount: 8,
  },

  // ─── Kategori 4: MATEMATİK & MANTIK (8 şablon) ────────────────────────
  {
    id: 'number-pyramid',
    categoryId: 'ws-math-logic',
    title: 'Sayı Piramidi',
    description: 'Kurallara göre boş kutuları doldurur.',
    studentAction: 'Boş kutuları doldurur ✏️',
    icon: 'Triangle',
    supportsOffline: true,
    supportsAI: false,
    defaultSectionCount: 3,
  },
  {
    id: 'operation-boxes',
    categoryId: 'ws-math-logic',
    title: 'İşlem Kutuları',
    description: 'Bilinmeyen sayıyı/işlemi bulur.',
    studentAction: 'Kutu içine bilinmeyeni yazar ✏️',
    icon: 'Square',
    supportsOffline: true,
    supportsAI: false,
    defaultSectionCount: 6,
  },
  {
    id: 'simple-sudoku',
    categoryId: 'ws-math-logic',
    title: 'Mini Sudoku',
    description: '4×4 veya 6×6 grid\'i kurallarla doldurur.',
    studentAction: 'Grid\'i sayılarla doldurur ✏️',
    icon: 'LayoutGrid',
    supportsOffline: true,
    supportsAI: false,
    defaultSectionCount: 2,
  },
  {
    id: 'clock-reading',
    categoryId: 'ws-math-logic',
    title: 'Saat Okuma',
    description: 'Saati okuyup yazar veya akrep/yelkovan çizer.',
    studentAction: 'Saati okuyup cevabı yazar ✏️',
    icon: 'Clock',
    supportsOffline: true,
    supportsAI: false,
    defaultSectionCount: 6,
  },
  {
    id: 'money-calculation',
    categoryId: 'ws-math-logic',
    title: 'Para Hesaplama',
    description: 'Toplam tutarı, para üstünü hesaplar.',
    studentAction: 'Hesabı yapıp cevabı yazar ✏️',
    icon: 'Coins',
    supportsOffline: true,
    supportsAI: true,
    defaultSectionCount: 4,
  },
  {
    id: 'sequence-pattern',
    categoryId: 'ws-math-logic',
    title: 'Örüntü ve Seri',
    description: 'Sayı veya şekil serisindeki eksik öğeyi bulur.',
    studentAction: 'Eksik öğeyi yazar ✏️',
    icon: 'TrendingUp',
    supportsOffline: true,
    supportsAI: true,
    defaultSectionCount: 6,
  },
  {
    id: 'graph-reading',
    categoryId: 'ws-math-logic',
    title: 'Grafik Okuma',
    description: 'Grafiği okuyup soruları cevaplar.',
    studentAction: 'Grafik verilerinden soruları cevaplar ✏️',
    icon: 'BarChart3',
    supportsOffline: false,
    supportsAI: true,
    defaultSectionCount: 4,
  },
  {
    id: 'word-problem',
    categoryId: 'ws-math-logic',
    title: 'Problem Çözme',
    description: 'Sözel problemi okuyup işlem yaparak çözer.',
    studentAction: 'İşlemi yapıp cevabı yazar ✏️',
    icon: 'Calculator',
    supportsOffline: false,
    supportsAI: true,
    defaultSectionCount: 4,
  },
];
