import { Activity, ActivityType, ActivityCategory } from './types';

export const ACTIVITIES: Activity[] = [
  {
    id: ActivityType.WORD_SEARCH,
    title: 'Kelime Bulmaca',
    description: 'Verilen kelimeleri harf tablosunda bulun.',
    icon: 'fa-solid fa-search',
  },
  {
    id: ActivityType.ANAGRAM,
    title: 'Anagram',
    description: 'Karışık harflerden anlamlı kelimeler oluşturun.',
    icon: 'fa-solid fa-shuffle',
  },
  {
    id: ActivityType.ANAGRAM,
    title: 'Anagram (Liste)',
    description: 'Verilen kelimelerin anagramlarını bulun.',
    icon: 'fa-solid fa-list-ol',
  },
   {
    id: ActivityType.FIND_THE_DIFFERENCE,
    title: 'Farklı Olanı Bul (Görsel)',
    description: 'Gruplar içinde farklı olan kelimeyi bulun.',
    icon: 'fa-solid fa-not-equal',
  },
  {
    id: ActivityType.MATH_PUZZLE,
    title: 'Matematik Bulmacası',
    description: 'Nesnelerle gizlenmiş sayıları bularak denklemleri çözün.',
    icon: 'fa-solid fa-calculator',
  },
  {
    id: ActivityType.STORY_COMPREHENSION,
    title: 'Hikaye Anlama',
    description: 'Kısa bir hikaye okuyun ve ilgili soruları yanıtlayın.',
    icon: 'fa-solid fa-book-open',
  },
   {
    id: ActivityType.STORY_COMPREHENSION,
    title: 'Hikayeye Dikkat - 1',
    description: 'Yeni bir hikaye okuyun ve ilgili soruları yanıtlayın.',
    icon: 'fa-solid fa-book-bookmark',
  },
   {
    id: ActivityType.STORY_COMPREHENSION,
    title: 'Hikayeye Dikkat - 2',
    description: 'Yeni bir hikaye okuyun ve ilgili soruları yanıtlayın.',
    icon: 'fa-solid fa-book-open-reader',
  },
  {
    id: ActivityType.WORD_COMPARISON,
    title: 'Kelime Karşılaştırma',
    description: 'İki kelime listesini karşılaştırıp farklı olanları bulun.',
    icon: 'fa-solid fa-code-compare',
  },
  {
    id: ActivityType.WORDS_IN_STORY,
    title: 'Metindeki Kelimeler',
    description: 'Metinde geçen ve geçmeyen kelimeleri listeden bulun.',
    icon: 'fa-solid fa-book-reader',
  },
  {
    id: ActivityType.STROOP_TEST,
    title: 'Stroop Testi (Renk Oku)',
    description: 'Kelimeyi değil, kelimenin yazıldığı rengi söyleyin.',
    icon: 'fa-solid fa-palette',
  },
  {
    id: ActivityType.NUMBER_PATTERN,
    title: 'Sayı Örüntüsü Bulma',
    description: 'Sayı dizisindeki kuralı bulup eksik sayıyı tamamlayın.',
    icon: 'fa-solid fa-arrow-trend-up',
  },
  {
    id: ActivityType.SPELLING_CHECK,
    title: 'Doğru Yazılışı Bulma',
    description: 'Verilen kelimeler arasından doğru yazılanı seçin.',
    icon: 'fa-solid fa-spell-check',
  },
  {
    id: ActivityType.LETTER_GRID_TEST,
    title: 'Harf Izgara Testi',
    description: 'Harf yığını içinden istenen harfleri bulun ve işaretleyin.',
    icon: 'fa-solid fa-border-all',
  },
  {
    id: ActivityType.NUMBER_SEARCH,
    title: 'Sayı Avı',
    description: 'Karışık sayılar arasından belirli bir sırayı takip edin.',
    icon: 'fa-solid fa-arrow-down-1-9',
  },
  {
    id: ActivityType.WORD_MEMORY,
    title: 'Süper Hafıza (Kelime)',
    description: 'Kelimeleri ezberleyin ve sonraki sayfada hatırlayın.',
    icon: 'fa-solid fa-brain',
  },
  {
    id: ActivityType.STORY_CREATION_PROMPT,
    title: 'Hikaye Oluşturma',
    description: 'Verilen anahtar kelimeleri kullanarak bir hikaye yazın.',
    icon: 'fa-solid fa-pencil-alt',
  },
  {
    id: ActivityType.ODD_ONE_OUT,
    title: 'Farkı Fark Et (Anlamsal)',
    description: 'Kelime gruplarında anlamsal olarak farklı olanı bulun.',
    icon: 'fa-solid fa-lightbulb-question',
  },
  {
    id: ActivityType.SHAPE_MATCHING,
    title: 'Şekil Eşleştirme',
    description: 'Aynı şekil dizilerini bulun ve eşleştirin.',
    icon: 'fa-solid fa-shapes',
  },
  {
    id: ActivityType.SYMBOL_CIPHER,
    title: 'Şifre Çözme',
    description: 'Şekillerle kodlanmış kelimeleri anahtara bakarak çözün.',
    icon: 'fa-solid fa-key',
  },
  {
    id: ActivityType.PROVERB_FILL_IN_THE_BLANK,
    title: 'Atasözü Avı',
    description: 'Atasözlerindeki eksik kelimeleri bulun ve tamamlayın.',
    icon: 'fa-solid fa-quote-left',
  },
  {
    id: ActivityType.LETTER_BRIDGE,
    title: 'Harf Köprüsü',
    description: 'İki kelime arasına bir harf yerleştirerek yeni kelimeler oluşturun.',
    icon: 'fa-solid fa-bridge',
  },
  {
    id: ActivityType.FIND_THE_DUPLICATE_IN_ROW,
    title: 'İkiliyi Bul',
    description: 'Her satırda tekrar eden harfi veya rakamı bulun.',
    icon: 'fa-solid fa-clone',
  },
  {
    id: ActivityType.WORD_LADDER,
    title: 'Kelime Merdiveni',
    description: 'Her adımda tek harf değiştirerek bir kelimeden diğerine ulaşın.',
    icon: 'fa-solid fa-stairs',
  },
  {
    id: ActivityType.FIND_IDENTICAL_WORD,
    title: 'Aynısını Bul',
    description: 'Birbirine çok benzeyen kelimelerden aynı olan çifti bulun.',
    icon: 'fa-solid fa-equals',
  },
  {
    id: ActivityType.WORD_FORMATION,
    title: 'Harflerden Kelime Türetme',
    description: 'Verilen harfleri kullanarak anlamlı kelimeler oluşturun.',
    icon: 'fa-solid fa-puzzle-piece',
  },
  {
    id: ActivityType.REVERSE_WORD,
    title: 'Ters Oku - Ters Uko',
    description: 'Verilen kelimeleri tersten yazma alıştırması yapın.',
    icon: 'fa-solid fa-right-left-rotate',
  },
  {
    id: ActivityType.FIND_LETTER_PAIR,
    title: 'Harf İkilisini Bul',
    description: 'Harf tablosunda istenen harf ikilisini bulun.',
    icon: 'fa-solid fa-magnifying-glass-plus',
  },
  {
    id: ActivityType.WORD_GROUPING,
    title: 'Gruplama',
    description: 'Kelimeleri doğru kategorilere ayırın.',
    icon: 'fa-solid fa-folder-tree',
  },
  {
    id: ActivityType.VISUAL_MEMORY,
    title: 'Süper Hafıza (Görsel)',
    description: 'Görselleri aklınızda tutup sonraki sayfada bulun.',
    icon: 'fa-solid fa-images',
  },
   {
    id: ActivityType.CHARACTER_MEMORY,
    title: 'Dikkat - Hafıza',
    description: 'Karakterleri aklınızda tutup sonraki sayfada bulun.',
    icon: 'fa-solid fa-users-viewfinder',
  },
  {
    id: ActivityType.STORY_ANALYSIS,
    title: 'Hikaye Analizi',
    description: 'Hikayedeki eş/zıt anlamlı kelimeleri ve detayları bulun.',
    icon: 'fa-solid fa-magnifying-glass-chart',
  },
  {
    id: ActivityType.COORDINATE_CIPHER,
    title: 'Gizemli Bulmaca',
    description: 'Koordinatları verilen harfleri birleştirip şifreyi çözün.',
    icon: 'fa-solid fa-map-location-dot',
  },
  {
    id: ActivityType.PROVERB_SEARCH,
    title: 'Atasözü Avı',
    description: 'Harf tablosunda gizlenmiş atasözünü bulun.',
    icon: 'fa-solid fa-comment-dots',
  },
  {
    id: ActivityType.TARGET_SEARCH,
    title: 'Dikkatli Göz',
    description: 'Karakter yığını içinde hedef karakteri bulun.',
    icon: 'fa-solid fa-crosshairs',
  },
  {
    id: ActivityType.SHAPE_NUMBER_PATTERN,
    title: 'Şekilli Sayı Örüntüsü',
    description: 'Şekillerdeki sayılar arasındaki kuralı bulup eksik sayıyı tamamlayın.',
    icon: 'fa-solid fa-draw-polygon',
  },
  {
    id: ActivityType.GRID_DRAWING,
    title: 'Ayna Çizimi',
    description: 'Soldaki deseni sağdaki boş alana kopyalayın.',
    icon: 'fa-solid fa-vector-square',
  },
  {
    id: ActivityType.COLOR_WHEEL_MEMORY,
    title: 'Renk Çemberi',
    description: 'Renk çarkındaki nesneleri ezberleyip doğru yerleştirin.',
    icon: 'fa-solid fa-bullseye',
  },
  {
    id: ActivityType.IMAGE_COMPREHENSION,
    title: 'Resme Dikkat',
    description: 'Resmi inceleyip detaylarla ilgili soruları yanıtlayın.',
    icon: 'fa-solid fa-image',
  },
  {
    id: ActivityType.CHARACTER_MEMORY,
    title: 'Hafızanda Tut (Karakter)',
    description: 'Karakterleri aklınızda tutup sonraki sayfada hatırlayın.',
    icon: 'fa-solid fa-user-friends',
  },
  {
    id: ActivityType.STORY_SEQUENCING,
    title: 'Hikaye Oluşturma (Sıralama)',
    description: 'Karışık resimleri sıralayarak anlamlı bir hikaye oluşturun.',
    icon: 'fa-solid fa-film',
  },
  {
    id: ActivityType.CHAOTIC_NUMBER_SEARCH,
    title: 'Sayıları Bulma',
    description: 'Karışık sayılar arasından 1\'den 50\'ye kadar olanları boyayın.',
    icon: 'fa-solid fa-search-plus',
  },
  {
    id: ActivityType.BLOCK_PAINTING,
    title: 'Blok Boyama',
    description: 'Verilen blokları kullanarak deseni doğru renklere boyayın.',
    icon: 'fa-solid fa-puzzle-piece',
  },
  {
    id: ActivityType.MINI_WORD_GRID,
    title: 'Kelime Bulmaca (Mini)',
    description: 'Küçük tablolarda renkli harften başlayan kelimeleri bulun.',
    icon: 'fa-solid fa-table-cells',
  },
  {
    id: ActivityType.VISUAL_ODD_ONE_OUT,
    title: 'Sözcük Avı (Farklı Şekil)',
    description: 'Her satırda diğerlerinden farklı olan şekli bulun.',
    icon: 'fa-solid fa-circle-nodes',
  },
  {
    id: ActivityType.SHAPE_COUNTING,
    title: 'Kaç Tane Üçgen Var?',
    description: 'Karmaşık şekillerin içine gizlenmiş üçgenleri sayın.',
    icon: 'fa-solid fa-calculator-simple',
  },
  {
    id: ActivityType.SYMMETRY_DRAWING,
    title: 'Noktalarla Dans (Simetri)',
    description: 'Verilen desenin simetri eksenine göre yansımasını çizin.',
    icon: 'fa-solid fa-reflect-horizontal',
  },
  {
    id: ActivityType.BURDON_TEST,
    title: 'Burdon Dikkat Testi',
    description: 'Aşağıdaki satırlarda “a, b, d, g” harflerini bulup yuvarlak içine alalım.',
    icon: 'fa-solid fa-tasks',
  },
  {
    id: ActivityType.FIND_DIFFERENT_STRING,
    title: 'Farklı Olanı Bulma',
    description: 'Aşağıdaki sütunlarda yer alan harf sıralamasında VWN’den farklı olan harf grubunu işaretleyelim.',
    icon: 'fa-solid fa-not-equal',
  },
  {
    id: ActivityType.DOT_PAINTING,
    title: 'Nokta Boyama',
    description: 'Noktaların bulunduğu alanları boyayarak gizli şekli ortaya çıkaralım.',
    icon: 'fa-solid fa-paint-brush',
  },
  {
    id: ActivityType.ABC_CONNECT,
    title: 'ABC Bağlama',
    description: 'Örnekteki gibi aynı harflerle belirtilen noktaları birbirleriyle kesişmeyecek şekilde yatay ve dikey çizgilerle birleştirelim.',
    icon: 'fa-solid fa-draw-polygon',
  },
  {
    id: ActivityType.PASSWORD_FINDER,
    title: 'Şifre Bul',
    description: 'Baş harfi büyük yazılması gereken kelimeleri bulup şifreyi çözün.',
    icon: 'fa-solid fa-user-secret',
  },
  {
    id: ActivityType.SYLLABLE_COMPLETION,
    title: 'Eksik Kelimeler',
    description: 'Eksik heceleri bularak kelimeleri tamamlayın ve hikaye yazın.',
    icon: 'fa-solid fa-puzzle-piece',
  },
  {
    id: ActivityType.SYNONYM_WORD_SEARCH,
    title: 'Eş Anlamlı Kelime Avı',
    description: 'Kelimelerin eş anlamlılarını bulup bulmacada arayın.',
    icon: 'fa-solid fa-file-word',
  },
  {
    id: ActivityType.WORD_CONNECT,
    title: 'Kelime Bağlama',
    description: 'Anlamca ilişkili kelimeleri çizgilerle birleştirin.',
    icon: 'fa-solid fa-link',
  },
  {
    id: ActivityType.SPIRAL_PUZZLE,
    title: 'Sarmal Bulmaca',
    description: 'İpuçlarından kelimeleri bulup sarmal bulmacaya yerleştirin.',
    icon: 'fa-solid fa-hurricane',
  },
  {
    id: ActivityType.CROSSWORD,
    title: 'Çapraz Bulmaca',
    description: 'Verilen ipuçlarıyla bulmacayı çözün ve şifreyi bulun.',
    icon: 'fa-solid fa-border-all',
  },
  {
    id: ActivityType.JUMBLED_WORD_STORY,
    title: 'Kelime Bulma ve Hikaye Yazma',
    description: 'Karışık harflerden kelimeler bulun ve bu kelimelerle hikaye yazın.',
    icon: 'fa-solid fa-pen-nib',
  },
  {
    id: ActivityType.HOMONYM_SENTENCE_WRITING,
    title: 'Kelime Ağı (Eş Sesli)',
    description: 'Eş sesli kelimeler için iki farklı anlama gelen cümleler yazın.',
    icon: 'fa-solid fa-water',
  },
  {
    id: ActivityType.WORD_GRID_PUZZLE,
    title: 'Kelime Ağı (Yerleştirme)',
    description: 'Verilen kelimeleri bulmaca tablosuna doğru şekilde yerleştirin.',
    icon: 'fa-solid fa-table-cells-large',
  },
  {
    id: ActivityType.PROVERB_SAYING_SORT,
    title: 'Şifre Bul (Atasözü/Özdeyiş)',
    description: 'Cümlelerin atasözü mü yoksa özdeyiş mi olduğunu belirleyin.',
    icon: 'fa-solid fa-arrows-split-up-and-left',
  },
  {
    id: ActivityType.HOMONYM_IMAGE_MATCH,
    title: 'Resim Eşleştirme (Eş Sesli)',
    description: 'Eş sesli kelimelere ait görselleri eşleştirin.',
    icon: 'fa-solid fa-object-ungroup',
  },
  {
    id: ActivityType.ANTONYM_FLOWER_PUZZLE,
    title: 'Eşleştir (Zıt Anlamlı)',
    description: 'Papatyaların ortasındaki kelimelerin zıt anlamlılarını bulun ve şifreyi çözün.',
    icon: 'fa-solid fa-fan',
  },
  {
    id: ActivityType.PROVERB_WORD_CHAIN,
    title: 'Atasözü/Özdeyiş Bulma',
    description: 'Karışık kelimelerden atasözleri ve özdeyişler oluşturun.',
    icon: 'fa-solid fa-link-slash',
  },
  {
    id: ActivityType.THEMATIC_ODD_ONE_OUT,
    title: 'Farklı Özelliği Bulma',
    description: 'Belirli bir temaya uymayan kelimeyi bulun.',
    icon: 'fa-solid fa-magnifying-glass-arrow-right',
  },
  {
    id: ActivityType.SYNONYM_ANTONYM_GRID,
    title: 'Kelime Bulma (Eş/Zıt Anlamlı)',
    description: 'Kelimelerin eş ve zıt anlamlılarını bulup bulmacaya yerleştirin.',
    icon: 'fa-solid fa-right-left',
  },
  {
    id: ActivityType.PUNCTUATION_COLORING,
    title: 'Görsel Boyama (Noktalama)',
    description: 'Cümlelere uygun noktalama işaretlerini bularak resmi boyayın.',
    icon: 'fa-solid fa-pencil',
  },
  {
    id: ActivityType.PUNCTUATION_MAZE,
    title: 'Labirent (Noktalama)',
    description: 'Doğru kuralı bularak labirentte doğru yolu bulun.',
    icon: 'fa-solid fa-mouse',
  },
  {
    id: ActivityType.ANTONYM_RESFEBE,
    title: 'Resfebe (Zıt Anlamlı)',
    description: 'Resfebe ile kelimeyi bulun, sonra zıt anlamlısını yazın.',
    icon: 'fa-solid fa-image-landscape',
  },
  {
    id: ActivityType.THEMATIC_WORD_SEARCH_COLOR,
    title: 'Kelime Bulma (Tematik)',
    description: 'Belirli bir konudaki kelimeleri bulmacada bulun ve boyayın.',
    icon: 'fa-solid fa-highlighter',
  },
  {
    id: ActivityType.THEMATIC_ODD_ONE_OUT_SENTENCE,
    title: 'Şifre Bul (Farklı Kelime)',
    description: 'Her grupta farklı olan kelimeyi bulun ve cümle kurun.',
    icon: 'fa-solid fa-user-secret',
  },
  {
    id: ActivityType.PROVERB_SENTENCE_FINDER,
    title: 'Cümle Bulma (Atasözü)',
    description: 'Karışık kelimelerden atasözleri oluşturun ve boyayın.',
    icon: 'fa-solid fa-comments',
  },
  {
    id: ActivityType.SYNONYM_SEARCH_STORY,
    title: 'Dikkat Testi (Eş Anlamlı)',
    description: 'Kelimelerin eş anlamlılarını bulun, bulmacada arayın ve hikaye yazın.',
    icon: 'fa-solid fa-file-signature',
  },
  {
    id: ActivityType.PUNCTUATION_SPIRAL_PUZZLE,
    title: 'Sarmal Bulmaca (Noktalama)',
    description: 'Dil bilgisi ve noktalama kuralları ile sarmal bulmacayı çözün.',
    icon: 'fa-solid fa-pen-ruler',
  },
  {
    id: ActivityType.COLUMN_ODD_ONE_OUT_SENTENCE,
    title: 'Farklı Özelliği Bulma (Sütun)',
    description: 'Her sütunda farklı olan kelimeyi bulup cümle kurun.',
    icon: 'fa-solid fa-table-columns',
  },
  {
    id: ActivityType.SYNONYM_ANTONYM_COLORING,
    title: 'Görsel Boyama (Eş/Zıt Anlamlı)',
    description: 'Doğru eş/zıt anlamlı kelimeyi bularak resmi boyayın.',
    icon: 'fa-solid fa-fill-drip',
  },
  {
    id: ActivityType.PUNCTUATION_PHONE_NUMBER,
    title: 'Bul Bakalım (Telefon Numarası)',
    description: 'Noktalama ipuçlarını çözerek gizli telefon numarasını bulun.',
    icon: 'fa-solid fa-phone-volume',
  },
  {
    id: ActivityType.THEMATIC_JUMBLED_WORD_STORY,
    title: 'Kelime Bulma ve Metin Yazma',
    description: 'Karışık harflerden tematik kelimeler oluşturup metin yazın.',
    icon: 'fa-solid fa-feather-pointed',
  },
  {
    id: ActivityType.SYNONYM_MATCHING_PATTERN,
    title: 'Desen Bulmaca (Eş Anlamlı)',
    description: 'Tematik kelimelerin eş anlamlılarını bularak eşleştirin.',
    icon: 'fa-solid fa-sitemap',
  },
  {
    id: ActivityType.FUTOSHIKI,
    title: 'Futoşiki',
    description: 'Büyüktür/küçüktür sembollerine göre sayıları yerleştirin.',
    icon: 'fa-solid fa-greater-than-less-than',
  },
  {
    id: ActivityType.NUMBER_PYRAMID,
    title: 'Sihirli Piramit (Toplama)',
    description: 'Sayı piramidindeki eksik sayıları toplama kuralına göre tamamlayın.',
    icon: 'fa-solid fa-chart-gantt',
  },
  {
    id: ActivityType.NUMBER_CAPSULE,
    title: 'Kapsül Oyunu',
    description: 'Tek ve çift sayılarla toplama yaparak kapsülleri doldurun.',
    icon: 'fa-solid fa-capsules',
  },
  {
    id: ActivityType.ODD_EVEN_SUDOKU,
    title: 'Tek-Çift Sudoku',
    description: 'Klasik Sudoku kurallarına ek olarak tek/çift sayı kuralını uygulayın.',
    icon: 'fa-solid fa-grid-2-plus',
  },
  {
    id: ActivityType.ROMAN_NUMERAL_CONNECT,
    title: 'ABC Bağlama (Romen Rakamlı)',
    description: 'Aynı Romen rakamlarını yolları kesişmeyecek şekilde birleştirin.',
    icon: 'fa-solid fa-v',
  },
  {
    id: ActivityType.ROMAN_NUMERAL_STAR_HUNT,
    title: 'Yıldız Avı (Romen Rakamlı)',
    description: 'Romen rakamlarını ipucu olarak kullanarak yıldızları bulun.',
    icon: 'fa-solid fa-star-of-david',
  },
  {
    id: ActivityType.ROUNDING_CONNECT,
    title: 'ABC Bağlamaca (Yuvarlama)',
    description: 'Aynı değere yuvarlanan sayıları birbirine bağlayın.',
    icon: 'fa-solid fa-arrows-turn-to-dots',
  },
  {
    id: ActivityType.ROMAN_NUMERAL_MULTIPLICATION,
    title: 'İşlem Karesi (Romen Rakamlı)',
    description: 'Çarpma işlemi yaparak işlem karesindeki boşlukları doldurun.',
    icon: 'fa-solid fa-xmarks-lines',
  },
  {
    id: ActivityType.ARITHMETIC_CONNECT,
    title: 'ABC Bağlamaca (İşlemler)',
    description: 'Aynı sonucu veren işlemleri birbirine bağlayın.',
    icon: 'fa-solid fa-link',
  },
  {
    id: ActivityType.ROMAN_ARABIC_MATCH_CONNECT,
    title: 'ABC Bağlama (Romen Rakamı)',
    description: 'Romen rakamlarını normal sayılarla eşleştirin.',
    icon: 'fa-solid fa-arrow-right-arrow-left',
  },
  {
    id: ActivityType.SUDOKU_6X6_SHADED,
    title: 'Tek-Çift Sudoku (6x6)',
    description: '6x6 Sudoku\'yu tek/çift sayı kuralıyla çözün.',
    icon: 'fa-solid fa-table-cells',
  },
  {
    id: ActivityType.KENDOKU,
    title: 'Kendoku',
    description: 'İşlem ipuçlarını kullanarak mantık bulmacasını çözün.',
    icon: 'fa-solid fa-calculator',
  },
  {
    id: ActivityType.DIVISION_PYRAMID,
    title: 'Sihirli Piramit (Bölme)',
    description: 'Piramitteki sayıları bölme kuralına göre bulun.',
    icon: 'fa-solid fa-divide',
  },
  {
    id: ActivityType.MULTIPLICATION_PYRAMID,
    title: 'Sihirli Piramit (Çarpma)',
    description: 'Piramitteki sayıları çarpma kuralına göre bulun.',
    icon: 'fa-solid fa-xmark',
  },
  {
    id: ActivityType.OPERATION_SQUARE_SUBTRACTION,
    title: 'İşlem Karesi (Çıkarma)',
    description: 'Çıkarma işlemleri yaparak işlem karesini tamamlayın.',
    icon: 'fa-solid fa-minus',
  },
  {
    id: ActivityType.OPERATION_SQUARE_FILL_IN,
    title: 'İşlem Karesi (Yerleştirme)',
    description: 'Verilen sayıları işlem karesine doğru şekilde yerleştirin.',
    icon: 'fa-solid fa-plus',
  },
  {
    id: ActivityType.MULTIPLICATION_WHEEL,
    title: 'Çarpım Çarkı',
    description: 'Sayıları yerleştirerek çarpım çarkını tamamlayın.',
    icon: 'fa-solid fa-circle-notch',
  },
  {
    id: ActivityType.TARGET_NUMBER,
    title: 'Hedef Sayı',
    description: 'Verilen sayılarla dört işlem yaparak hedef sayıya ulaşın.',
    icon: 'fa-solid fa-bullseye',
  },
  {
    id: ActivityType.OPERATION_SQUARE_MULT_DIV,
    title: 'İşlem Karesi (Çarpma/Bölme)',
    description: 'Çarpma ve bölme işlemleri yaparak işlem karesini tamamlayın.',
    icon: 'fa-solid fa-calculator',
  },
  {
    id: ActivityType.SHAPE_SUDOKU,
    title: 'Şekilli Sudoku',
    description: 'Her satır, sütun ve bölgede şekilleri tekrar etmeden yerleştirin.',
    icon: 'fa-solid fa-table-cells',
  },
  {
    id: ActivityType.WEIGHT_CONNECT,
    title: 'ABC Bağlama (Ağırlık)',
    description: 'Birbirine eşit olan ağırlıkları çizgilerle birleştirin.',
    icon: 'fa-solid fa-weight-hanging',
  },
  {
    id: ActivityType.TARGET_NUMBER,
    title: 'Hedef Sayı (Paralar)',
    description: 'Verilen paralarla dört işlem yaparak hedef paraya ulaşın.',
    icon: 'fa-solid fa-coins',
  },
  {
    id: ActivityType.RESFEBE,
    title: 'Resfebe',
    description: 'Resim ve harflerle kelime türetme oyunu.',
    icon: 'fa-solid fa-puzzle-piece',
  },
  {
    id: ActivityType.FUTOSHIKI_LENGTH,
    title: 'Futoşiki (Uzunluk)',
    description: 'Uzunluk ölçü birimlerini büyüktür/küçüktür işaretlerine göre yerleştirin.',
    icon: 'fa-solid fa-ruler-horizontal',
  },
  {
    id: ActivityType.MATCHSTICK_SYMMETRY,
    title: 'Kibrit İşlemleri (Simetri)',
    description: 'Kibritlerle yapılmış şeklin simetriğini çizin.',
    icon: 'fa-solid fa-grip-lines-vertical',
  },
  {
    id: ActivityType.WORD_WEB,
    title: 'Kelime Ağı',
    description: 'Verilen kelimeleri bulmaca ızgarasına yerleştirin.',
    icon: 'fa-solid fa-diagram-project',
  },
  {
    id: ActivityType.STAR_HUNT,
    title: 'Yıldız Avı (Geometrik Cisimler)',
    description: 'Yıldız sayısına göre doğru geometrik cismi bulun.',
    icon: 'fa-solid fa-star',
  },
  {
    id: ActivityType.LENGTH_CONNECT,
    title: 'ABC Bağlama (Uzunluk)',
    description: 'Birbirine eşit olan uzunluk ölçülerini birleştirin.',
    icon: 'fa-solid fa-arrows-left-right-to-line',
  },
  {
    id: ActivityType.VISUAL_NUMBER_PATTERN,
    title: 'Görsel Sayı Örüntüsü',
    description: 'Görsel dizideki kuralı bulup eksik sayıyı tamamlayın.',
    icon: 'fa-solid fa-sort-numeric-up',
  },
  {
    id: ActivityType.MISSING_PARTS,
    title: 'Eksik Kelimeler (Eşleştirme)',
    description: 'Kelime parçalarını doğru şekilde birleştirin.',
    icon: 'fa-solid fa-link',
  },
  {
    id: ActivityType.PROFESSION_CONNECT,
    title: 'Kelime Bağlama (Meslekler)',
    description: 'Meslekleri ilgili görsellerle eşleştirin.',
    icon: 'fa-solid fa-user-tie',
  },
  {
    id: ActivityType.VISUAL_ODD_ONE_OUT_THEMED,
    title: 'Farklı Özelliği Bulma (Tematik)',
    description: 'Her meslek grubunda, konuyla ilgisiz olan görseli bulun.',
    icon: 'fa-solid fa-user-group-slash',
  },
  {
    id: ActivityType.LOGIC_GRID_PUZZLE,
    title: 'Zekâ Sorusu (Mantık Tablosu)',
    description: 'Verilen ipuçlarını kullanarak mantık tablosunu doldurun.',
    icon: 'fa-solid fa-table-list',
  },
  {
    id: ActivityType.IMAGE_ANAGRAM_SORT,
    title: 'Kart Sıralama (Anagram)',
    description: 'Görsellerle eşleşen karışık kelimeleri çözüp sıralayın.',
    icon: 'fa-solid fa-sort-alpha-down',
  },
  {
    id: ActivityType.ANAGRAM_IMAGE_MATCH,
    title: 'Resim - Kelime Eşleme (Anagram)',
    description: 'Karışık kelimeleri çözüp ilgili görsellerle eşleştirin.',
    icon: 'fa-solid fa-arrow-right-arrow-left',
  },
  {
    id: ActivityType.SYLLABLE_WORD_SEARCH,
    title: 'Eksik Kelimeler ve Bulmaca',
    description: 'Hecelerle kelimeler oluşturun ve kelime avında bulun.',
    icon: 'fa-solid fa-puzzle',
  },
  {
    id: ActivityType.WORD_SEARCH_WITH_PASSWORD,
    title: 'Kelime Avı (Şifreli)',
    description: 'Kelimeleri bulun ve renkli kutulardan şifreyi çözün.',
    icon: 'fa-solid fa-key',
  },
  {
    id: ActivityType.WORD_WEB_WITH_PASSWORD,
    title: 'Kelime Ağı (Şifreli)',
    description: 'Kelimeleri yerleştirin ve renkli sütundan şifreyi bulun.',
    icon: 'fa-solid fa-lock',
  },
  {
    id: ActivityType.LETTER_GRID_WORD_FIND,
    title: 'Kelime Bulma (Tablo)',
    description: 'Harf tablosunda gizlenmiş kelimeleri bulun ve metin yazın.',
    icon: 'fa-solid fa-pen-to-square',
  },
  {
    id: ActivityType.WORD_PLACEMENT_PUZZLE,
    title: 'Kelime Yerleştirme',
    description: 'Verilen kelimeleri harf sayısına göre bulmaca diyagramına yerleştirin.',
    icon: 'fa-solid fa-arrows-to-dot',
  },
  {
    id: ActivityType.POSITIONAL_ANAGRAM,
    title: 'Yer Değiştirmeli Anagram',
    description: 'Numaralı kutucuklardaki harflerin yerlerini değiştirerek kelimeler bulun.',
    icon: 'fa-solid fa-arrow-down-1-9',
  }
];

export const ACTIVITY_CATEGORIES: ActivityCategory[] = [
  {
    id: 'memory_attention',
    title: '🧠 Hafıza & Dikkat',
    description: 'Görsel hafıza ve dikkat geliştirme oyunları',
    icon: 'fa-solid fa-brain',
    activities: [
      ActivityType.WORD_MEMORY,
      ActivityType.VISUAL_MEMORY,
      ActivityType.NUMBER_SEARCH,
      ActivityType.FIND_THE_DUPLICATE_IN_ROW,
      ActivityType.LETTER_GRID_TEST,
      ActivityType.FIND_LETTER_PAIR,
      ActivityType.TARGET_SEARCH,
      ActivityType.COLOR_WHEEL_MEMORY,
      ActivityType.IMAGE_COMPREHENSION,
      ActivityType.CHARACTER_MEMORY,
      ActivityType.BURDON_TEST,
      ActivityType.STROOP_TEST,
      ActivityType.CHAOTIC_NUMBER_SEARCH,
    ]
  },
  {
    id: 'reading_comprehension',
    title: '📚 Okuma & Anlama',
    description: 'Hikayeler, atasözleri ve okuduğunu anlama etkinlikleri',
    icon: 'fa-solid fa-book-open-reader',
    activities: [
      ActivityType.STORY_COMPREHENSION,
      ActivityType.WORDS_IN_STORY,
      ActivityType.STORY_CREATION_PROMPT,
      ActivityType.STORY_ANALYSIS,
      ActivityType.STORY_SEQUENCING,
      ActivityType.JUMBLED_WORD_STORY,
      ActivityType.THEMATIC_JUMBLED_WORD_STORY,
      ActivityType.SYNONYM_SEARCH_STORY,
      ActivityType.PROVERB_FILL_IN_THE_BLANK,
      ActivityType.PROVERB_SAYING_SORT,
      ActivityType.PROVERB_WORD_CHAIN,
      ActivityType.PROVERB_SENTENCE_FINDER,
      ActivityType.PROVERB_SEARCH,
    ]
  },
  {
    id: 'word_games',
    title: '📝 Kelime Oyunları',
    description: 'Anagram, sözcük avı, bulmaca ve dil becerileri',
    icon: 'fa-solid fa-spell-check',
    activities: [
      ActivityType.WORD_SEARCH,
      ActivityType.ANAGRAM,
      ActivityType.SPELLING_CHECK,
      ActivityType.LETTER_BRIDGE,
      ActivityType.WORD_LADDER,
      ActivityType.WORD_FORMATION,
      ActivityType.REVERSE_WORD,
      ActivityType.WORD_GROUPING,
      ActivityType.MINI_WORD_GRID,
      ActivityType.PASSWORD_FINDER,
      ActivityType.SYLLABLE_COMPLETION,
      ActivityType.SYNONYM_WORD_SEARCH,
      ActivityType.SPIRAL_PUZZLE,
      ActivityType.CROSSWORD,
      ActivityType.HOMONYM_SENTENCE_WRITING,
      ActivityType.WORD_GRID_PUZZLE,
      ActivityType.HOMONYM_IMAGE_MATCH,
      ActivityType.ANTONYM_FLOWER_PUZZLE,
      ActivityType.SYNONYM_ANTONYM_GRID,
      ActivityType.ANTONYM_RESFEBE,
      ActivityType.RESFEBE,
      ActivityType.THEMATIC_WORD_SEARCH_COLOR,
      ActivityType.PUNCTUATION_SPIRAL_PUZZLE,
      ActivityType.SYNONYM_MATCHING_PATTERN,
      ActivityType.MISSING_PARTS,
      ActivityType.WORD_WEB,
      ActivityType.SYLLABLE_WORD_SEARCH,
      ActivityType.WORD_SEARCH_WITH_PASSWORD,
      ActivityType.WORD_WEB_WITH_PASSWORD,
      ActivityType.LETTER_GRID_WORD_FIND,
      ActivityType.WORD_PLACEMENT_PUZZLE,
      ActivityType.POSITIONAL_ANAGRAM,
      ActivityType.IMAGE_ANAGRAM_SORT,
      ActivityType.ANAGRAM_IMAGE_MATCH,
    ]
  },
  {
    id: 'math_logic_games',
    title: '🎲 Matematik & Mantık Oyunları',
    description: 'Sayısal düşünme ve mantık yürütme becerileri',
    icon: 'fa-solid fa-dice',
    activities: [
      ActivityType.MATH_PUZZLE,
      ActivityType.NUMBER_PATTERN,
      ActivityType.ODD_ONE_OUT,
      ActivityType.THEMATIC_ODD_ONE_OUT,
      ActivityType.THEMATIC_ODD_ONE_OUT_SENTENCE,
      ActivityType.COLUMN_ODD_ONE_OUT_SENTENCE,
      ActivityType.PUNCTUATION_MAZE,
      ActivityType.PUNCTUATION_PHONE_NUMBER,
      ActivityType.SHAPE_NUMBER_PATTERN,
      ActivityType.FUTOSHIKI,
      ActivityType.NUMBER_PYRAMID,
      ActivityType.NUMBER_CAPSULE,
      ActivityType.ODD_EVEN_SUDOKU,
      ActivityType.ROMAN_NUMERAL_CONNECT,
      ActivityType.ROMAN_NUMERAL_STAR_HUNT,
      ActivityType.ROUNDING_CONNECT,
      ActivityType.ROMAN_NUMERAL_MULTIPLICATION,
      ActivityType.ARITHMETIC_CONNECT,
      ActivityType.ROMAN_ARABIC_MATCH_CONNECT,
      ActivityType.SUDOKU_6X6_SHADED,
      ActivityType.KENDOKU,
      ActivityType.DIVISION_PYRAMID,
      ActivityType.MULTIPLICATION_PYRAMID,
      ActivityType.OPERATION_SQUARE_SUBTRACTION,
      ActivityType.OPERATION_SQUARE_FILL_IN,
      ActivityType.MULTIPLICATION_WHEEL,
      ActivityType.TARGET_NUMBER,
      ActivityType.OPERATION_SQUARE_MULT_DIV,
      ActivityType.SHAPE_SUDOKU,
      ActivityType.WEIGHT_CONNECT,
      ActivityType.FUTOSHIKI_LENGTH,
      ActivityType.LENGTH_CONNECT,
      ActivityType.VISUAL_NUMBER_PATTERN,
      ActivityType.LOGIC_GRID_PUZZLE,
    ]
  },
  {
    id: 'visual_perceptual_skills',
    title: '🎨 Görsel Algı Becerileri',
    description: 'Şekil tanıma, görsel ayırt etme ve mekansal farkındalık',
    icon: 'fa-solid fa-eye',
    activities: [
      ActivityType.FIND_THE_DIFFERENCE,
      ActivityType.WORD_COMPARISON,
      ActivityType.SHAPE_MATCHING,
      ActivityType.FIND_IDENTICAL_WORD,
      ActivityType.GRID_DRAWING,
      ActivityType.SYMBOL_CIPHER,
      ActivityType.BLOCK_PAINTING,
      ActivityType.VISUAL_ODD_ONE_OUT,
      ActivityType.SHAPE_COUNTING,
      ActivityType.SYMMETRY_DRAWING,
      ActivityType.FIND_DIFFERENT_STRING,
      ActivityType.DOT_PAINTING,
      ActivityType.ABC_CONNECT,
      ActivityType.WORD_CONNECT,
      ActivityType.COORDINATE_CIPHER,
      ActivityType.PROFESSION_CONNECT,
      ActivityType.MATCHSTICK_SYMMETRY,
      ActivityType.VISUAL_ODD_ONE_OUT_THEMED,
      ActivityType.PUNCTUATION_COLORING,
      ActivityType.SYNONYM_ANTONYM_COLORING,
      ActivityType.STAR_HUNT
    ]
  }
];
