import { Activity, ActivityCategory, ActivityType } from './types';

export const ACTIVITIES: Activity[] = [
    // --- GÖRSEL ALGI ---
    { id: ActivityType.FIND_THE_DIFFERENCE, title: 'Farkı Bul', description: 'Görseller veya metinler arasındaki farkları bulun.', icon: 'fa-solid fa-not-equal' },
    { id: ActivityType.WORD_COMPARISON, title: 'Kelime Karşılaştırma', description: 'İki liste arasındaki farkları tespit edin.', icon: 'fa-solid fa-code-compare' },
    { id: ActivityType.SHAPE_MATCHING, title: 'Şekil Eşleştirme', description: 'Benzer şekil gruplarını eşleştirin.', icon: 'fa-solid fa-shapes' },
    { id: ActivityType.FIND_IDENTICAL_WORD, title: 'Aynısını Bul', description: 'Hedef kelimenin aynısını seçenekler arasından bulun.', icon: 'fa-solid fa-clone' },
    { id: ActivityType.GRID_DRAWING, title: 'Kare Çizim', description: 'Verilen deseni ızgara üzerinde kopyalayın.', icon: 'fa-solid fa-border-all' },
    { id: ActivityType.SYMBOL_CIPHER, title: 'Şekil Şifresi', description: 'Sembollere karşılık gelen harfleri bularak şifreyi çözün.', icon: 'fa-solid fa-puzzle-piece' },
    { id: ActivityType.BLOCK_PAINTING, title: 'Blok Boyama', description: 'Verilen desene göre kareleri boyayın.', icon: 'fa-solid fa-brush' },
    { id: ActivityType.VISUAL_ODD_ONE_OUT, title: 'Görsel Farkı Bul', description: 'Şekiller arasında farklı olanı bulun.', icon: 'fa-regular fa-object-ungroup' },
    { id: ActivityType.SYMMETRY_DRAWING, title: 'Simetri Tamamlama', description: 'Şeklin simetriğini çizerek tamamlayın.', icon: 'fa-solid fa-yin-yang' },
    { id: ActivityType.FIND_DIFFERENT_STRING, title: 'Farklı Diziyi Bul', description: 'Benzer karakter dizileri arasında farklı olanı bulun.', icon: 'fa-solid fa-fingerprint' },
    { id: ActivityType.DOT_PAINTING, title: 'Nokta Boyama', description: 'Koordinatları veya yönergeleri takiperek noktaları boyayın.', icon: 'fa-solid fa-circle-dot' },
    { id: ActivityType.ABC_CONNECT, title: 'Nokta Birleştirme', description: 'Aynı harfleri veya sayıları çizgilerle birleştirin.', icon: 'fa-solid fa-bezier-curve' },
    { id: ActivityType.WORD_CONNECT, title: 'Kelime Bağlama', description: 'İlişkili kelimeleri çizgilerle eşleştirin.', icon: 'fa-solid fa-link' },
    { id: ActivityType.COORDINATE_CIPHER, title: 'Koordinat Şifreleme', description: 'Koordinatları verilen harfleri bularak şifreyi çözün.', icon: 'fa-solid fa-location-crosshairs' },
    { id: ActivityType.PROFESSION_CONNECT, title: 'Meslek Eşleştirme', description: 'Meslekleri araçları veya mekanlarıyla eşleştirin.', icon: 'fa-solid fa-user-doctor' },
    { id: ActivityType.MATCHSTICK_SYMMETRY, title: 'Kibrit Simetrisi', description: 'Kibrit çöpleriyle oluşturulan şeklin yansımasını çizin.', icon: 'fa-solid fa-fire-burner' },
    { id: ActivityType.VISUAL_ODD_ONE_OUT_THEMED, title: 'Tematik Farkı Bul', description: 'Konuyla ilgisiz olan görseli bulun.', icon: 'fa-solid fa-image' },
    { id: ActivityType.STAR_HUNT, title: 'Yıldız Avı', description: 'Tabloda gizli yıldızları mantık kurallarına göre bulun.', icon: 'fa-solid fa-star' },
    { id: ActivityType.SHAPE_COUNTING, title: 'Şekil Sayma', description: 'Karmaşık şekil içindeki belirli geometrik şekilleri sayın.', icon: 'fa-solid fa-layer-group' },

    // --- OKUMA VE SÖZEL ---
    { id: ActivityType.WORD_SEARCH, title: 'Kelime Bulmaca', description: 'Tabloya gizlenmiş kelimeleri bulun.', icon: 'fa-solid fa-table-cells' },
    { id: ActivityType.ANAGRAM, title: 'Anagram', description: 'Karışık harflerden kelime türetin.', icon: 'fa-solid fa-shuffle' },
    { id: ActivityType.SPELLING_CHECK, title: 'Yazım Yanlışı', description: 'Doğru yazılmış kelimeyi bulun.', icon: 'fa-solid fa-check-double' },
    { id: ActivityType.LETTER_BRIDGE, title: 'Harf Köprüsü', description: 'İki kelimeyi birbirine bağlayan ortak harfi bulun.', icon: 'fa-solid fa-bridge' },
    { id: ActivityType.WORD_LADDER, title: 'Kelime Merdiveni', description: 'Bir harf değiştirerek yeni kelimeye ulaşın.', icon: 'fa-solid fa-stairs' },
    { id: ActivityType.WORD_FORMATION, title: 'Kelime Türetmece', description: 'Verilen harflerle kelimeler oluşturun.', icon: 'fa-solid fa-cubes-stacked' },
    { id: ActivityType.REVERSE_WORD, title: 'Ters Oku Düz Yaz', description: 'Tersten yazılmış kelimeleri okuyun.', icon: 'fa-solid fa-rotate-left' },
    { id: ActivityType.WORD_GROUPING, title: 'Kelime Gruplama', description: 'Kelimeleri kategorilerine göre ayırın.', icon: 'fa-solid fa-object-group' },
    { id: ActivityType.MINI_WORD_GRID, title: 'Mini Kelime Kareleri', description: 'Küçük ızgaralarda kelime avı.', icon: 'fa-solid fa-border-none' },
    { id: ActivityType.PASSWORD_FINDER, title: 'Şifre Çözücü', description: 'İpuçlarını kullanarak gizli şifreyi bulun.', icon: 'fa-solid fa-key' },
    { id: ActivityType.SYLLABLE_COMPLETION, title: 'Hece Tamamlama', description: 'Eksik heceleri tamamlayarak kelime oluşturun.', icon: 'fa-solid fa-puzzle-piece' },
    { id: ActivityType.SYNONYM_WORD_SEARCH, title: 'Eş Anlam Avı', description: 'Kelimelerin eş anlamlılarını bulmacada arayın.', icon: 'fa-solid fa-equals' },
    { id: ActivityType.SPIRAL_PUZZLE, title: 'Sarmal Bulmaca', description: 'İçe doğru kıvrılan sarmal bulmacayı çözün.', icon: 'fa-solid fa-hurricane' },
    { id: ActivityType.CROSSWORD, title: 'Çapraz Bulmaca', description: 'Klasik kare bulmaca.', icon: 'fa-solid fa-border-all' },
    { id: ActivityType.JUMBLED_WORD_STORY, title: 'Karışık Hikaye', description: 'Kelimeleri çözüp hikayeyi tamamlayın.', icon: 'fa-solid fa-book-open' },
    { id: ActivityType.HOMONYM_SENTENCE_WRITING, title: 'Eş Sesli Cümleler', description: 'Eş sesli kelimelerin farklı anlamlarıyla cümle kurun.', icon: 'fa-solid fa-pen-fancy' },
    { id: ActivityType.WORD_GRID_PUZZLE, title: 'Kelime Ağı', description: 'Kelimeleri birbirine bağlayarak yerleştirin.', icon: 'fa-solid fa-network-wired' },
    { id: ActivityType.PROVERB_SAYING_SORT, title: 'Atasözü/Özdeyiş', description: 'Sözleri türüne göre ayırın.', icon: 'fa-solid fa-quote-left' },
    { id: ActivityType.HOMONYM_IMAGE_MATCH, title: 'Eş Sesli Resim', description: 'Resimlerin anlattığı ortak kelimeyi bulun.', icon: 'fa-regular fa-images' },
    { id: ActivityType.ANTONYM_FLOWER_PUZZLE, title: 'Zıt Anlam Çiçeği', description: 'Zıt anlamlı kelimeleri çiçek yapraklarına yazın.', icon: 'fa-solid fa-fan' },
    { id: ActivityType.PROVERB_WORD_CHAIN, title: 'Atasözü Zinciri', description: 'Kelimeleri sıralayarak atasözünü oluşturun.', icon: 'fa-solid fa-link' },
    { id: ActivityType.THEMATIC_ODD_ONE_OUT, title: 'Tematik Farkı Bul', description: 'Konuyla ilgisiz kelimeyi bulun.', icon: 'fa-solid fa-list-ul' },
    { id: ActivityType.SYNONYM_ANTONYM_GRID, title: 'Eş/Zıt Tablosu', description: 'Tabloda eş ve zıt anlamlıları bulun.', icon: 'fa-solid fa-table' },
    { id: ActivityType.PUNCTUATION_COLORING, title: 'Noktalama Boyama', description: 'Noktalama işaretlerine göre boyama yapın.', icon: 'fa-solid fa-fill-drip' },
    { id: ActivityType.PUNCTUATION_MAZE, title: 'Noktalama Labirenti', description: 'Doğru noktalama kurallarını takip ederek çıkışı bulun.', icon: 'fa-solid fa-diamond-turn-right' },
    { id: ActivityType.ANTONYM_RESFEBE, title: 'Zıt Anlam Resfebe', description: 'Resfebeyi çözüp zıt anlamlısını bulun.', icon: 'fa-solid fa-eye' },
    { id: ActivityType.THEMATIC_WORD_SEARCH_COLOR, title: 'Renkli Kelime Avı', description: 'Tematik kelimeleri bulun.', icon: 'fa-solid fa-palette' },
    { id: ActivityType.THEMATIC_ODD_ONE_OUT_SENTENCE, title: 'Farklı Olanla Cümle', description: 'Farklı kelimeyi bulup cümle içinde kullanın.', icon: 'fa-solid fa-pen' },
    { id: ActivityType.SYNONYM_SEARCH_STORY, title: 'Eş Anlam Hikaye', description: 'Eş anlamlıları bulup hikayede kullanın.', icon: 'fa-solid fa-book-open-reader' },
    { id: ActivityType.COLUMN_ODD_ONE_OUT_SENTENCE, title: 'Sütunda Farklı Olan', description: 'Sütunlardaki farklı kelimeleri bulun.', icon: 'fa-solid fa-table-columns' },
    { id: ActivityType.SYNONYM_ANTONYM_COLORING, title: 'Eş/Zıt Boyama', description: 'Anlam ilişkisine göre boyama yapın.', icon: 'fa-solid fa-brush' },
    { id: ActivityType.PUNCTUATION_PHONE_NUMBER, title: 'Noktalama Telefonu', description: 'İpuçlarını çözerek gizli numarayı bulun.', icon: 'fa-solid fa-phone' },
    { id: ActivityType.PUNCTUATION_SPIRAL_PUZZLE, title: 'Noktalama Sarmalı', description: 'Sarmal bulmacayı çözün.', icon: 'fa-solid fa-hurricane' },
    { id: ActivityType.SYNONYM_MATCHING_PATTERN, title: 'Eş Anlam Deseni', description: 'Eş anlamlıları eşleştirerek desen oluşturun.', icon: 'fa-solid fa-draw-polygon' },
    { id: ActivityType.RESFEBE, title: 'Resfebe', description: 'Resim ve harflerden kelimeyi bulun.', icon: 'fa-solid fa-eye' },
    { id: ActivityType.WORD_WEB, title: 'Kelime Ağı', description: 'Kelimeleri ağ yapısında yerleştirin.', icon: 'fa-solid fa-circle-nodes' },
    { id: ActivityType.IMAGE_ANAGRAM_SORT, title: 'Resimli Anagram', description: 'Resme bakarak karışık harfleri düzenleyin.', icon: 'fa-solid fa-image' },
    { id: ActivityType.ANAGRAM_IMAGE_MATCH, title: 'Anagram Eşleme', description: 'Anagramı çözüp resimle eşleştirin.', icon: 'fa-solid fa-images' },
    { id: ActivityType.SYLLABLE_WORD_SEARCH, title: 'Hece Avı', description: 'Heceleri birleştirip kelimeyi bulun.', icon: 'fa-solid fa-magnifying-glass' },
    { id: ActivityType.WORD_SEARCH_WITH_PASSWORD, title: 'Şifreli Bulmaca', description: 'Kelimeleri bulup şifreyi çözün.', icon: 'fa-solid fa-lock-open' },
    { id: ActivityType.WORD_WEB_WITH_PASSWORD, title: 'Şifreli Ağ', description: 'Ağı tamamlayıp şifreyi bulun.', icon: 'fa-solid fa-globe' },
    { id: ActivityType.LETTER_GRID_WORD_FIND, title: 'Harf Tablosu', description: 'Harfler arasından kelimeler türetin.', icon: 'fa-solid fa-table' },
    { id: ActivityType.WORD_PLACEMENT_PUZZLE, title: 'Kelime Yerleştirme', description: 'Kelimeleri uzunluklarına göre yerleştirin.', icon: 'fa-solid fa-arrow-down-a-z' },
    { id: ActivityType.POSITIONAL_ANAGRAM, title: 'Konumlu Anagram', description: 'Harflerin yerini değiştirerek kelimeyi bulun.', icon: 'fa-solid fa-arrow-right-arrow-left' },
    { id: ActivityType.PROVERB_SENTENCE_FINDER, title: 'Cümle Bulmaca', description: 'Karışık kelimelerden cümle oluşturun.', icon: 'fa-solid fa-quote-right' },
    { id: ActivityType.PROVERB_FILL_IN_THE_BLANK, title: 'Atasözü Tamamlama', description: 'Eksik kelimeleri tamamlayın.', icon: 'fa-solid fa-pen' },
    { id: ActivityType.PROVERB_SEARCH, title: 'Atasözü Avı', description: 'Gizli atasözünü bulun.', icon: 'fa-solid fa-magnifying-glass' },

    // --- MATEMATİK VE MANTIK ---
    { id: ActivityType.MATH_PUZZLE, title: 'Matematik Bulmacası', description: 'Resimli matematik işlemlerini çözün.', icon: 'fa-solid fa-calculator' },
    { id: ActivityType.NUMBER_PATTERN, title: 'Sayı Örüntüsü', description: 'Sayı dizisindeki kuralı bulun.', icon: 'fa-solid fa-arrow-up-right-dots' },
    { id: ActivityType.FUTOSHIKI, title: 'Futoşiki', description: 'Büyüktür/Küçüktür mantığıyla tabloyu doldurun.', icon: 'fa-solid fa-less-than-equal' },
    { id: ActivityType.NUMBER_PYRAMID, title: 'Sayı Piramidi', description: 'Piramidi toplama işlemiyle tamamlayın.', icon: 'fa-solid fa-play' }, // Triangle shape
    { id: ActivityType.NUMBER_CAPSULE, title: 'Sayı Kapsülü', description: 'Sayıları kapsüllere mantıklı şekilde yerleştirin.', icon: 'fa-solid fa-capsules' },
    { id: ActivityType.ODD_EVEN_SUDOKU, title: 'Tek-Çift Sudoku', description: 'Tek ve çift sayı kurallı sudoku.', icon: 'fa-solid fa-border-all' },
    { id: ActivityType.ROMAN_NUMERAL_CONNECT, title: 'Romen Rakamı Bağla', description: 'Romen rakamlarını eşleştirin.', icon: 'fa-solid fa-i' },
    { id: ActivityType.ROMAN_NUMERAL_STAR_HUNT, title: 'Yıldız Avı (Romen)', description: 'Romen rakamlarıyla verilen ipuçlarını kullanın.', icon: 'fa-solid fa-star-half-stroke' },
    { id: ActivityType.ROUNDING_CONNECT, title: 'Yuvarlama Eşleşmesi', description: 'Sayıları en yakın onluğa yuvarlayarak eşleştirin.', icon: 'fa-solid fa-arrows-to-circle' },
    { id: ActivityType.ROMAN_NUMERAL_MULTIPLICATION, title: 'Romen Çarpımı', description: 'Romen rakamlarıyla çarpım tablosu.', icon: 'fa-solid fa-xmark' },
    { id: ActivityType.ARITHMETIC_CONNECT, title: 'İşlem Eşleştirme', description: 'Sonucu aynı olan işlemleri eşleştirin.', icon: 'fa-solid fa-equals' },
    { id: ActivityType.ROMAN_ARABIC_MATCH_CONNECT, title: 'Rakam Eşleştirme', description: 'Romen ve Arap rakamlarını eşleştirin.', icon: 'fa-solid fa-retweet' },
    { id: ActivityType.KENDOKU, title: 'Kendoku', description: 'İşlem gruplu mantık bulmacası.', icon: 'fa-solid fa-brain' },
    { id: ActivityType.OPERATION_SQUARE_FILL_IN, title: 'İşlem Karesi', description: 'Boşlukları uygun sayılarla doldurun.', icon: 'fa-solid fa-square-root-variable' },
    { id: ActivityType.MULTIPLICATION_WHEEL, title: 'Çarpım Çarkı', description: 'Merkezdeki sayıyla çarparak çarkı doldurun.', icon: 'fa-solid fa-dharmachakra' },
    { id: ActivityType.TARGET_NUMBER, title: 'Hedef Sayı', description: 'Verilen sayılarla hedef sayıya ulaşın.', icon: 'fa-solid fa-bullseye' },
    { id: ActivityType.SHAPE_SUDOKU, title: 'Şekilli Sudoku', description: 'Sayılar yerine şekillerle sudoku çözün.', icon: 'fa-solid fa-shapes' },
    { id: ActivityType.WEIGHT_CONNECT, title: 'Ağırlık Eşleştirme', description: 'Eşit ağırlıkları birleştirin.', icon: 'fa-solid fa-weight-hanging' },
    { id: ActivityType.LENGTH_CONNECT, title: 'Uzunluk Eşleştirme', description: 'Eşit uzunlukları birleştirin.', icon: 'fa-solid fa-ruler-horizontal' },
    { id: ActivityType.VISUAL_NUMBER_PATTERN, title: 'Görsel Örüntü', description: 'Şekil ve renk örüntülerini devam ettirin.', icon: 'fa-solid fa-palette' },
    { id: ActivityType.LOGIC_GRID_PUZZLE, title: 'Mantık Tablosu', description: 'İpuçlarını kullanarak tabloyu çözün.', icon: 'fa-solid fa-table-list' },
    { id: ActivityType.ODD_ONE_OUT, title: 'Farklı Olanı Bul', description: 'Grupta uyumsuz olanı bulun.', icon: 'fa-solid fa-circle-xmark' },
    { id: ActivityType.SHAPE_NUMBER_PATTERN, title: 'Şekilli Sayı İlişkisi', description: 'Şekiller ve sayılar arasındaki kuralı bulun.', icon: 'fa-solid fa-draw-polygon' },
    { id: ActivityType.BASIC_OPERATIONS, title: 'Dört İşlem', description: 'Temel matematik işlemleri.', icon: 'fa-solid fa-plus-minus' },
    { id: ActivityType.REAL_LIFE_MATH_PROBLEMS, title: 'Hayat Problemleri', description: 'Günlük hayattan matematik problemleri.', icon: 'fa-solid fa-basket-shopping' },
    { id: ActivityType.FAMILY_RELATIONS, title: 'Akrabalık İlişkileri', description: 'Akrabalık terimlerini ve ilişkilerini eşleştirin.', icon: 'fa-solid fa-people-roof' },
    { id: ActivityType.LOGIC_DEDUCTION, title: 'Mantıksal Çıkarım', description: 'İpuçlarından yola çıkarak doğru cevabı bulun.', icon: 'fa-solid fa-lightbulb' },
    { id: ActivityType.NUMBER_BOX_LOGIC, title: 'Kutu Mantığı', description: 'Kutulardaki sayıları analiz edin.', icon: 'fa-solid fa-box-open' },
    { id: ActivityType.MAP_INSTRUCTION, title: 'Harita Yönergesi', description: 'Yönergeleri takip ederek haritada yer bulun.', icon: 'fa-solid fa-map-location-dot' },
    { 
        id: ActivityType.MIND_GAMES, 
        title: 'Akıl Oyunları (3-4. Sınıf)', 
        description: 'Matrisler, işlem piramitleri, fonksiyon makineleri ve şekil bağıntıları.', 
        icon: 'fa-solid fa-puzzle-piece' 
    },
    { 
        id: ActivityType.MIND_GAMES_56, 
        title: 'Akıl Oyunları (5-6. Sınıf)', 
        description: 'Mantık, matematik ve sözel akıl yürütme problemleri.', 
        icon: 'fa-solid fa-brain' 
    },

    // --- DİKKAT VE HAFIZA ---
    { id: ActivityType.STROOP_TEST, title: 'Stroop Testi', description: 'Kelimeyi değil, rengi söyleyin.', icon: 'fa-solid fa-brush' },
    { id: ActivityType.LETTER_GRID_TEST, title: 'Harf Izgarası', description: 'Karışık harfler arasında hedefi bulun.', icon: 'fa-solid fa-table-cells' },
    { id: ActivityType.NUMBER_SEARCH, title: 'Sayı Avı', description: 'Karışık sayılar arasında hedefi bulun.', icon: 'fa-solid fa-magnifying-glass' },
    { id: ActivityType.WORD_MEMORY, title: 'Kelime Hafıza', description: 'Kelimeleri akılda tutun ve hatırlayın.', icon: 'fa-solid fa-memory' },
    { id: ActivityType.VISUAL_MEMORY, title: 'Görsel Hafıza', description: 'Görselleri akılda tutun ve hatırlayın.', icon: 'fa-regular fa-image' },
    { id: ActivityType.FIND_THE_DUPLICATE_IN_ROW, title: 'İkiliyi Bul', description: 'Satırdaki tekrar eden öğeyi bulun.', icon: 'fa-solid fa-clone' },
    { id: ActivityType.FIND_LETTER_PAIR, title: 'Harf İkilisi', description: 'Belirli harf çiftlerini bulun.', icon: 'fa-solid fa-font' },
    { id: ActivityType.TARGET_SEARCH, title: 'Hedef Avı', description: 'Belirlenen hedefi bulun.', icon: 'fa-solid fa-crosshairs' },
    { id: ActivityType.COLOR_WHEEL_MEMORY, title: 'Renk Çemberi', description: 'Renklerin sırasını hatırlayın.', icon: 'fa-solid fa-circle-notch' },
    { id: ActivityType.IMAGE_COMPREHENSION, title: 'Resim Anlama', description: 'Resimdeki detayları hatırlayın.', icon: 'fa-solid fa-image' },
    { id: ActivityType.CHARACTER_MEMORY, title: 'Karakter Hafıza', description: 'Karakter özelliklerini hatırlayın.', icon: 'fa-solid fa-user-tag' },
    { id: ActivityType.CHAOTIC_NUMBER_SEARCH, title: 'Kaotik Sayı Avı', description: 'Dağınık sayılar arasında hedefi bulun.', icon: 'fa-solid fa-arrow-pointer' },
    { id: ActivityType.BURDON_TEST, title: 'Burdon Dikkat Testi', description: 'Dikkat ve odaklanma testi.', icon: 'fa-solid fa-list-check' },

    // --- OKUMA ANLAMA ---
    { id: ActivityType.STORY_COMPREHENSION, title: 'Okuduğunu Anlama', description: 'Hikayeyi okuyup soruları cevaplayın.', icon: 'fa-solid fa-book-reader' },
    { id: ActivityType.STORY_CREATION_PROMPT, title: 'Hikaye Yazma', description: 'Verilen kelimelerle hikaye oluşturun.', icon: 'fa-solid fa-pen-nib' },
    { id: ActivityType.WORDS_IN_STORY, title: 'Metin Analizi', description: 'Metin içindeki kelimeleri analiz edin.', icon: 'fa-solid fa-file-word' },
    { id: ActivityType.STORY_ANALYSIS, title: 'Hikaye Analizi', description: 'Hikayenin unsurlarını inceleyin.', icon: 'fa-solid fa-microscope' },
    { id: ActivityType.STORY_SEQUENCING, title: 'Olay Sıralama', description: 'Olayları oluş sırasına göre dizin.', icon: 'fa-solid fa-arrow-down-1-9' },
    { id: ActivityType.MISSING_PARTS, title: 'Eksik Parça', description: 'Hikaye veya kelimedeki eksik parçayı tamamlayın.', icon: 'fa-solid fa-puzzle-piece' },

    // --- ÖZEL ÖĞRENME DESTEĞİ ---
    { id: ActivityType.READING_FLOW, title: 'Okuma Akışı', description: 'Renkli hecelerle okuma kolaylığı.', icon: 'fa-solid fa-water' },
    { id: ActivityType.LETTER_DISCRIMINATION, title: 'Harf Ayırt Etme', description: 'Karıştırılan harfleri ayırt etme egzersizi.', icon: 'fa-solid fa-font' },
    { id: ActivityType.RAPID_NAMING, title: 'Hızlı İsimlendirme', description: 'Otomatikleşmiş isimlendirme hızı çalışması.', icon: 'fa-solid fa-stopwatch' },
    { id: ActivityType.PHONOLOGICAL_AWARENESS, title: 'Fonolojik Farkındalık', description: 'Ses ve hece farkındalığı çalışmaları.', icon: 'fa-solid fa-ear-listen' },
    { id: ActivityType.MIRROR_LETTERS, title: 'Ayna Harfler', description: 'Ters (ayna) harfleri düzeltme.', icon: 'fa-solid fa-arrow-right-arrow-left' },
    { id: ActivityType.SYLLABLE_TRAIN, title: 'Hece Treni', description: 'Kelimeleri hecelerine ayırma.', icon: 'fa-solid fa-train' },
    { id: ActivityType.VISUAL_TRACKING_LINES, title: 'Gözle Takip', description: 'Çizgileri gözle takip etme egzersizi.', icon: 'fa-solid fa-route' },
    { id: ActivityType.BACKWARD_SPELLING, title: 'Ters Harf', description: 'Tersten yazılmış kelimeleri okuma.', icon: 'fa-solid fa-rotate' },
    { id: ActivityType.CODE_READING, title: 'Kod Okuma', description: 'Sembolleri harfe çevirme.', icon: 'fa-solid fa-code' },
    { id: ActivityType.ATTENTION_TO_QUESTION, title: 'Soruya Dikkat', description: 'Detaylı görsel dikkat ve yönerge takibi.', icon: 'fa-solid fa-circle-question' },
    { id: ActivityType.ATTENTION_DEVELOPMENT, title: 'Dikkat Geliştirme', description: 'Mantıksal çıkarım ve dikkat.', icon: 'fa-solid fa-brain' },
    { id: ActivityType.ATTENTION_FOCUS, title: 'Dikkatini Ver', description: 'İpuçlarını takip ederek doğru nesneyi bul.', icon: 'fa-solid fa-eye' },

    // --- DİSKALKULİ ---
    { id: ActivityType.NUMBER_SENSE, title: 'Sayı Hissi', description: 'Miktar ve sayı kavramı çalışmaları.', icon: 'fa-solid fa-1' },
    { id: ActivityType.ARITHMETIC_FLUENCY, title: 'İşlem Akıcılığı', description: 'Temel işlemlerde hız kazanma.', icon: 'fa-solid fa-plus' },
    { id: ActivityType.NUMBER_GROUPING, title: 'Sayı Gruplama', description: 'Nesneleri gruplandırarak sayma.', icon: 'fa-solid fa-layer-group' },
    { id: ActivityType.PROBLEM_SOLVING_STRATEGIES, title: 'Problem Çözme', description: 'Adım adım problem çözme stratejileri.', icon: 'fa-solid fa-list-ol' },
    { id: ActivityType.MATH_LANGUAGE, title: 'Matematik Dili', description: 'Matematiksel terim ve semboller.', icon: 'fa-solid fa-language' },
    { id: ActivityType.TIME_MEASUREMENT_GEOMETRY, title: 'Zaman ve Ölçme', description: 'Saat, para ve ölçü birimleri.', icon: 'fa-solid fa-ruler' },
    { id: ActivityType.SPATIAL_REASONING, title: 'Uzamsal Algı', description: '3 boyutlu düşünme ve konumlandırma.', icon: 'fa-solid fa-cube' },
    { id: ActivityType.ESTIMATION_SKILLS, title: 'Tahmin Becerisi', description: 'Miktar tahmin etme çalışmaları.', icon: 'fa-solid fa-scale-balanced' },
    { id: ActivityType.FRACTIONS_DECIMALS, title: 'Kesirler', description: 'Kesir ve ondalık kavramları.', icon: 'fa-solid fa-chart-pie' },
    { id: ActivityType.VISUAL_NUMBER_REPRESENTATION, title: 'Görsel Sayılar', description: 'Sayıları görsel modellerle eşleştirme.', icon: 'fa-solid fa-dice' },
    { id: ActivityType.VISUAL_ARITHMETIC, title: 'Görsel Aritmetik', description: 'Resimlerle toplama ve çıkarma.', icon: 'fa-solid fa-calculator' },
    { id: ActivityType.APPLIED_MATH_STORY, title: 'Matematik Hikayesi', description: 'Hikaye içinde matematik problemleri.', icon: 'fa-solid fa-book' },
    { id: ActivityType.SPATIAL_AWARENESS_DISCOVERY, title: 'Mekansal Keşif', description: 'Yön ve konum bulma.', icon: 'fa-solid fa-compass' },
    { id: ActivityType.POSITIONAL_CONCEPTS, title: 'Konum Kavramları', description: 'Altında, üstünde, sağında, solunda.', icon: 'fa-solid fa-arrows-up-down-left-right' },
    { id: ActivityType.DIRECTIONAL_CONCEPTS, title: 'Yön Kavramları', description: 'Yönleri ayırt etme.', icon: 'fa-solid fa-arrow-trend-up' },
    { id: ActivityType.VISUAL_DISCRIMINATION_MATH, title: 'Matematiksel Ayrım', description: 'Benzer şekil ve sayılar arasındaki farkı bulma.', icon: 'fa-solid fa-magnifying-glass' }
];

export const ACTIVITY_CATEGORIES: ActivityCategory[] = [
    {
        id: 'visual-perception',
        title: 'Görsel Algı',
        description: 'Görsel ayrıştırma, şekil-zemin ilişkisi ve görsel hafıza becerilerini geliştiren etkinlikler.',
        icon: 'fa-solid fa-eye',
        activities: [
            ActivityType.FIND_THE_DIFFERENCE, ActivityType.WORD_COMPARISON, ActivityType.SHAPE_MATCHING, 
            ActivityType.FIND_IDENTICAL_WORD, ActivityType.GRID_DRAWING, ActivityType.SYMBOL_CIPHER, 
            ActivityType.BLOCK_PAINTING, ActivityType.VISUAL_ODD_ONE_OUT, ActivityType.SYMMETRY_DRAWING, 
            ActivityType.FIND_DIFFERENT_STRING, ActivityType.DOT_PAINTING, ActivityType.ABC_CONNECT, 
            ActivityType.WORD_CONNECT, ActivityType.COORDINATE_CIPHER, ActivityType.PROFESSION_CONNECT, 
            ActivityType.MATCHSTICK_SYMMETRY, ActivityType.VISUAL_ODD_ONE_OUT_THEMED, ActivityType.STAR_HUNT, 
            ActivityType.SHAPE_COUNTING
        ]
    },
    {
        id: 'reading-verbal',
        title: 'Okuma ve Sözel',
        description: 'Kelime dağarcığı, fonolojik farkındalık ve dil becerilerini destekleyen etkinlikler.',
        icon: 'fa-solid fa-book-open',
        activities: [
            ActivityType.WORD_SEARCH, ActivityType.ANAGRAM, ActivityType.SPELLING_CHECK, 
            ActivityType.LETTER_BRIDGE, ActivityType.WORD_LADDER, ActivityType.WORD_FORMATION, 
            ActivityType.REVERSE_WORD, ActivityType.WORD_GROUPING, ActivityType.MINI_WORD_GRID, 
            ActivityType.PASSWORD_FINDER, ActivityType.SYLLABLE_COMPLETION, ActivityType.SYNONYM_WORD_SEARCH, 
            ActivityType.SPIRAL_PUZZLE, ActivityType.CROSSWORD, ActivityType.JUMBLED_WORD_STORY, 
            ActivityType.HOMONYM_SENTENCE_WRITING, ActivityType.WORD_GRID_PUZZLE, ActivityType.PROVERB_SAYING_SORT, 
            ActivityType.HOMONYM_IMAGE_MATCH, ActivityType.ANTONYM_FLOWER_PUZZLE, ActivityType.PROVERB_WORD_CHAIN, 
            ActivityType.THEMATIC_ODD_ONE_OUT, ActivityType.SYNONYM_ANTONYM_GRID, ActivityType.PUNCTUATION_COLORING, 
            ActivityType.PUNCTUATION_MAZE, ActivityType.ANTONYM_RESFEBE, ActivityType.THEMATIC_WORD_SEARCH_COLOR, 
            ActivityType.THEMATIC_ODD_ONE_OUT_SENTENCE, ActivityType.SYNONYM_SEARCH_STORY, 
            ActivityType.COLUMN_ODD_ONE_OUT_SENTENCE, ActivityType.SYNONYM_ANTONYM_COLORING, 
            ActivityType.PUNCTUATION_PHONE_NUMBER, ActivityType.PUNCTUATION_SPIRAL_PUZZLE, 
            ActivityType.SYNONYM_MATCHING_PATTERN, ActivityType.RESFEBE, ActivityType.WORD_WEB, 
            ActivityType.IMAGE_ANAGRAM_SORT, ActivityType.ANAGRAM_IMAGE_MATCH, ActivityType.SYLLABLE_WORD_SEARCH, 
            ActivityType.WORD_SEARCH_WITH_PASSWORD, ActivityType.WORD_WEB_WITH_PASSWORD, 
            ActivityType.LETTER_GRID_WORD_FIND, ActivityType.WORD_PLACEMENT_PUZZLE, ActivityType.POSITIONAL_ANAGRAM, 
            ActivityType.PROVERB_SENTENCE_FINDER, ActivityType.PROVERB_FILL_IN_THE_BLANK, ActivityType.PROVERB_SEARCH
        ]
    },
    {
        id: 'math-logic',
        title: 'Matematik ve Mantık',
        description: 'Sayısal düşünme, problem çözme ve mantıksal akıl yürütme becerilerini geliştiren etkinlikler.',
        icon: 'fa-solid fa-calculator',
        activities: [
            ActivityType.MATH_PUZZLE, ActivityType.NUMBER_PATTERN, ActivityType.FUTOSHIKI, 
            ActivityType.NUMBER_PYRAMID, ActivityType.NUMBER_CAPSULE, ActivityType.ODD_EVEN_SUDOKU, 
            ActivityType.ROMAN_NUMERAL_CONNECT, ActivityType.ROMAN_NUMERAL_STAR_HUNT, 
            ActivityType.ROUNDING_CONNECT, ActivityType.ROMAN_NUMERAL_MULTIPLICATION, 
            ActivityType.ARITHMETIC_CONNECT, ActivityType.ROMAN_ARABIC_MATCH_CONNECT, ActivityType.KENDOKU, 
            ActivityType.OPERATION_SQUARE_FILL_IN, ActivityType.MULTIPLICATION_WHEEL, ActivityType.TARGET_NUMBER, 
            ActivityType.SHAPE_SUDOKU, ActivityType.WEIGHT_CONNECT, ActivityType.LENGTH_CONNECT, 
            ActivityType.VISUAL_NUMBER_PATTERN, ActivityType.LOGIC_GRID_PUZZLE, ActivityType.ODD_ONE_OUT, 
            ActivityType.SHAPE_NUMBER_PATTERN, ActivityType.BASIC_OPERATIONS, ActivityType.REAL_LIFE_MATH_PROBLEMS, 
            ActivityType.FAMILY_RELATIONS, ActivityType.LOGIC_DEDUCTION, ActivityType.NUMBER_BOX_LOGIC, 
            ActivityType.MAP_INSTRUCTION, ActivityType.MIND_GAMES, ActivityType.MIND_GAMES_56
        ]
    },
    {
        id: 'attention-memory',
        title: 'Dikkat ve Hafıza',
        description: 'Odaklanma, sürdürülebilir dikkat ve hafıza kapasitesini artıran etkinlikler.',
        icon: 'fa-solid fa-brain',
        activities: [
            ActivityType.STROOP_TEST, ActivityType.LETTER_GRID_TEST, ActivityType.NUMBER_SEARCH, 
            ActivityType.WORD_MEMORY, ActivityType.VISUAL_MEMORY, ActivityType.FIND_THE_DUPLICATE_IN_ROW, 
            ActivityType.FIND_LETTER_PAIR, ActivityType.TARGET_SEARCH, ActivityType.COLOR_WHEEL_MEMORY, 
            ActivityType.IMAGE_COMPREHENSION, ActivityType.CHARACTER_MEMORY, ActivityType.CHAOTIC_NUMBER_SEARCH, 
            ActivityType.BURDON_TEST
        ]
    },
    {
        id: 'reading-comprehension',
        title: 'Okuma Anlama',
        description: 'Metin analizi, ana fikir bulma ve çıkarım yapma becerilerini geliştiren etkinlikler.',
        icon: 'fa-solid fa-book-reader',
        activities: [
            ActivityType.STORY_COMPREHENSION, ActivityType.STORY_CREATION_PROMPT, ActivityType.WORDS_IN_STORY, 
            ActivityType.STORY_ANALYSIS, ActivityType.STORY_SEQUENCING, ActivityType.MISSING_PARTS
        ]
    },
    {
        id: 'dyslexia-support',
        title: 'Özel Öğrenme Desteği',
        description: 'Disleksi ve öğrenme güçlüğü yaşayan bireyler için özel olarak tasarlanmış destekleyici etkinlikler.',
        icon: 'fa-solid fa-hands-holding-circle',
        activities: [
            ActivityType.READING_FLOW, ActivityType.LETTER_DISCRIMINATION, ActivityType.RAPID_NAMING, 
            ActivityType.PHONOLOGICAL_AWARENESS, ActivityType.MIRROR_LETTERS, ActivityType.SYLLABLE_TRAIN, 
            ActivityType.VISUAL_TRACKING_LINES, ActivityType.BACKWARD_SPELLING, ActivityType.CODE_READING, 
            ActivityType.ATTENTION_TO_QUESTION, ActivityType.ATTENTION_DEVELOPMENT, ActivityType.ATTENTION_FOCUS
        ]
    },
    {
        id: 'dyscalculia',
        title: 'Diskalkuli Desteği',
        description: 'Matematik öğrenme güçlüğü yaşayanlar için sayı hissi ve işlem becerilerini destekleyen etkinlikler.',
        icon: 'fa-solid fa-arrow-up-1-9',
        activities: [
            ActivityType.NUMBER_SENSE, ActivityType.ARITHMETIC_FLUENCY, ActivityType.NUMBER_GROUPING, 
            ActivityType.PROBLEM_SOLVING_STRATEGIES, ActivityType.MATH_LANGUAGE, 
            ActivityType.TIME_MEASUREMENT_GEOMETRY, ActivityType.SPATIAL_REASONING, 
            ActivityType.ESTIMATION_SKILLS, ActivityType.FRACTIONS_DECIMALS, 
            ActivityType.VISUAL_NUMBER_REPRESENTATION, ActivityType.VISUAL_ARITHMETIC, 
            ActivityType.APPLIED_MATH_STORY, ActivityType.SPATIAL_AWARENESS_DISCOVERY, 
            ActivityType.POSITIONAL_CONCEPTS, ActivityType.DIRECTIONAL_CONCEPTS, 
            ActivityType.VISUAL_DISCRIMINATION_MATH
        ]
    }
];