import { Activity, ActivityType, ActivityCategory } from './types';

export const ACTIVITIES: Activity[] = [
  {
    id: ActivityType.WORD_SEARCH,
    title: 'Kelime Bulmaca',
    description: 'Verilen kelimeleri harf tablosunda bulun.',
    icon: 'fa-solid fa-search',
  },
  {
    id: ActivityType.ANAGRAM,
    title: 'Anagram',
    description: 'Karışık harflerden anlamlı kelimeler oluşturun.',
    icon: 'fa-solid fa-shuffle',
  },
  {
    id: ActivityType.ANAGRAM,
    title: 'Anagram (Liste)',
    description: 'Verilen kelimelerin anagramlarını bulun.',
    icon: 'fa-solid fa-list-ol',
  },
   {
    id: ActivityType.FIND_THE_DIFFERENCE,
    title: 'Farklı Olanı Bul (Görsel)',
    description: 'Gruplar içinde farklı olan kelimeyi bulun.',
    icon: 'fa-solid fa-not-equal',
  },
  {
    id: ActivityType.MATH_PUZZLE,
    title: 'Matematik Bulmacası',
    description: 'Nesnelerle gizlenmiş sayıları bularak denklemleri çözün.',
    icon: 'fa-solid fa-calculator',
  },
  {
    id: ActivityType.STORY_COMPREHENSION,
    title: 'Hikaye Anlama',
    description: 'Kısa bir hikaye okuyun ve ilgili soruları yanıtlayın.',
    icon: 'fa-solid fa-book-open',
  },
   {
    id: ActivityType.STORY_COMPREHENSION,
    title: 'Hikayeye Dikkat - 1',
    description: 'Yeni bir hikaye okuyun ve ilgili soruları yanıtlayın.',
    icon: 'fa-solid fa-book-bookmark',
  },
   {
    id: ActivityType.STORY_COMPREHENSION,
    title: 'Hikayeye Dikkat - 2',
    description: 'Yeni bir hikaye okuyun ve ilgili soruları yanıtlayın.',
    icon: 'fa-solid fa-book-open-reader',
  },
  {
    id: ActivityType.WORD_COMPARISON,
    title: 'Kelime Karşılaştırma',
    description: 'İki kelime listesini karşılaştırıp farklı olanları bulun.',
    icon: 'fa-solid fa-code-compare',
  },
  {
    id: ActivityType.WORDS_IN_STORY,
    title: 'Metindeki Kelimeler',
    description: 'Metinde geçen ve geçmeyen kelimeleri listeden bulun.',
    icon: 'fa-solid fa-book-reader',
  },
  {
    id: ActivityType.STROOP_TEST,
    title: 'Stroop Testi (Renk Oku)',
    description: 'Kelimeyi değil, kelimenin yazıldığı rengi söyleyin.',
    icon: 'fa-solid fa-palette',
  },
  {
    id: ActivityType.NUMBER_PATTERN,
    title: 'Sayı Örüntüsü Bulma',
    description: 'Sayı dizisindeki kuralı bulup eksik sayıyı tamamlayın.',
    icon: 'fa-solid fa-arrow-trend-up',
  },
  {
    id: ActivityType.SPELLING_CHECK,
    title: 'Doğru Yazılışı Bulma',
    description: 'Verilen kelimeler arasından doğru yazılanı seçin.',
    icon: 'fa-solid fa-spell-check',
  },
  {
    id: ActivityType.LETTER_GRID_TEST,
    title: 'Harf Izgara Testi',
    description: 'Harf yığını içinden istenen harfleri bulun ve işaretleyin.',
    icon: 'fa-solid fa-border-all',
  },
  {
    id: ActivityType.NUMBER_SEARCH,
    title: 'Sayı Avı',
    description: 'Karışık sayılar arasından belirli bir sırayı takip edin.',
    icon: 'fa-solid fa-arrow-down-1-9',
  },
  {
    id: ActivityType.WORD_MEMORY,
    title: 'Süper Hafıza (Kelime)',
    description: 'Kelimeleri ezberleyin ve sonraki sayfada hatırlayın.',
    icon: 'fa-solid fa-brain',
  },
  {
    id: ActivityType.STORY_CREATION_PROMPT,
    title: 'Hikaye Oluşturma',
    description: 'Verilen anahtar kelimeleri kullanarak bir hikaye yazın.',
    icon: 'fa-solid fa-pencil-alt',
  },
  {
    id: ActivityType.ODD_ONE_OUT,
    title: 'Farkı Fark Et (Anlamsal)',
    description: 'Kelime gruplarında anlamsal olarak farklı olanı bulun.',
    icon: 'fa-solid fa-lightbulb-question',
  },
  {
    id: ActivityType.SHAPE_MATCHING,
    title: 'Şekil Eşleştirme',
    description: 'Aynı şekil dizilerini bulun ve eşleştirin.',
    icon: 'fa-solid fa-shapes',
  },
  {
    id: ActivityType.SYMBOL_CIPHER,
    title: 'Şifre Çözme',
    description: 'Şekillerle kodlanmış kelimeleri anahtara bakarak çözün.',
    icon: 'fa-solid fa-key',
  },
  {
    id: ActivityType.PROVERB_FILL_IN_THE_BLANK,
    title: 'Atasözü Avı',
    description: 'Atasözlerindeki eksik kelimeleri bulun ve tamamlayın.',
    icon: 'fa-solid fa-quote-left',
  },
  {
    id: ActivityType.LETTER_BRIDGE,
    title: 'Harf Köprüsü',
    description: 'İki kelime arasına bir harf yerleştirerek yeni kelimeler oluşturun.',
    icon: 'fa-solid fa-bridge',
  },
  {
    id: ActivityType.FIND_THE_DUPLICATE_IN_ROW,
    title: 'İkiliyi Bul',
    description: 'Her satırda tekrar eden harfi veya rakamı bulun.',
    icon: 'fa-solid fa-clone',
  },
  {
    id: ActivityType.WORD_LADDER,
    title: 'Kelime Merdiveni',
    description: 'Her adımda tek harf değiştirerek bir kelimeden diğerine ulaşın.',
    icon: 'fa-solid fa-stairs',
  },
  {
    id: ActivityType.FIND_IDENTICAL_WORD,
    title: 'Aynısını Bul',
    description: 'Birbirine çok benzeyen kelimelerden aynı olan çifti bulun.',
    icon: 'fa-solid fa-equals',
  },
  {
    id: ActivityType.WORD_FORMATION,
    title: 'Harflerden Kelime Türetme',
    description: 'Verilen harfleri kullanarak anlamlı kelimeler oluşturun.',
    icon: 'fa-solid fa-puzzle-piece',
  },
  {
    id: ActivityType.REVERSE_WORD,
    title: 'Ters Oku - Ters Uko',
    description: 'Verilen kelimeleri tersten yazma alıştırması yapın.',
    icon: 'fa-solid fa-right-left-rotate',
  },
  {
    id: ActivityType.FIND_LETTER_PAIR,
    title: 'Harf İkilisini Bul',
    description: 'Harf tablosunda istenen harf ikilisini bulun.',
    icon: 'fa-solid fa-magnifying-glass-plus',
  },
  {
    id: ActivityType.WORD_GROUPING,
    title: 'Gruplama',
    description: 'Kelimeleri doğru kategorilere ayırın.',
    icon: 'fa-solid fa-folder-tree',
  },
  {
    id: ActivityType.VISUAL_MEMORY,
    title: 'Süper Hafıza (Görsel)',
    description: 'Görselleri aklınızda tutup sonraki sayfada bulun.',
    icon: 'fa-solid fa-images',
  },
   {
    id: ActivityType.CHARACTER_MEMORY,
    title: 'Dikkat - Hafıza',
    description: 'Karakterleri aklınızda tutup sonraki sayfada bulun.',
    icon: 'fa-solid fa-users-viewfinder',
  },
  {
    id: ActivityType.STORY_ANALYSIS,
    title: 'Hikaye Analizi',
    description: 'Hikayedeki eş/zıt anlamlı kelimeleri ve detayları bulun.',
    icon: 'fa-solid fa-magnifying-glass-chart',
  },
  {
    id: ActivityType.COORDINATE_CIPHER,
    title: 'Gizemli Bulmaca',
    description: 'Koordinatları verilen harfleri birleştirip şifreyi çözün.',
    icon: 'fa-solid fa-map-location-dot',
  },
  {
    id: ActivityType.PROVERB_SEARCH,
    title: 'Atasözü Avı',
    description: 'Harf tablosunda gizlenmiş atasözünü bulun.',
    icon: 'fa-solid fa-comment-dots',
  },
  {
    id: ActivityType.TARGET_SEARCH,
    title: 'Dikkatli Göz',
    description: 'Karakter yığını içinde hedef karakteri bulun.',
    icon: 'fa-solid fa-crosshairs',
  },
  {
    id: ActivityType.SHAPE_NUMBER_PATTERN,
    title: 'Şekilli Sayı Örüntüsü',
    description: 'Şekillerdeki sayılar arasındaki kuralı bulup eksik sayıyı tamamlayın.',
    icon: 'fa-solid fa-draw-polygon',
  },
  {
    id: ActivityType.GRID_DRAWING,
    title: 'Ayna Çizimi',
    description: 'Soldaki deseni sağdaki boş alana kopyalayın.',
    icon: 'fa-solid fa-vector-square',
  },
  {
    id: ActivityType.COLOR_WHEEL_MEMORY,
    title: 'Renk Çemberi',
    description: 'Renk çarkındaki nesneleri ezberleyip doğru yerleştirin.',
    icon: 'fa-solid fa-bullseye',
  },
  {
    id: ActivityType.IMAGE_COMPREHENSION,
    title: 'Resme Dikkat',
    description: 'Resmi inceleyip detaylarla ilgili soruları yanıtlayın.',
    icon: 'fa-solid fa-image',
  },
  {
    id: ActivityType.CHARACTER_MEMORY,
    title: 'Hafızanda Tut (Karakter)',
    description: 'Karakterleri aklınızda tutup sonraki sayfada hatırlayın.',
    icon: 'fa-solid fa-user-friends',
  },
  {
    id: ActivityType.STORY_SEQUENCING,
    title: 'Hikaye Oluşturma (Sıralama)',
    description: 'Karışık resimleri sıralayarak anlamlı bir hikaye oluşturun.',
    icon: 'fa-solid fa-film',
  },
  {
    id: ActivityType.CHAOTIC_NUMBER_SEARCH,
    title: 'Sayıları Bulma',
    description: 'Karışık sayılar arasından 1\'den 50\'ye kadar olanları boyayın.',
    icon: 'fa-solid fa-search-plus',
  },
  {
    id: ActivityType.BLOCK_PAINTING,
    title: 'Blok Boyama',
    description: 'Verilen blokları kullanarak deseni doğru renklere boyayın.',
    icon: 'fa-solid fa-puzzle-piece',
  },
  {
    id: ActivityType.MINI_WORD_GRID,
    title: 'Kelime Bulmaca (Mini)',
    description: 'Küçük tablolarda renkli harften başlayan kelimeleri bulun.',
    icon: 'fa-solid fa-table-cells',
  },
  {
    id: ActivityType.VISUAL_ODD_ONE_OUT,
    title: 'Sözcük Avı (Farklı Şekil)',
    description: 'Her satırda diğerlerinden farklı olan şekli bulun.',
    icon: 'fa-solid fa-circle-nodes',
  },
  {
    id: ActivityType.SHAPE_COUNTING,
    title: 'Kaç Tane Üçgen Var?',
    description: 'Karmaşık şekillerin içine gizlenmiş üçgenleri sayın.',
    icon: 'fa-solid fa-calculator-simple',
  },
  {
    id: ActivityType.SYMMETRY_DRAWING,
    title: 'Noktalarla Dans (Simetri)',
    description: 'Verilen desenin simetri eksenine göre yansımasını çizin.',
    icon: 'fa-solid fa-reflect-horizontal',
  },
  {
    id: ActivityType.BURDON_TEST,
    title: 'Burdon Dikkat Testi',
    description: 'Aşağıdaki satırlarda “a, b, d, g” harflerini bulup yuvarlak içine alalım.',
    icon: 'fa-solid fa-tasks',
  },
  {
    id: ActivityType.FIND_DIFFERENT_STRING,
    title: 'Farklı Olanı Bulma',
    description: 'Aşağıdaki sütunlarda yer alan harf sıralamasında VWN’den farklı olan harf grubunu işaretleyelim.',
    icon: 'fa-solid fa-not-equal',
  },
  {
    id: ActivityType.DOT_PAINTING,
    title: 'Nokta Boyama',
    description: 'Noktaların bulunduğu alanları boyayarak gizli şekli ortaya çıkaralım.',
    icon: 'fa-solid fa-paint-brush',
  },
  {
    id: ActivityType.ABC_CONNECT,
    title: 'ABC Bağlama',
    description: 'Örnekteki gibi aynı harflerle belirtilen noktaları birbirleriyle kesişmeyecek şekilde yatay ve dikey çizgilerle birleştirelim.',
    icon: 'fa-solid fa-draw-polygon',
  },
  {
    id: ActivityType.PASSWORD_FINDER,
    title: 'Şifre Bul',
    description: 'Baş harfi büyük yazılması gereken kelimeleri bulup şifreyi çözün.',
    icon: 'fa-solid fa-user-secret',
  },
  {
    id: ActivityType.SYLLABLE_COMPLETION,
    title: 'Eksik Kelimeler',
    description: 'Eksik heceleri bularak kelimeleri tamamlayın ve hikaye yazın.',
    icon: 'fa-solid fa-puzzle-piece',
  },
  {
    id: ActivityType.SYNONYM_WORD_SEARCH,
    title: 'Eş Anlamlı Kelime Avı',
    description: 'Kelimelerin eş anlamlılarını bulup bulmacada arayın.',
    icon: 'fa-solid fa-file-word',
  },
  {
    id: ActivityType.WORD_CONNECT,
    title: 'Kelime Bağlama',
    description: 'Anlamca ilişkili kelimeleri çizgilerle birleştirin.',
    icon: 'fa-solid fa-link',
  },
  {
    id: ActivityType.SPIRAL_PUZZLE,
    title: 'Sarmal Bulmaca',
    description: 'İpuçlarından kelimeleri bulup sarmal bulmacaya yerleştirin.',
    icon: 'fa-solid fa-hurricane',
  },
  {
    id: ActivityType.CROSSWORD,
    title: 'Çapraz Bulmaca',
    description: 'Verilen ipuçlarıyla bulmacayı çözün ve şifreyi bulun.',
    icon: 'fa-solid fa-border-all',
  },
  {
    id: ActivityType.JUMBLED_WORD_STORY,
    title: 'Kelime Bulma ve Hikaye Yazma',
    description: 'Karışık harflerden kelimeler bulun ve bu kelimelerle hikaye yazın.',
    icon: 'fa-solid fa-pen-nib',
  },
  {
    id: ActivityType.HOMONYM_SENTENCE_WRITING,
    title: 'Kelime Ağı (Eş Sesli)',
    description: 'Eş sesli kelimeler için iki farklı anlama gelen cümleler yazın.',
    icon: 'fa-solid fa-water',
  },
  {
    id: ActivityType.WORD_GRID_PUZZLE,
    title: 'Kelime Ağı (Yerleştirme)',
    description: 'Verilen kelimeleri bulmaca tablosuna doğru şekilde yerleştirin.',
    icon: 'fa-solid fa-table-cells-large',
  },
  {
    id: ActivityType.PROVERB_SAYING_SORT,
    title: 'Şifre Bul (Atasözü/Özdeyiş)',
    description: 'Cümlelerin atasözü mü yoksa özdeyiş mi olduğunu belirleyin.',
    icon: 'fa-solid fa-arrows-split-up-and-left',
  },
  {
    id: ActivityType.HOMONYM_IMAGE_MATCH,
    title: 'Resim Eşleştirme (Eş Sesli)',
    description: 'Eş sesli kelimelere ait görselleri eşleştirin.',
    icon: 'fa-solid fa-object-ungroup',
  },
  {
    id: ActivityType.ANTONYM_FLOWER_PUZZLE,
    title: 'Eşleştir (Zıt Anlamlı)',
    description: 'Papatyaların ortasındaki kelimelerin zıt anlamlılarını bulun ve şifreyi çözün.',
    icon: 'fa-solid fa-fan',
  },
  {
    id: ActivityType.PROVERB_WORD_CHAIN,
    title: 'Atasözü/Özdeyiş Bulma',
    description: 'Karışık kelimelerden atasözleri ve özdeyişler oluşturun.',
    icon: 'fa-solid fa-link-slash',
  },
  {
    id: ActivityType.THEMATIC_ODD_ONE_OUT,
    title: 'Farklı Özelliği Bulma',
    description: 'Belirli bir temaya uymayan kelimeyi bulun.',
    icon: 'fa-solid fa-magnifying-glass-arrow-right',
  },
  {
    id: ActivityType.SYNONYM_ANTONYM_GRID,
    title: 'Kelime Bulma (Eş/Zıt Anlamlı)',
    description: 'Kelimelerin eş ve zıt anlamlılarını bulup bulmacaya yerleştirin.',
    icon: 'fa-solid fa-right-left',
  },
  {
    id: ActivityType.PUNCTUATION_COLORING,
    title: 'Görsel Boyama (Noktalama)',
    description: 'Cümlelere uygun noktalama işaretlerini bularak resmi boyayın.',
    icon: 'fa-solid fa-pencil',
  },
  {
    id: ActivityType.PUNCTUATION_MAZE,
    title: 'Labirent (Noktalama)',
    description: 'Doğru kuralı bularak labirentte doğru yolu bulun.',
    icon: 'fa-solid fa-mouse',
  },
  {
    id: ActivityType.ANTONYM_RESFEBE,
    title: 'Resfebe (Zıt Anlamlı)',
    description: 'Resfebe ile kelimeyi bulun, sonra zıt anlamlısını yazın.',
    icon: 'fa-solid fa-image-landscape',
  },
  {
    id: ActivityType.THEMATIC_WORD_SEARCH_COLOR,
    title: 'Kelime Bulma (Tematik)',
    description: 'Belirli bir konudaki kelimeleri bulmacada bulun ve boyayın.',
    icon: 'fa-solid fa-highlighter',
  },
  {
    id: ActivityType.THEMATIC_ODD_ONE_OUT_SENTENCE,
    title: 'Şifre Bul (Farklı Kelime)',
    description: 'Her grupta farklı olan kelimeyi bulun ve cümle kurun.',
    icon: 'fa-solid fa-user-secret',
  },
  {
    id: ActivityType.PROVERB_SENTENCE_FINDER,
    title: 'Cümle Bulma (Atasözü)',
    description: 'Karışık kelimelerden atasözleri oluşturun ve boyayın.',
    icon: 'fa-solid fa-comments',
  },
  {
    id: ActivityType.SYNONYM_SEARCH_STORY,
    title: 'Dikkat Testi (Eş Anlamlı)',
    description: 'Kelimelerin eş anlamlılarını bulun, bulmacada arayın ve hikaye yazın.',
    icon: 'fa-solid fa-file-signature',
  },
  {
    id: ActivityType.PUNCTUATION_SPIRAL_PUZZLE,
    title: 'Sarmal Bulmaca (Noktalama)',
    description: 'Dil bilgisi ve noktalama kuralları ile sarmal bulmacayı çözün.',
    icon: 'fa-solid fa-pen-ruler',
  },
  {
    id: ActivityType.COLUMN_ODD_ONE_OUT_SENTENCE,
    title: 'Farklı Özelliği Bulma (Sütun)',
    description: 'Her sütunda farklı olan kelimeyi bulup cümle kurun.',
    icon: 'fa-solid fa-table-columns',
  },
  {
    id: ActivityType.SYNONYM_ANTONYM_COLORING,
    title: 'Görsel Boyama (Eş/Zıt Anlamlı)',
    description: 'Doğru eş/zıt anlamlı kelimeyi bularak resmi boyayın.',
    icon: 'fa-solid fa-fill-drip',
  },
  {
    id: ActivityType.PUNCTUATION_PHONE_NUMBER,
    title: 'Bul Bakalım (Telefon Numarası)',
    description: 'Noktalama ipuçlarını çözerek gizli telefon numarasını bulun.',
    icon: 'fa-solid fa-phone-volume',
  },
];

export const ACTIVITY_CATEGORIES: ActivityCategory[] = [
  {
    id: 'memory_attention',
    title: '🧠 Hafıza & Dikkat',
    description: 'Görsel hafıza ve dikkat geliştirme oyunları',
    icon: 'fa-solid fa-brain',
    activities: [
      ActivityType.WORD_MEMORY,
      ActivityType.VISUAL_MEMORY,
      ActivityType.NUMBER_SEARCH,
      ActivityType.FIND_THE_DUPLICATE_IN_ROW,
      ActivityType.LETTER_GRID_TEST,
      ActivityType.FIND_LETTER_PAIR,
      ActivityType.TARGET_SEARCH,
      ActivityType.COLOR_WHEEL_MEMORY,
      ActivityType.IMAGE_COMPREHENSION,
      ActivityType.CHARACTER_MEMORY,
      ActivityType.BURDON_TEST,
      ActivityType.SYNONYM_SEARCH_STORY,
    ]
  },
  {
    id: 'word_games',
    title: '📝 Kelime Oyunları',
    description: 'Anagram, sözcük avı ve dil becerileri',
    icon: 'fa-solid fa-spell-check',
    activities: [
      ActivityType.WORD_SEARCH,
      ActivityType.PROVERB_SEARCH,
      ActivityType.ANAGRAM,
      ActivityType.SPELLING_CHECK,
      ActivityType.WORD_COMPARISON,
      ActivityType.PROVERB_FILL_IN_THE_BLANK,
      ActivityType.LETTER_BRIDGE,
      ActivityType.WORD_LADDER,
      ActivityType.WORD_FORMATION,
      ActivityType.REVERSE_WORD,
      ActivityType.WORD_GROUPING,
      ActivityType.MINI_WORD_GRID,
      ActivityType.PASSWORD_FINDER,
      ActivityType.SYLLABLE_COMPLETION,
      ActivityType.SYNONYM_WORD_SEARCH,
      ActivityType.SPIRAL_PUZZLE,
      ActivityType.CROSSWORD,
      ActivityType.JUMBLED_WORD_STORY,
      ActivityType.HOMONYM_SENTENCE_WRITING,
      ActivityType.WORD_GRID_PUZZLE,
      ActivityType.HOMONYM_IMAGE_MATCH,
      ActivityType.ANTONYM_FLOWER_PUZZLE,
      ActivityType.SYNONYM_ANTONYM_GRID,
      ActivityType.PUNCTUATION_COLORING,
      ActivityType.ANTONYM_RESFEBE,
      ActivityType.THEMATIC_WORD_SEARCH_COLOR,
      ActivityType.PROVERB_SENTENCE_FINDER,
      ActivityType.PUNCTUATION_SPIRAL_PUZZLE,
      ActivityType.SYNONYM_ANTONYM_COLORING,
    ]
  },
  {
    id: 'math_geometry',
    title: '🔢 Matematik & Geometri',
    description: 'Sayma, simetri ve şekil egzersizleri',
    icon: 'fa-solid fa-calculator',
    activities: [
      ActivityType.MATH_PUZZLE,
      ActivityType.SHAPE_COUNTING,
    ]
  },
  {
    id: 'reading_comprehension',
    title: '📚 Okuma Anlama',
    description: 'Hikaye okuma ve metin analizi',
    icon: 'fa-solid fa-book-open',
    activities: [
      ActivityType.STORY_COMPREHENSION, // Also for "Hikayeye Dikkat"
      ActivityType.STORY_ANALYSIS,
      ActivityType.STORY_CREATION_PROMPT,
      ActivityType.WORDS_IN_STORY,
      ActivityType.STORY_SEQUENCING,
      ActivityType.PROVERB_SAYING_SORT,
      ActivityType.PROVERB_WORD_CHAIN,
    ]
  },
  {
    id: 'logic_problems',
    title: '🧩 Mantık Problemleri',
    description: 'Eleme yöntemi ve problem çözme',
    icon: 'fa-solid fa-lightbulb',
    activities: [
        ActivityType.NUMBER_PATTERN,
        ActivityType.SHAPE_MATCHING,
        ActivityType.SYMBOL_CIPHER,
        ActivityType.COORDINATE_CIPHER,
        ActivityType.SHAPE_NUMBER_PATTERN,
        ActivityType.ABC_CONNECT,
        ActivityType.WORD_CONNECT,
        ActivityType.THEMATIC_ODD_ONE_OUT,
        ActivityType.PUNCTUATION_MAZE,
        ActivityType.THEMATIC_ODD_ONE_OUT_SENTENCE,
        ActivityType.COLUMN_ODD_ONE_OUT_SENTENCE,
        ActivityType.PUNCTUATION_PHONE_NUMBER,
    ]
  },
  {
    id: 'perceptual_skills',
    title: '👁️ Algısal Beceriler',
    description: 'Şekil tanıma ve desen farkı bulma',
    icon: 'fa-solid fa-eye',
    activities: [
      ActivityType.FIND_THE_DIFFERENCE,
      ActivityType.STROOP_TEST, // Also for "Sağ Beyin - Sol Beyin"
      ActivityType.ODD_ONE_OUT,
      ActivityType.FIND_IDENTICAL_WORD,
      ActivityType.GRID_DRAWING,
      ActivityType.CHAOTIC_NUMBER_SEARCH,
      ActivityType.BLOCK_PAINTING,
      ActivityType.VISUAL_ODD_ONE_OUT,
      ActivityType.SYMMETRY_DRAWING,
      ActivityType.FIND_DIFFERENT_STRING,
      ActivityType.DOT_PAINTING,
    ]
  },
];