import { BoslukDoldurmaItem } from '../../types/kelimeCumle';

export const BOSLUK_DOLDURMA_SOURCES: BoslukDoldurmaItem[] = [
    { sentence: "Bugün hava çok ……… .", answer: "soğuk" },
    { sentence: "Atatürk 1881 yılında Selanik’te ……… .", answer: "doğdu" },
    { sentence: "Eren sınıfın camını ……… .", answer: "kırdı" },
    { sentence: "Emre hasta ……… .", answer: "oldu" },
    { sentence: "Annem pazardan armut ……… .", answer: "aldı" },
    { sentence: "Emine denizde ……… .", answer: "yüzüyor" },
    { sentence: "Burcu dişlerini ……… .", answer: "fırçaladı" },
    { sentence: "Arzu akşam televizyon ……… .", answer: "seyretti" },
    { sentence: "Çocuklar bahçede top ……… .", answer: "oynadı" },
    { sentence: "Hasan sabah saat 7.30’da ……… .", answer: "uyandı" },
    { sentence: "Ufuk okuldan eve gelince çok ……… .", answer: "çalıştı" },
    { sentence: "Meral yemekten önce ellerini ……… .", answer: "yıkadı" },
    { sentence: "Arı ……… yapar.", answer: "bal" },
    { sentence: "Küçük kedi ……… içti.", answer: "süt" },
    { sentence: "……… ot yiyor.", answer: "Koyunlar" },
    { sentence: "……… uçak kullanıyor.", answer: "Pilot" },
    { sentence: "Osman ……… ile balık tutuyor.", answer: "olta" },
    { sentence: "Tavuklar ve horoz ……… yiyor.", answer: "yem" },
    { sentence: "……… mevsimi çok soğuk.", answer: "Kış" },
    { sentence: "Öğrenciler bayramda sınıfta ……… astı.", answer: "bayrak" },
    { sentence: "Tuvaletten sonra ellerimi ……… .", answer: "yıkarım" },
    { sentence: "İtfaiye ……… söndürdü.", answer: "yangını" },
    { sentence: "Berber ……… kesti.", answer: "saçlarımı" },
    { sentence: "Fatih arabaya ……… .", answer: "bindi" },
    { sentence: "Hakan ……… giydi.", answer: "mont" },
    { sentence: "Salı günü Kemal ve İbrahim ……… etti.", answer: "kavga" },
    { sentence: "Dün akşam eve ……… geldi.", answer: "misafir" },
    { sentence: "Gölde ……… yüzüyor.", answer: "ördekler" },
    { sentence: "Papatya ve güller güzel ……… .", answer: "kokuyor" },
    { sentence: "Bakkaldan ……… aldım.", answer: "çikolata" },
    { sentence: "Bir yıl dört ……… .", answer: "mevsim" },
    { sentence: "Bir yıl 12 ……… .", answer: "ay" },
    { sentence: "Bir yıl 365 ……… .", answer: "gün" },
    { sentence: "Bir hafta ……… gün.", answer: "yedi" },
    { sentence: "Haftanın ilk günü ……… .", answer: "pazartesi" },
    { sentence: "Tatil günleri cumartesi ve ……… .", answer: "pazar" },
    { sentence: "Bir gün 24 ……… .", answer: "saat" },
    { sentence: "……… mevsimi çok sıcak.", answer: "Yaz" },
    { sentence: "Bir ay ……… gün.", answer: "30" },
    { sentence: "……… mevsiminde çiçekler açar.", answer: "İlkbahar" },
    { sentence: "Çocuklar ……… sallanıyor.", answer: "salıncakta" },
    { sentence: "Hayvanat bahçesinde ……… gördüm.", answer: "zürafa" },
    { sentence: "Dedem ……… okuyor.", answer: "gazete" },
    { sentence: "Ablam manavdan ……… aldı.", answer: "çilek" },
    { sentence: "Hatice ……… taze ekmek aldı.", answer: "fırından" },
    { sentence: "……… mutfakta yemek yapıyor.", answer: "Aşçı" },
    { sentence: "Dedem camide ……… kılıyor.", answer: "namaz" },
    { sentence: "……… günü okul tatil.", answer: "Pazar" },
    { sentence: "……… öğrencilere aşı yapıyor.", answer: "Hemşire" },
    { sentence: "Akşam saat ……… uyudum.", answer: "22:00'de" },
    { sentence: "Okula gitmek için ……… bindim.", answer: "servise" },
    { sentence: "Öğretmenimiz tahtaya ……… yazdı.", answer: "yazı" },
    { sentence: "Ali çantasından ……… çıkardı.", answer: "kalemini" },
    { sentence: "Yemekten sonra ……… fırçalamalıyız.", answer: "dişlerimizi" },
    { sentence: "Pazardan taze ……… ve sebze aldık.", answer: "meyve" },
    { sentence: "Kardeşim oyuncağını ……… .", answer: "kırdı" },
    { sentence: "Gökyüzünde parlak ……… var.", answer: "güneş" },
    { sentence: "Balıklar ……… içinde yüzer.", answer: "suyun" },
    { sentence: "Kuşlar kanatlarını çırparak ……… .", answer: "uçar" },
    { sentence: "Araba ……… durdu.", answer: "kırmızı ışıkta" },
    { sentence: "Dedem bahçedeki çiçekleri ……… .", answer: "suladı" },
    { sentence: "Manavdan üç kilo ……… aldım.", answer: "elma" },
    { sentence: "Sobanın içinde ……… yanıyor.", answer: "odunlar" },
    { sentence: "Tavşan havuç ……… çok sever.", answer: "yemeyi" },
    { sentence: "Annem mutfakta lezzetli bir ……… yaptı.", answer: "kek" },
    { sentence: "Okulda teneffüs zili ……… .", answer: "çaldı" },
    { sentence: "Yağmur yağınca ……… açtık.", answer: "şemsiyemizi" },
    { sentence: "Dün gece rüyamda ……… gördüm.", answer: "devler" },
    { sentence: "Sınıfın duvarına ……… astık.", answer: "harita" },
    { sentence: "Kışın kalın ……… giymeliyiz.", answer: "kazaklar" },
    { sentence: "Deniz kıyısında ……… topladık.", answer: "deniz kabuğu" },
    { sentence: "Fatih bugün okula ……… geldi.", answer: "geç" },
    { sentence: "Meral ödevlerini ……… bitirdi.", answer: "vaktinde" },
    { sentence: "Babam bana yeni bir ……… aldı.", answer: "bisiklet" },
    { sentence: "Kayıp kedimizi ……… bulduk.", answer: "bahçede" },
    { sentence: "Sobanın üstünde ……… kaynıyor.", answer: "çaydanlık" },
    { sentence: "Öğle yemeğinde ……… içtik.", answer: "ayran" },
    { sentence: "Bahçedeki ağaçtan ……… topladık.", answer: "erik" },
    { sentence: "Ali sabah erkenden ……… .", answer: "kalktı" },
    { sentence: "Ayşe piyano ……… öğreniyor.", answer: "çalmayı" },
    { sentence: "Kamyon yolda ……… kaldı.", answer: "yolda" },
    { sentence: "Postacı bize ……… getirdi.", answer: "mektup" },
    { sentence: "Gözlüklerimi ……… unutmuşum.", answer: "evde" },
    { sentence: "Piknikte ……… oynadık.", answer: "yakantop" },
    { sentence: "Annem pazardan ……… aldı.", answer: "taze fasulye" },
    { sentence: "Sokak lambaları ……… yanar.", answer: "akşam" },
    { sentence: "Dizim kanayınca ……… yapıştırdık.", answer: "yara bandı" },
    { sentence: "Müzayede evinde eski ……… satıldı.", answer: "tablolar" },
    { sentence: "Kütüphanede sessizce ……… okuduk.", answer: "kitap" },
    { sentence: "Yaz tatilinde ……… yüzmeye gideceğiz.", answer: "denize" },
    { sentence: "Ablam üniversitede ……… okuyor.", answer: "tıp" },
    { sentence: "Dolabın içinden temiz ……… aldım.", answer: "çoraplar" },
    { sentence: "Çiftlikte ……… sağılıyor.", answer: "inekler" },
    { sentence: "Aslan ormanın ……… .", answer: "kralıdır" },
    { sentence: "Kelebekler ……… üstüne kondu.", answer: "çiçeklerin" },
    { sentence: "Ablam saçlarını ……… ördü.", answer: "iki yandan" },
    { sentence: "Babam arabayı ……… yıkadı.", answer: "fırçayla" },
    { sentence: "Meyveleri yemeden önce ……… .", answer: "yıkamalıyız" },
    { sentence: "Güneş doğudan ……… .", answer: "doğar" },
    { sentence: "Ay geceleri gökyüzünde ……… .", answer: "parlar" },
    { sentence: "Kurbağalar gölde ……… .", answer: "zıplar" },
    { sentence: "Zürafa çok uzun bir ……… sahiptir.", answer: "boyna" },
    { sentence: "Fil hortumuyla ……… içer.", answer: "su" },
    { sentence: "Maymunlar ağaçtan ağaca ……… .", answer: "atlar" },
    { sentence: "Kaplumbağa çok ……… yürür.", answer: "yavaş" },
    { sentence: "Tavşanlar çok ……… koşar.", answer: "hızlı" },
    { sentence: "Arılar çiçeklerden ……… toplar.", answer: "öz" },
    { sentence: "Karıncalar kış için ……… biriktirir.", answer: "yiyecek" },
    { sentence: "Yılanlar yerde ……… ilerler.", answer: "sürünerek" },
    { sentence: "Yunuslar denizde ……… yapar.", answer: "gösteri" },
    { sentence: "Balina dünyanın en büyük ……… .", answer: "hayvanıdır" },
    { sentence: "Öğretmenimiz bize ……… anlattı.", answer: "masal" },
    { sentence: "Okul çantam çok ……… olmuş.", answer: "ağır" },
    { sentence: "Defterime ……… ile resim çizdim.", answer: "boya kalemleri" },
    { sentence: "Masamın üstünde ……… duruyor.", answer: "lambam" },
    { sentence: "Sabah kahvaltısında ……… yedim.", answer: "yumurta" },
    { sentence: "Akşam yemeğinde ……… var.", answer: "makarna" },
    { sentence: "Susam Sokağı'nı ……… çok severdim.", answer: "izlemeyi" },
    { sentence: "Atatürk'ün mezarı ……… .", answer: "Anıtkabir'dedir" },
    { sentence: "Türkiye'nin başkenti ……… .", answer: "Ankara'dır" },
    { sentence: "İstanbul'da tarihi ……… çoktur.", answer: "camiler" },
    { sentence: "Karadeniz'de ……… çok yağar.", answer: "yağmur" },
    { sentence: "Antalya'da yazlar çok ……… geçer.", answer: "sıcak" },
    { sentence: "Erzurum'da kışın çok ……… yağar.", answer: "kar" },
    { sentence: "İzmir'in ……… meşhurdur.", answer: "boyozu" },
    { sentence: "Bursa'nın ……… tadı damakta kalır.", answer: "iskenderi" },
    { sentence: "Hafta içi ……… okula gideriz.", answer: "beş gün" },
    { sentence: "Hafta sonu Cumartesi ve ……… .", answer: "Pazar'dır" },
    { sentence: "Yarın hava ……… olacakmış.", answer: "güneşli" },
    { sentence: "Bugün kendimi çok ……… hissediyorum.", answer: "mutlu" },
    { sentence: "Arkadaşım bana ……… verdi.", answer: "ödevini" },
    { sentence: "Teneffüste ……… oynadık.", answer: "saklambaç" },
    { sentence: "Kitap okumak ……… geliştirir.", answer: "hayal gücünü" },
    { sentence: "Bisiklete binerken ……… takmalıyız.", answer: "kask" },
    { sentence: "Denizde yüzerken ……… dikkat etmeliyiz.", answer: "dalgalara" },
    { sentence: "Ormanda piknik yaparken ……… yakmamalıyız.", answer: "ateş" },
    { sentence: "Çevremizi temiz ……… korumalıyız.", answer: "tutarak" },
    { sentence: "Ağaçlar havayı ……… .", answer: "temizler" },
    { sentence: "Geri dönüşüm doğayı ……… .", answer: "korur" },
    { sentence: "Hayvanlara sevgiyle ……… .", answer: "yaklaşmalıyız" },
    { sentence: "Yaşlılara yardım ……… .", answer: "etmeliyiz" },
    { sentence: "Otobüste hamilelere ……… vermeliyiz.", answer: "yer" },
    { sentence: "Trafik kurallarına ……… hayat kurtarır.", answer: "uymak" },
    { sentence: "Yalancının mumu ……… kadar yanar.", answer: "yatsıya" },
    { sentence: "Damlaya damlaya ……… olur.", answer: "göl" },
    { sentence: "Gözden ırak olan ……… de ırak olur.", answer: "gönülden" },
    { sentence: "Gülme komşuna ……… başına.", answer: "gelir" },
    { sentence: "Sakla samanı ……… zamanı.", answer: "gelir" },
    { sentence: "İyilik yap ……… at.", answer: "denize" },
    { sentence: "Meyve veren ağaç ……… .", answer: "taşlanır" },
    { sentence: "Bakarsan bağ, bakmazsan ……… olur.", answer: "dağ" },
    { sentence: "Aslan yattığı ……… belli olur.", answer: "yerden" },
    { sentence: "Akıl akıldan ……… .", answer: "üstündür" },
    { sentence: "Bir elin nesi var, ……… sesi var.", answer: "iki elin" },
    { sentence: "Birlikten ……… doğar.", answer: "kuvvet" },
    { sentence: "Çalışan demir ……… .", answer: "ışıldayacak" },
    { sentence: "Tatlı dil ……… deliğinden çıkarır.", answer: "yılanı" },
    { sentence: "Komşu komşunun ……… muhtaçtır.", answer: "külüne" },
    { sentence: "Zahmetsiz ……… olmaz.", answer: "rahmet" },
    { sentence: "Görünen köy ……… istemez.", answer: "kılavuz" },
    { sentence: "Ayağını yorganına göre ……… .", answer: "uzat" },
    { sentence: "Keskin sirke ……… zarar.", answer: "küpüne" },
    { sentence: "Rüzgar eken ……… biçer.", answer: "fırtına" },
    { sentence: "Sütten ağzı yanan ……… üfleyerek yer.", answer: "yoğurdu" },
    { sentence: "Ateş olmayan yerden ……… çıkmaz.", answer: "duman" },
    { sentence: "Bugünün işini ……… bırakma.", answer: "yarına" },
    { sentence: "Akıl yaşta değil ……… .", answer: "baştadır" },
    { sentence: "Altın eşik ……… eşiğe muhtaçtır.", answer: "gümüş" },
    { sentence: "Bal tutan parmağını ……… .", answer: "yalar" },
    { sentence: "Besle kargayı ……… gözünü.", answer: "oysun" },
    { sentence: "Can boğazdan ……… .", answer: "gelir" },
    { sentence: "Dost kara günde ……… olur.", answer: "belli" },
    { sentence: "Emek olmadan ……… olmaz.", answer: "yemek" },
    { sentence: "Evdeki hesap ……… uymaz.", answer: "çarşıya" },
    { sentence: "Göz görmeyince ……… katlanır.", answer: "gönül" },
    { sentence: "İşleyen demir pas ……… .", answer: "tutmaz" },
    { sentence: "Kaçan balık ……… olur.", answer: "büyük" },
    { sentence: "Kurt kocayınca ……… maskarası olur.", answer: "köpeklerin" },
    { sentence: "Ne ekersen ……… biçersin.", answer: "onu" },
    { sentence: "Öfke ile kalkan ……… oturur.", answer: "zararla" },
    { sentence: "Sabreden derviş ……… ermiş.", answer: "muradına" },
    { sentence: "Yalancının mumu yatsıya kadar ……… .", answer: "yanar" },
    { sentence: "Zaman nakittir ……… .", answer: "" },
    { sentence: "Kardeşim bugün parkta ……… .", answer: "oynadı" },
    { sentence: "Annem pazardan ……… aldı.", answer: "domates" },
    { sentence: "Babam bana yeni ……… aldı.", answer: "ayakkabı" },
    { sentence: "Öğretmenimiz bize ……… yazdırdı.", answer: "şiir" },
    { sentence: "Dün akşam çok ……… yağdı.", answer: "yağmur" },
    { sentence: "Sınıfın camı ……… .", answer: "kırıldı" },
    { sentence: "Kedim mırıl mırıl ……… .", answer: "uyuyor" },
    { sentence: "Köpeğim bahçede ……… .", answer: "koşuyor" },
    { sentence: "Kuşlar ağaçta ……… .", answer: "ötüyor" },
    { sentence: "Çiçekler saksıda ……… .", answer: "büyüyor" },
    { sentence: "Güneş tepeden ……… .", answer: "parlıyor" },
    { sentence: "Ay geceleri ……… .", answer: "doğuyor" },
    { sentence: "Yıldızlar gökyüzünde ……… .", answer: "titriyor" },
    { sentence: "Bulutlar gökyüzünde ……… .", answer: "yüzüyor" },
    { sentence: "Rüzgar sert ……… .", answer: "esiyor" },
    { sentence: "Kar her yeri ……… .", answer: "kapladı" },
    { sentence: "Dolu camlara ……… .", answer: "vuruyor" },
    { sentence: "Şimşek birden ……… .", answer: "çaktı" },
    { sentence: "Gök gürültüsü ……… .", answer: "korkuttu" },
    { sentence: "Gökkuşağı çok ……… .", answer: "renkli" },
    { sentence: "Deniz masmavi ……… .", answer: "görünüyor" },
    { sentence: "Kumlar çok ……… .", answer: "sıcak" },
    { sentence: "Taşlar yolda ……… .", answer: "duruyor" },
    { sentence: "Ağaçlar ormanda ……… .", answer: "sıralı" },
    { sentence: "Orman çok ……… .", answer: "koyu" },
    { sentence: "Dağlar çok ……… .", answer: "yüksek" },
    { sentence: "Ova çok ……… .", answer: "geniş" },
    { sentence: "Nehir hızlı ……… .", answer: "akıyor" },
    { sentence: "Göl durgun ……… .", answer: "duruyor" },
    { sentence: "Şelale coşkuyla ……… .", answer: "çağlıyor" },
    { sentence: "Mağara karanlık ……… .", answer: "görünüyor" },
    { sentence: "Yol uzun ……… .", answer: "sürüyor" },
    { sentence: "Köprü nehri ……… .", answer: "bağlıyor" },
    { sentence: "Tünel dağın içinden ……… .", answer: "geçiyor" },
    { sentence: "Sokak sessiz ……… .", answer: "duruyor" },
    { sentence: "Evimiz sıcak ……… .", answer: "oldu" },
    { sentence: "Bahçemiz yeşil ……… .", answer: "kaldı" },
    { sentence: "Okulumuz büyük ……… .", answer: "yapıldı" },
    { sentence: "Sınıfımız aydınlık ……… .", answer: "oldu" },
    { sentence: "Masamız sağlam ……… .", answer: "duruyor" },
    { sentence: "Sandalyemiz rahat ……… .", answer: "oldu" },
    { sentence: "Dolabımız düzenli ……… .", answer: "kaldı" },
    { sentence: "Yatağımız yumuşak ……… .", answer: "oldu" },
    { sentence: "Yastığımız kabarık ……… .", answer: "yapılmış" },
    { sentence: "Yorganımız kalın ……… .", answer: "oldu" },
    { sentence: "Halı yumuşak ……… .", answer: "duruyor" },
    { sentence: "Perdemiz beyaz ……… .", answer: "kaldı" },
    { sentence: "Lambamız parlak ……… .", answer: "yanıyor" },
    { sentence: "Televizyon sesli ……… .", answer: "çalışıyor" },
    { sentence: "Bilgisayar hızlı ……… .", answer: "açılıyor" },
    { sentence: "Telefon ince ……… .", answer: "yapılmış" },
    { sentence: "Saat doğru ……… .", answer: "işliyor" },
    { sentence: "Ayna parlak ……… .", answer: "duruyor" },
    { sentence: "Tarak ince ……… .", answer: "yapılmış" },
    { sentence: "Sabun mis ……… .", answer: "kokuyor" },
    { sentence: "Şampuan köpüklü ……… .", answer: "oldu" },
    { sentence: "Havlu kuru ……… .", answer: "kaldı" },
    { sentence: "Fırça sert ……… .", answer: "oldu" },
    { sentence: "Macun beyaz ……… .", answer: "görünüyor" },
    { sentence: "Bardak cam ……… .", answer: "yapılmış" },
    { sentence: "Tabak seramik ……… .", answer: "oldu" },
    { sentence: "Kaşık metal ……… .", answer: "yapılmış" },
    { sentence: "Çatal sivri ……… .", answer: "oldu" },
    { sentence: "Bıçak keskin ……… .", answer: "oldu" },
    { sentence: "Tencere sıcak ……… .", answer: "oldu" },
    { sentence: "Tava yağlı ……… .", answer: "kaldı" },
    { sentence: "Süzgeç delikli ……… .", answer: "yapılmış" },
    { sentence: "Rende tırtıklı ……… .", answer: "oldu" },
    { sentence: "Masa örtüsü ……… .", answer: "serildi" },
    { sentence: "Mutfak temiz ……… .", answer: "kaldı" },
    { sentence: "Antre dar ……… .", answer: "görünüyor" },
    { sentence: "Koridor uzun ……… .", answer: "yapılmış" },
    { sentence: "Balkon havadar ……… .", answer: "oldu" },
    { sentence: "Çatı dik ……… .", answer: "yapıldı" },
    { sentence: "Baca tüter ……… .", answer: "duruyor" },
    { sentence: "Kapı kapalı ……… .", answer: "kaldı" },
    { sentence: "Pencere açık ……… .", answer: "duruyor" },
    { sentence: "Bahçe kapısı ……… .", answer: "kilitlendi" },
    { sentence: "Garaj kapısı ……… .", answer: "kapandı" },
    { sentence: "Zil yüksek ……… .", answer: "çaldı" },
    { sentence: "Anahtar demir ……… .", answer: "yapılmış" },
    { sentence: "Kilit sağlam ……… .", answer: "oldu" },
    { sentence: "Çanta deri ……… .", answer: "yapılmış" },
    { sentence: "Cüzdan para ……… .", answer: "dolu" },
    { sentence: "Kemer siyah ……… .", answer: "oldu" },
    { sentence: "Şapka bordo ……… .", answer: "kaldı" },
    { sentence: "Eldiven yün ……… .", answer: "yapılmış" },
    { sentence: "Atkı örgü ……… .", answer: "yapıldı" },
    { sentence: "Çorap delik ……… .", answer: "oldu" },
    { sentence: "Pabuç yeni ……… .", answer: "alındı" },
    { sentence: "Çizme uzun ……… .", answer: "duruyor" },
    { sentence: "Sandalet hafif ……… .", answer: "oldu" },
    { sentence: "Terlik rahat ……… .", answer: "yapılmış" },
    { sentence: "Gözlük camı ……… .", answer: "kırıldı" },
    { sentence: "Saat kordonu ……… .", answer: "koptu" },
    { sentence: "Yüzük altın ……… .", answer: "yapılmış" },
    { sentence: "Küpe parlak ……… .", answer: "görünüyor" },
    { sentence: "Kolye inci ……… .", answer: "dizili" },
    { sentence: "Bilezik gümüş ……… .", answer: "yapıldı" },
    { sentence: "Toka çiçekli ……… .", answer: "oldu" },
    { sentence: "Parfüm hoş ……… .", answer: "kokuyor" },
    { sentence: "Resim defterime ……… çizdim.", answer: "başarılar" },
    { sentence: "Sulu boya ile ……… yaptık.", answer: "deniz" },
    { sentence: "Boyama yaparken ……… dışına taşırmadım.", answer: "çizgilerin" },
    { sentence: "Makasla kağıdı ……… kestim.", answer: "düzgün" },
    { sentence: "Yapıştırıcı parmaklarıma ……… .", answer: "bulaştı" },
    { sentence: "Elişi kağıtlarından ……… yaptık.", answer: "uçak" },
    { sentence: "Hamurdan ……… şekli verdim.", answer: "elma" },
    { sentence: "Kilin kokusu ……… gibiydi.", answer: "toprak" },
    { sentence: "Kalemtraşla kalemimi ……… .", answer: "açtım" },
    { sentence: "Silgi tozlarını ……… .", answer: "temizledim" },
    { sentence: "Masa lambası odayı ……… .", answer: "aydınlattı" },
    { sentence: "Gece lambası ……… ışık veriyor.", answer: "hafif" },
    { sentence: "Sınıfın tavanı çok ……… .", answer: "yüksek" },
    { sentence: "Okul bahçesi ……… doluydu.", answer: "çocuklarla" },
    { sentence: "Basketbol potası ……… duruyor.", answer: "yukarıda" },
    { sentence: "Futbol kalesi ……… .", answer: "başındaydı" },
    { sentence: "Voleybol filesi ……… .", answer: "gerildi" },
    { sentence: "Tenis raketi çok ……… .", answer: "hafifti" },
    { sentence: "Masa tenisi ……… oynanır.", answer: "hızlı" },
    { sentence: "Yüzme havuzu ……… doluydu.", answer: "suyla" },
    { sentence: "Deniz suyu çok ……… .", answer: "tuzluydu" },
    { sentence: "Kumdan kale ……… .", answer: "yıkıldı" },
    { sentence: "Güneş kremi ……… korur.", answer: "yakıcıdan" },
    { sentence: "Deniz gözlüğüyle ……… gördüm.", answer: "balıkları" },
    { sentence: "Paletlerle daha ……… yüzdüm.", answer: "hızlı" },
    { sentence: "Can yeleği ……… tutar.", answer: "su üstünde" },
    { sentence: "Gemi limandan ……… .", answer: "ayrıldı" },
    { sentence: "Kayık dalgalarla ……… .", answer: "sallandı" },
    { sentence: "Kaptan dümene ……… .", answer: "geçti" },
    { sentence: "Yelkenli rüzgarla ……… .", answer: "ilerledi" },
    { sentence: "Denizaltı suyun ……… gitti.", answer: "altından" },
    { sentence: "Buzdağı gemi için ……… .", answer: "tehlikeliydi" },
    { sentence: "Ada ıssız ……… .", answer: "görünüyordu" },
    { sentence: "Kumsal altın gibi ……… .", answer: "parlıyordu" },
    { sentence: "Martılar denizin üstünde ……… .", answer: "uçuyordu" },
    { sentence: "Yengeç yan yan ……… .", answer: "yürüyordu" },
    { sentence: "Istakozun kıskaçları ……… .", answer: "sertti" },
    { sentence: "Ahtapotun sekiz ……… var.", answer: "kolu" },
    { sentence: "Köpekbalığı dişleri ……… .", answer: "keskindir" },
    { sentence: "Balina su ……… .", answer: "fışkırtıyor" },
    { sentence: "Yunuslar çok ……… .", answer: "arkadaştır" },
    { sentence: "Fayton atlarla ……… .", answer: "çekiliyordu" },
    { sentence: "Traktör tarlayı ……… .", answer: "sürüyordu" },
    { sentence: "Biçerdöver ekinleri ……… .", answer: "topluyordu" },
    { sentence: "Kamyon ağır yükleri ……… .", answer: "taşıyordu" },
    { sentence: "Vinç betonu ……… kaldırdı.", answer: "havaya" },
    { sentence: "Buldozer yolu ……… .", answer: "açtı" },
    { sentence: "Asfalt dökme aracı ……… yayıyordu.", answer: "sıcaklık" },
    { sentence: "İtfaiye sireni ……… .", answer: "bağırdı" },
    { sentence: "Ambulans hastayı ……… .", answer: "yetiştirdi" },
    { sentence: "Polis arabası ……… çalıyor.", answer: "mavi ışık" },
    { sentence: "Motosiklet vın vın …… .", answer: "geçti" },
    { sentence: "Bisiklet kornası ……… .", answer: "çaldı" },
    { sentence: "Tekerlek yolda ……… .", answer: "yuvarlandı" },
    { sentence: "Direksiyonu sıkıca ……… .", answer: "tuttum" },
    { sentence: "Fren yapınca araba ……… .", answer: "durdu" },
    { sentence: "Emniyet kemerini ……… .", answer: "bağladım" },
    { sentence: "Aynadan arkadaki yolu ……… .", answer: "gördüm" },
    { sentence: "Far gece yolu ……… .", answer: "aydınlattı" },
    { sentence: "Silecek yağmuru ……… .", answer: "sildi" },
    { sentence: "Egzozdan duman ……… .", answer: "çıktı" },
    { sentence: "Benzin deposu ……… .", answer: "doldu" },
    { sentence: "Motor sıcaklık ……… .", answer: "veriyor" },
    { sentence: "Müzik sesi kulaklarımı ……… .", answer: "doldurdu" },
    { sentence: "Şarkı sözlerini ……… .", answer: "ezberledim" },
    { sentence: "Nota kağıdına ……… .", answer: "baktım" },
    { sentence: "Gitar tellerine ……… .", answer: "vurdum" },
    { sentence: "Piyano tuşları ……… ve siyahtı.", answer: "beyaz" },
    { sentence: "Kemanın sesi çok ……… .", answer: "yanıktı" },
    { sentence: "Flüt çalmayı ……… öğrendim.", answer: "okulda" },
    { sentence: "Davul güm güm ……… .", answer: "vurdu" },
    { sentence: "Zil sesini ……… .", answer: "duydum" },
    { sentence: "Orkestra şefi ……… .", answer: "başladı" },
    { sentence: "Konser çok ……… geçti.", answer: "eğlenceli" },
    { sentence: "Sahne ışıkları ……… .", answer: "parladı" },
    { sentence: "Seyirciler ……… .", answer: "alkışladı" },
    { sentence: "Mikrofon sesi ……… .", answer: "yükseltti" },
    { sentence: "Hoparlörden ses ……… .", answer: "yayıldı" },
    { sentence: "Kamera çekim ……… .", answer: "yaptı" },
    { sentence: "Fotoğraf makinesi flaşı ……… .", answer: "patladı" },
    { sentence: "Albüm fotoğraflarla ……… .", answer: "doldu" },
    { sentence: "Çerçeve duvara ……… .", answer: "asıldı" },
    { sentence: "Heykel taştan ……… .", answer: "yapılmış" },
    { sentence: "Müze sessiz ……… .", answer: "olmalıydı" },
    { sentence: "Sergi çok ……… .", answer: "ilginçti" },
    { sentence: "Tablo renkli ……… .", answer: "görünüyordu" },
    { sentence: "Fırça darbeleri ……… .", answer: "belliydi" },
    { sentence: "Palet üstünde boyalar ……… .", answer: "karıştı" },
    { sentence: "Tuval bembeyaz ……… .", answer: "duruyordu" },
    { sentence: "Şizol (şövale) tuvali ……… .", answer: "tutuyordu" },
    { sentence: "Gökyüzü bulutlarla ……… .", answer: "kaplandı" },
    { sentence: "Yıldızlar gece ……… .", answer: "parlar" },
    { sentence: "Ay dede gülümsüyor ……… .", answer: "gibiydi" },
    { sentence: "Samanyolu çok ……… .", answer: "uzaktı" },
    { sentence: "Gezegenler güneşin etrafında ……… .", answer: "döner" },
    { sentence: "Dünya kendi etrafında ……… .", answer: "döner" },
    { sentence: "Mars kızıl ……… .", answer: "gezegenidir" },
    { sentence: "Ay yüzeyi ……… doluydu.", answer: "çukurlarla" },
    { sentence: "Roket uzaya ……… .", answer: "fırlatıldı" },
    { sentence: "Astronot kıyafeti çok ……… .", answer: "kalındı" },
    { sentence: "Yer çekimi bizi ……… .", answer: "tutar" },
    { sentence: "Teleskopla uzakları ……… .", answer: "izledim" },
    { sentence: "Mikroskopla mikropları ……… .", answer: "gördüm" },
    { sentence: "Deney tüpü ……… .", answer: "patlamış" },
    { sentence: "Laboratuvar beyaz ……… .", answer: "doluydu" },
    { sentence: "Kimya hocası karışımı ……… .", answer: "yaptı" },
    { sentence: "Fizik dersinde ……… öğrendik.", answer: "hareketi" },
    { sentence: "Biyoloji dersinde ……… inceledik.", answer: "bitkileri" },
    { sentence: "Coğrafya dersinde ……… baktık.", answer: "haritaya" },
    { sentence: "Tarih dersinde ……… öğrendik.", answer: "geçmişi" },
    { sentence: "Matematik dersinde ……… yaptık.", answer: "toplama" },
    { sentence: "Türkçe dersinde ……… yazdık.", answer: "kompozisyon" },
    { sentence: "Güzel sanatlar dersinde ……… çizdik.", answer: "resim" },
    { sentence: "Beden eğitimi dersinde ……… .", answer: "koştuk" },
    { sentence: "Karne günü çok ……… .", answer: "heyecanlıydı" },
    { sentence: "Diploma töreni ……… .", answer: "yapıldı" },
    { sentence: "Mezuniyet balosu ……… .", answer: "eğlenceliydi" },
    { sentence: "Sınav soruları ……… .", answer: "zordu" },
    { sentence: "Zayıf not beni ……… .", answer: "üzdü" },
    { sentence: "Takdir belgesi ……… .", answer: "aldım" },
    { sentence: "Teşekkür belgesi ……… .", answer: "aldım" },
    { sentence: "Onur belgesi gurur ……… .", answer: "vericiydi" },
    { sentence: "Burs kazandığım için ……… .", answer: "mutluyum" },
    { sentence: "Kütüphane kartımı ……… .", answer: "çıkardım" },
    { sentence: "Sırt çantamı ……… .", answer: "takıp çıktım" },
    { sentence: "Beslenme çantamda ……… vardı.", answer: "kek" },
    { sentence: "Mataram su ……… .", answer: "dolu" },
    { sentence: "Kalemliğim fermuarlı ……… .", answer: "yapılmış" },
    { sentence: "Sulu boya fırçası ……… .", answer: "yumuşaktı" },
    { sentence: "Kuru boya kutusu ……… .", answer: "kırılmış" },
    { sentence: "Pastel boya ellerimi ……… .", answer: "boyadı" },
    { sentence: "Gazlı kalem kağıttan ……… .", answer: "geçti" },
    { sentence: "Tükenmez kalem ……… .", answer: "mürekkebi bitti" },
    { sentence: "Kurşun kalem ucu ……… .", answer: "kırıldı" },
    { sentence: "Dolma kalem ……… .", answer: "damlattı" },
    { sentence: "Mürekkep şişesi ……… .", answer: "devrildi" },
    { sentence: "Kağıt havlu suyu ……… .", answer: "emdi" },
    { sentence: "Peçete burnumu ……… .", answer: "sildi" },
    { sentence: "Mendil cebimde ……… .", answer: "duruyor" },
    { sentence: "Iszak mendil ferahlık ……… .", answer: "verdi" },
    { sentence: "Pamuk yarayı ……… .", answer: "temizledi" },
    { sentence: "Sargı bezi kolumu ……… .", answer: "sardı" },
    { sentence: "Yara bandı ……… kapattı.", answer: "çiziği" },
    { sentence: "İlaç kutusu ……… .", answer: "açıldı" },
    { sentence: "Şurup şişesi ……… .", answer: "yarımdı" },
    { sentence: "Hap yutmak ……… .", answer: "zordu" },
    { sentence: "İğne acısı ……… .", answer: "geçti" },
    { sentence: "Röntgen filmine ……… .", answer: "baktık" },
    { sentence: "Alçı bacağımı ……… .", answer: "tuttu" },
    { sentence: "Sedyeyle hastayı ……… .", answer: "taşıdılar" },
    { sentence: "Doktor reçete ……… .", answer: "yazdı" },
    { sentence: "Hemşire tansiyon ……… .", answer: "ölçtü" },
    { sentence: "Eczacı ilacı ……… .", answer: "verdi" },
    { sentence: "Hastane bahçesi ……… .", answer: "genişti" },
    { sentence: "Koru ormanı içindeydi ……… .", answer: "evimiz" },
    { sentence: "Köprüden karşıya ……… .", answer: "geçtik" },
    { sentence: "Vapur iskelesi ……… .", answer: "yakındaydı" },
    { sentence: "Havalimanı çok ……… .", answer: "kalabalıktı" },
    { sentence: "Gar garın içinde ……… .", answer: "trenler vardı" },
    { sentence: "Terminal otobüslerle ……… .", answer: "doluydu" },
    { sentence: "Durak boş ……… .", answer: "duruyordu" },
    { sentence: "Meydan çok ……… .", answer: "genişti" },
    { sentence: "Cadde ışıl ışıldı ……… .", answer: "gece" },
    { sentence: "Bulvar boyu ağaçlar ……… .", answer: "sıralıydı" },
    { sentence: "Park çocuklar için ……… .", answer: "güvenliydi" },
    { sentence: "Liman gemilerle ……… .", answer: "doluydu" },
    { sentence: "Rıhtım dalgalarla ……… .", answer: "dövüldü" },
    { sentence: "İskele tahtadan ……… .", answer: "yapılmıştı" },
    { sentence: "Deniz feneri yolu ……… .", answer: "gösteriyordu" },
    { sentence: "Şehir ışıkları ……… .", answer: "söndü" },
    { sentence: "Köy hayatı ……… .", answer: "huzurluydu" },
    { sentence: "Kasaba çarşısı ……… .", answer: "küçüktü" },
    { sentence: "İlçe merkezi ……… .", answer: "uzaktaydı" },
    { sentence: "Vilayet binası ……… .", answer: "görkemliydi" },
    { sentence: "Vali şehri ……… .", answer: "ziyaret etti" },
    { sentence: "Kaymakam okulu ……… .", answer: "açtı" },
    { sentence: "Muhtar köyü ……… .", answer: "yönetiyordu" },
    { sentence: "Belediye başkanı ……… .", answer: "konuştu" },
    { sentence: "Meclis binası ……… .", answer: "Ankara'dadır" },
    { sentence: "Saray çok ……… .", answer: "eskiydi" },
    { sentence: "Kule bulutlara ……… .", answer: "değiyordu" },
    { sentence: "Surlar şehri ……… .", answer: "koruyordu" },
    { sentence: "Hendek suyla ……… .", answer: "doluydu" },
    { sentence: "Sancak dalgalanıyor ……… .", answer: "gökyüzünde" },
    { sentence: "Bayrak töreni ……… .", answer: "yapıldı" },
    { sentence: "İstiklal Marşı ……… .", answer: "okundu" },
    { sentence: "Atatürk'ün ilkeleri ……… .", answer: "rehberimizdir" },
    { sentence: "Cumhuriyet bayramı ……… .", answer: "kutlandı" },
    { sentence: "Zafer bayramı coşku ……… .", answer: "vericiydi" },
    { sentence: "Ramazan bayramı tatlı ……… .", answer: "geçti" },
    { sentence: "Kurban bayramı paylaşmak ……… .", answer: "demektir" },
    { sentence: "Milli bayramlar ……… .", answer: "önemlidir" },
    { sentence: "Dini bayramlar ……… .", answer: "kutsaldır" },
    { sentence: "Tören alanı ……… .", answer: "süslendi" },
    { sentence: "Geçit töreni ……… .", answer: "başladı" },
    { sentence: "Halk oyunları ……… .", answer: "oynandı" },
    { sentence: "Davul zurna ……… .", answer: "çalıyordu" },
    { sentence: "Halay çekildi ……… .", answer: "meydanda" },
    { sentence: "Horon tepildi ……… .", answer: "Karadeniz'de" },
    { sentence: "Zeybek oynandı ……… .", answer: "Ege'de" },
    { sentence: "Bağlama teli ……… .", answer: "koptu" },
    { sentence: "Sazın sapı ……… .", answer: "uzundu" },
    { sentence: "Türkü sözleri ……… .", answer: "hüzünlüydü" },
    { sentence: "Yemek sofrası ……… .", answer: "kuruldu" },
    { sentence: "Düğün dernek ……… .", answer: "kuruldu" },
    { sentence: "Sünnet töreni ……… .", answer: "yapıldı" },
    { sentence: "Nişan yüzüğü ……… .", answer: "takıldı" },
    { sentence: "Kına gecesi ……… .", answer: "eğlenceliydi" },
    { sentence: "Gelinlik bembeyaz ……… .", answer: "parlıyordu" },
    { sentence: "Damatlık siyah ……… .", answer: "takımdı" },
    { sentence: "Düğün pastası ……… .", answer: "kesildi" },
    { sentence: "Takı töreni ……… .", answer: "heyecanlıydı" },
    { sentence: "Davetiye kartı ……… .", answer: "bastırıldı" },
    { sentence: "Zarfın içine ……… .", answer: "konuldu" },
    { sentence: "Pul mektuba ……… .", answer: "yapıştırıldı" },
    { sentence: "Posta kutusu ……… .", answer: "doluydu" },
    { sentence: "E-posta kutusu ……… .", answer: "temizlendi" }
];
