import { BoslukDoldurmaItem } from '../../types/kelimeCumle';

export const BOSLUK_DOLDURMA_SOURCES: BoslukDoldurmaItem[] = [
    { sentence: "Bugün hava çok ……… .", answer: "soğuk" },
    { sentence: "Atatürk 1881 yılında Selanik’te ……… .", answer: "doğdu" },
    { sentence: "Eren sınıfın camını ……… .", answer: "kırdı" },
    { sentence: "Emre hasta ……… .", answer: "oldu" },
    { sentence: "Annem pazardan armut ……… .", answer: "aldı" },
    { sentence: "Emine denizde ……… .", answer: "yüzüyor" },
    { sentence: "Burcu dişlerini ……… .", answer: "fırçaladı" },
    { sentence: "Arzu akşam televizyon ……… .", answer: "seyretti" },
    { sentence: "Çocuklar bahçede top ……… .", answer: "oynadı" },
    { sentence: "Hasan sabah saat 7.30’da ……… .", answer: "uyandı" },
    { sentence: "Ufuk okuldan eve gelince çok ……… .", answer: "çalıştı" },
    { sentence: "Meral yemekten önce ellerini ……… .", answer: "yıkadı" },
    { sentence: "Arı ……… yapar.", answer: "bal" },
    { sentence: "Küçük kedi ……… içti.", answer: "süt" },
    { sentence: "……… ot yiyor.", answer: "Koyunlar" },
    { sentence: "……… uçak kullanıyor.", answer: "Pilot" },
    { sentence: "Osman ……… ile balık tutuyor.", answer: "olta" },
    { sentence: "Tavuklar ve horoz ……… yiyor.", answer: "yem" },
    { sentence: "……… mevsimi çok soğuk.", answer: "Kış" },
    { sentence: "Öğrenciler bayramda sınıfta ……… astı.", answer: "bayrak" },
    { sentence: "Tuvaletten sonra ellerimi ……… .", answer: "yıkarım" },
    { sentence: "İtfaiye ……… söndürdü.", answer: "yangını" },
    { sentence: "Berber ……… kesti.", answer: "saçlarımı" },
    { sentence: "Fatih arabaya ……… .", answer: "bindi" },
    { sentence: "Hakan ……… giydi.", answer: "mont" },
    { sentence: "Salı günü Kemal ve İbrahim ……… etti.", answer: "kavga" },
    { sentence: "Dün akşam eve ……… geldi.", answer: "misafir" },
    { sentence: "Gölde ……… yüzüyor.", answer: "ördekler" },
    { sentence: "Papatya ve güller güzel ……… .", answer: "kokuyor" },
    { sentence: "Bakkaldan ……… aldım.", answer: "çikolata" },
    { sentence: "Bir yıl dört ……… .", answer: "mevsim" },
    { sentence: "Bir yıl 12 ……… .", answer: "ay" },
    { sentence: "Bir yıl 365 ……… .", answer: "gün" },
    { sentence: "Bir hafta ……… gün.", answer: "yedi" },
    { sentence: "Haftanın ilk günü ……… .", answer: "pazartesi" },
    { sentence: "Tatil günleri cumartesi ve ……… .", answer: "pazar" },
    { sentence: "Bir gün 24 ……… .", answer: "saat" },
    { sentence: "……… mevsimi çok sıcak.", answer: "Yaz" },
    { sentence: "Bir ay ……… gün.", answer: "30" },
    { sentence: "……… mevsiminde çiçekler açar.", answer: "İlkbahar" },
    { sentence: "Çocuklar ……… sallanıyor.", answer: "salıncakta" },
    { sentence: "Hayvanat bahçesinde ……… gördüm.", answer: "zürafa" },
    { sentence: "Dedem ……… okuyor.", answer: "gazete" },
    { sentence: "Ablam manavdan ……… aldı.", answer: "çilek" },
    { sentence: "Hatice ……… taze ekmek aldı.", answer: "fırından" },
    { sentence: "……… mutfakta yemek yapıyor.", answer: "Aşçı" },
    { sentence: "Dedem camide ……… kılıyor.", answer: "namaz" },
    { sentence: "……… günü okul tatil.", answer: "Pazar" },
    { sentence: "……… öğrencilere aşı yapıyor.", answer: "Hemşire" },
    { sentence: "Akşam saat ……… uyudum.", answer: "22:00'de" }
];
