import { BoslukDoldurmaItem } from '../../types/kelimeCumle';

export const BOSLUK_DOLDURMA_SOURCES: BoslukDoldurmaItem[] = [
    { sentence: "Bugün hava çok ……… .", answer: "soğuk" },
    { sentence: "Atatürk 1881 yılında Selanik’te ……… .", answer: "doğdu" },
    { sentence: "Eren sınıfın camını ……… .", answer: "kırdı" },
    { sentence: "Emre hasta ……… .", answer: "oldu" },
    { sentence: "Annem pazardan armut ……… .", answer: "aldı" },
    { sentence: "Emine denizde ……… .", answer: "yüzüyor" },
    { sentence: "Burcu dişlerini ……… .", answer: "fırçaladı" },
    { sentence: "Arzu akşam televizyon ……… .", answer: "seyretti" },
    { sentence: "Çocuklar bahçede top ……… .", answer: "oynadı" },
    { sentence: "Hasan sabah saat 7.30’da ……… .", answer: "uyandı" },
    { sentence: "Ufuk okuldan eve gelince çok ……… .", answer: "çalıştı" },
    { sentence: "Meral yemekten önce ellerini ……… .", answer: "yıkadı" },
    { sentence: "Arı ……… yapar.", answer: "bal" },
    { sentence: "Küçük kedi ……… içti.", answer: "süt" },
    { sentence: "……… ot yiyor.", answer: "Koyunlar" },
    { sentence: "……… uçak kullanıyor.", answer: "Pilot" },
    { sentence: "Osman ……… ile balık tutuyor.", answer: "olta" },
    { sentence: "Tavuklar ve horoz ……… yiyor.", answer: "yem" },
    { sentence: "……… mevsimi çok soğuk.", answer: "Kış" },
    { sentence: "Öğrenciler bayramda sınıfta ……… astı.", answer: "bayrak" },
    { sentence: "Tuvaletten sonra ellerimi ……… .", answer: "yıkarım" },
    { sentence: "İtfaiye ……… söndürdü.", answer: "yangını" },
    { sentence: "Berber ……… kesti.", answer: "saçlarımı" },
    { sentence: "Fatih arabaya ……… .", answer: "bindi" },
    { sentence: "Hakan ……… giydi.", answer: "mont" },
    { sentence: "Salı günü Kemal ve İbrahim ……… etti.", answer: "kavga" },
    { sentence: "Dün akşam eve ……… geldi.", answer: "misafir" },
    { sentence: "Gölde ……… yüzüyor.", answer: "ördekler" },
    { sentence: "Papatya ve güller güzel ……… .", answer: "kokuyor" },
    { sentence: "Bakkaldan ……… aldım.", answer: "çikolata" },
    { sentence: "Bir yıl dört ……… .", answer: "mevsim" },
    { sentence: "Bir yıl 12 ……… .", answer: "ay" },
    { sentence: "Bir yıl 365 ……… .", answer: "gün" },
    { sentence: "Bir hafta ……… gün.", answer: "yedi" },
    { sentence: "Haftanın ilk günü ……… .", answer: "pazartesi" },
    { sentence: "Tatil günleri cumartesi ve ……… .", answer: "pazar" },
    { sentence: "Bir gün 24 ……… .", answer: "saat" },
    { sentence: "……… mevsimi çok sıcak.", answer: "Yaz" },
    { sentence: "Bir ay ……… gün.", answer: "30" },
    { sentence: "……… mevsiminde çiçekler açar.", answer: "İlkbahar" },
    { sentence: "Çocuklar ……… sallanıyor.", answer: "salıncakta" },
    { sentence: "Hayvanat bahçesinde ……… gördüm.", answer: "zürafa" },
    { sentence: "Dedem ……… okuyor.", answer: "gazete" },
    { sentence: "Ablam manavdan ……… aldı.", answer: "çilek" },
    { sentence: "Hatice ……… taze ekmek aldı.", answer: "fırından" },
    { sentence: "……… mutfakta yemek yapıyor.", answer: "Aşçı" },
    { sentence: "Dedem camide ……… kılıyor.", answer: "namaz" },
    { sentence: "……… günü okul tatil.", answer: "Pazar" },
    { sentence: "……… öğrencilere aşı yapıyor.", answer: "Hemşire" },
    { sentence: "Akşam saat ……… uyudum.", answer: "22:00'de" },
    { sentence: "Okula gitmek için ……… bindim.", answer: "servise" },
    { sentence: "Öğretmenimiz tahtaya ……… yazdı.", answer: "yazı" },
    { sentence: "Ali çantasından ……… çıkardı.", answer: "kalemini" },
    { sentence: "Yemekten sonra ……… fırçalamalıyız.", answer: "dişlerimizi" },
    { sentence: "Pazardan taze ……… ve sebze aldık.", answer: "meyve" },
    { sentence: "Kardeşim oyuncağını ……… .", answer: "kırdı" },
    { sentence: "Gökyüzünde parlak ……… var.", answer: "güneş" },
    { sentence: "Balıklar ……… içinde yüzer.", answer: "suyun" },
    { sentence: "Kuşlar kanatlarını çırparak ……… .", answer: "uçar" },
    { sentence: "Araba ……… durdu.", answer: "kırmızı ışıkta" },
    { sentence: "Dedem bahçedeki çiçekleri ……… .", answer: "suladı" },
    { sentence: "Manavdan üç kilo ……… aldım.", answer: "elma" },
    { sentence: "Sobanın içinde ……… yanıyor.", answer: "odunlar" },
    { sentence: "Tavşan havuç ……… çok sever.", answer: "yemeyi" },
    { sentence: "Annem mutfakta lezzetli bir ……… yaptı.", answer: "kek" },
    { sentence: "Okulda teneffüs zili ……… .", answer: "çaldı" },
    { sentence: "Yağmur yağınca ……… açtık.", answer: "şemsiyemizi" },
    { sentence: "Dün gece rüyamda ……… gördüm.", answer: "devler" },
    { sentence: "Sınıfın duvarına ……… astık.", answer: "harita" },
    { sentence: "Kışın kalın ……… giymeliyiz.", answer: "kazaklar" },
    { sentence: "Deniz kıyısında ……… topladık.", answer: "deniz kabuğu" },
    { sentence: "Fatih bugün okula ……… geldi.", answer: "geç" },
    { sentence: "Meral ödevlerini ……… bitirdi.", answer: "vaktinde" },
    { sentence: "Babam bana yeni bir ……… aldı.", answer: "bisiklet" },
    { sentence: "Kayıp kedimizi ……… bulduk.", answer: "bahçede" },
    { sentence: "Sobanın üstünde ……… kaynıyor.", answer: "çaydanlık" },
    { sentence: "Öğle yemeğinde ……… içtik.", answer: "ayran" },
    { sentence: "Bahçedeki ağaçtan ……… topladık.", answer: "erik" },
    { sentence: "Ali sabah erkenden ……… .", answer: "kalktı" },
    { sentence: "Ayşe piyano ……… öğreniyor.", answer: "çalmayı" },
    { sentence: "Kamyon yolda ……… kaldı.", answer: "yolda" },
    { sentence: "Postacı bize ……… getirdi.", answer: "mektup" },
    { sentence: "Gözlüklerimi ……… unutmuşum.", answer: "evde" },
    { sentence: "Piknikte ……… oynadık.", answer: "yakantop" },
    { sentence: "Annem pazardan ……… aldı.", answer: "taze fasulye" },
    { sentence: "Sokak lambaları ……… yanar.", answer: "akşam" },
    { sentence: "Dizim kanayınca ……… yapıştırdık.", answer: "yara bandı" },
    { sentence: "Müzayede evinde eski ……… satıldı.", answer: "tablolar" },
    { sentence: "Kütüphanede sessizce ……… okuduk.", answer: "kitap" },
    { sentence: "Yaz tatilinde ……… yüzmeye gideceğiz.", answer: "denize" },
    { sentence: "Ablam üniversitede ……… okuyor.", answer: "tıp" },
    { sentence: "Dolabın içinden temiz ……… aldım.", answer: "çoraplar" },
    { sentence: "Çiftlikte ……… sağılıyor.", answer: "inekler" },
    { sentence: "Aslan ormanın ……… .", answer: "kralıdır" },
    { sentence: "Kelebekler ……… üstüne kondu.", answer: "çiçeklerin" },
    { sentence: "Ablam saçlarını ……… ördü.", answer: "iki yandan" },
    { sentence: "Babam arabayı ……… yıkadı.", answer: "fırçayla" },
    { sentence: "Meyveleri yemeden önce ……… .", answer: "yıkamalıyız" },
    { sentence: "Güneş doğudan ……… .", answer: "doğar" },
    { sentence: "Ay geceleri gökyüzünde ……… .", answer: "parlar" },
    { sentence: "Kurbağalar gölde ……… .", answer: "zıplar" },
    { sentence: "Zürafa çok uzun bir ……… sahiptir.", answer: "boyna" },
    { sentence: "Fil hortumuyla ……… içer.", answer: "su" },
    { sentence: "Maymunlar ağaçtan ağaca ……… .", answer: "atlar" },
    { sentence: "Kaplumbağa çok ……… yürür.", answer: "yavaş" },
    { sentence: "Tavşanlar çok ……… koşar.", answer: "hızlı" },
    { sentence: "Arılar çiçeklerden ……… toplar.", answer: "öz" },
    { sentence: "Karıncalar kış için ……… biriktirir.", answer: "yiyecek" },
    { sentence: "Yılanlar yerde ……… ilerler.", answer: "sürünerek" },
    { sentence: "Yunuslar denizde ……… yapar.", answer: "gösteri" },
    { sentence: "Balina dünyanın en büyük ……… .", answer: "hayvanıdır" },
    { sentence: "Öğretmenimiz bize ……… anlattı.", answer: "masal" },
    { sentence: "Okul çantam çok ……… olmuş.", answer: "ağır" },
    { sentence: "Defterime ……… ile resim çizdim.", answer: "boya kalemleri" },
    { sentence: "Masamın üstünde ……… duruyor.", answer: "lambam" },
    { sentence: "Sabah kahvaltısında ……… yedim.", answer: "yumurta" },
    { sentence: "Akşam yemeğinde ……… var.", answer: "makarna" },
    { sentence: "Susam Sokağı'nı ……… çok severdim.", answer: "izlemeyi" },
    { sentence: "Atatürk'ün mezarı ……… .", answer: "Anıtkabir'dedir" },
    { sentence: "Türkiye'nin başkenti ……… .", answer: "Ankara'dır" },
    { sentence: "İstanbul'da tarihi ……… çoktur.", answer: "camiler" },
    { sentence: "Karadeniz'de ……… çok yağar.", answer: "yağmur" },
    { sentence: "Antalya'da yazlar çok ……… geçer.", answer: "sıcak" },
    { sentence: "Erzurum'da kışın çok ……… yağar.", answer: "kar" },
    { sentence: "İzmir'in ……… meşhurdur.", answer: "boyozu" },
    { sentence: "Bursa'nın ……… tadı damakta kalır.", answer: "iskenderi" },
    { sentence: "Hafta içi ……… okula gideriz.", answer: "beş gün" },
    { sentence: "Hafta sonu Cumartesi ve ……… .", answer: "Pazar'dır" },
    { sentence: "Yarın hava ……… olacakmış.", answer: "güneşli" },
    { sentence: "Bugün kendimi çok ……… hissediyorum.", answer: "mutlu" },
    { sentence: "Arkadaşım bana ……… verdi.", answer: "ödevini" },
    { sentence: "Teneffüste ……… oynadık.", answer: "saklambaç" },
    { sentence: "Kitap okumak ……… geliştirir.", answer: "hayal gücünü" },
    { sentence: "Bisiklete binerken ……… takmalıyız.", answer: "kask" },
    { sentence: "Denizde yüzerken ……… dikkat etmeliyiz.", answer: "dalgalara" },
    { sentence: "Ormanda piknik yaparken ……… yakmamalıyız.", answer: "ateş" },
    { sentence: "Çevremizi temiz ……… korumalıyız.", answer: "tutarak" },
    { sentence: "Ağaçlar havayı ……… .", answer: "temizler" },
    { sentence: "Geri dönüşüm doğayı ……… .", answer: "korur" },
    { sentence: "Hayvanlara sevgiyle ……… .", answer: "yaklaşmalıyız" },
    { sentence: "Yaşlılara yardım ……… .", answer: "etmeliyiz" },
    { sentence: "Otobüste hamilelere ……… vermeliyiz.", answer: "yer" },
    { sentence: "Trafik kurallarına ……… hayat kurtarır.", answer: "uymak" },
    { sentence: "Yalancının mumu ……… kadar yanar.", answer: "yatsıya" },
    { sentence: "Damlaya damlaya ……… olur.", answer: "göl" },
    { sentence: "Gözden ırak olan ……… de ırak olur.", answer: "gönülden" },
    { sentence: "Gülme komşuna ……… başına.", answer: "gelir" },
    { sentence: "Sakla samanı ……… zamanı.", answer: "gelir" },
    { sentence: "İyilik yap ……… at.", answer: "denize" },
    { sentence: "Meyve veren ağaç ……… .", answer: "taşlanır" },
    { sentence: "Bakarsan bağ, bakmazsan ……… olur.", answer: "dağ" },
    { sentence: "Aslan yattığı ……… belli olur.", answer: "yerden" },
    { sentence: "Akıl akıldan ……… .", answer: "üstündür" },
    { sentence: "Bir elin nesi var, ……… sesi var.", answer: "iki elin" },
    { sentence: "Birlikten ……… doğar.", answer: "kuvvet" },
    { sentence: "Çalışan demir ……… .", answer: "ışıldayacak" },
    { sentence: "Tatlı dil ……… deliğinden çıkarır.", answer: "yılanı" },
    { sentence: "Komşu komşunun ……… muhtaçtır.", answer: "külüne" },
    { sentence: "Zahmetsiz ……… olmaz.", answer: "rahmet" },
    { sentence: "Görünen köy ……… istemez.", answer: "kılavuz" },
    { sentence: "Ayağını yorganına göre ……… .", answer: "uzat" },
    { sentence: "Keskin sirke ……… zarar.", answer: "küpüne" },
    { sentence: "Rüzgar eken ……… biçer.", answer: "fırtına" },
    { sentence: "Sütten ağzı yanan ……… üfleyerek yer.", answer: "yoğurdu" },
    { sentence: "Ateş olmayan yerden ……… çıkmaz.", answer: "duman" },
    { sentence: "Bugünün işini ……… bırakma.", answer: "yarına" },
    { sentence: "Akıl yaşta değil ……… .", answer: "baştadır" },
    { sentence: "Altın eşik ……… eşiğe muhtaçtır.", answer: "gümüş" },
    { sentence: "Bal tutan parmağını ……… .", answer: "yalar" },
    { sentence: "Besle kargayı ……… gözünü.", answer: "oysun" },
    { sentence: "Can boğazdan ……… .", answer: "gelir" },
    { sentence: "Dost kara günde ……… olur.", answer: "belli" },
    { sentence: "Emek olmadan ……… olmaz.", answer: "yemek" },
    { sentence: "Evdeki hesap ……… uymaz.", answer: "çarşıya" },
    { sentence: "Göz görmeyince ……… katlanır.", answer: "gönül" },
    { sentence: "İşleyen demir pas ……… .", answer: "tutmaz" },
    { sentence: "Kaçan balık ……… olur.", answer: "büyük" },
    { sentence: "Kurt kocayınca ……… maskarası olur.", answer: "köpeklerin" },
    { sentence: "Ne ekersen ……… biçersin.", answer: "onu" },
    { sentence: "Öfke ile kalkan ……… oturur.", answer: "zararla" },
    { sentence: "Sabreden derviş ……… ermiş.", answer: "muradına" },
    { sentence: "Yalancının mumu yatsıya kadar ……… .", answer: "yanar" },
    { sentence: "Zaman nakittir ……… .", answer: "" },
    { sentence: "Kardeşim bugün parkta ……… .", answer: "oynadı" },
    { sentence: "Annem pazardan ……… aldı.", answer: "domates" },
    { sentence: "Babam bana yeni ……… aldı.", answer: "ayakkabı" },
    { sentence: "Öğretmenimiz bize ……… yazdırdı.", answer: "şiir" },
    { sentence: "Dün akşam çok ……… yağdı.", answer: "yağmur" },
    { sentence: "Sınıfın camı ……… .", answer: "kırıldı" },
    { sentence: "Kedim mırıl mırıl ……… .", answer: "uyuyor" },
    { sentence: "Köpeğim bahçede ……… .", answer: "koşuyor" },
    { sentence: "Kuşlar ağaçta ……… .", answer: "ötüyor" },
    { sentence: "Çiçekler saksıda ……… .", answer: "büyüyor" },
    { sentence: "Güneş tepeden ……… .", answer: "parlıyor" },
    { sentence: "Ay geceleri ……… .", answer: "doğuyor" },
    { sentence: "Yıldızlar gökyüzünde ……… .", answer: "titriyor" },
    { sentence: "Bulutlar gökyüzünde ……… .", answer: "yüzüyor" },
    { sentence: "Rüzgar sert ……… .", answer: "esiyor" },
    { sentence: "Kar her yeri ……… .", answer: "kapladı" },
    { sentence: "Dolu camlara ……… .", answer: "vuruyor" },
    { sentence: "Şimşek birden ……… .", answer: "çaktı" },
    { sentence: "Gök gürültüsü ……… .", answer: "korkuttu" },
    { sentence: "Gökkuşağı çok ……… .", answer: "renkli" },
    { sentence: "Deniz masmavi ……… .", answer: "görünüyor" },
    { sentence: "Kumlar çok ……… .", answer: "sıcak" },
    { sentence: "Taşlar yolda ……… .", answer: "duruyor" },
    { sentence: "Ağaçlar ormanda ……… .", answer: "sıralı" },
    { sentence: "Orman çok ……… .", answer: "koyu" },
    { sentence: "Dağlar çok ……… .", answer: "yüksek" },
    { sentence: "Ova çok ……… .", answer: "geniş" },
    { sentence: "Nehir hızlı ……… .", answer: "akıyor" },
    { sentence: "Göl durgun ……… .", answer: "duruyor" },
    { sentence: "Şelale coşkuyla ……… .", answer: "çağlıyor" },
    { sentence: "Mağara karanlık ……… .", answer: "görünüyor" },
    { sentence: "Yol uzun ……… .", answer: "sürüyor" },
    { sentence: "Köprü nehri ……… .", answer: "bağlıyor" },
    { sentence: "Tünel dağın içinden ……… .", answer: "geçiyor" },
    { sentence: "Sokak sessiz ……… .", answer: "duruyor" },
    { sentence: "Evimiz sıcak ……… .", answer: "oldu" },
    { sentence: "Bahçemiz yeşil ……… .", answer: "kaldı" },
    { sentence: "Okulumuz büyük ……… .", answer: "yapıldı" },
    { sentence: "Sınıfımız aydınlık ……… .", answer: "oldu" },
    { sentence: "Masamız sağlam ……… .", answer: "duruyor" },
    { sentence: "Sandalyemiz rahat ……… .", answer: "oldu" },
    { sentence: "Dolabımız düzenli ……… .", answer: "kaldı" },
    { sentence: "Yatağımız yumuşak ……… .", answer: "oldu" },
    { sentence: "Yastığımız kabarık ……… .", answer: "yapılmış" },
    { sentence: "Yorganımız kalın ……… .", answer: "oldu" },
    { sentence: "Halı yumuşak ……… .", answer: "duruyor" },
    { sentence: "Perdemiz beyaz ……… .", answer: "kaldı" },
    { sentence: "Lambamız parlak ……… .", answer: "yanıyor" },
    { sentence: "Televizyon sesli ……… .", answer: "çalışıyor" },
    { sentence: "Bilgisayar hızlı ……… .", answer: "açılıyor" },
    { sentence: "Telefon ince ……… .", answer: "yapılmış" },
    { sentence: "Saat doğru ……… .", answer: "işliyor" },
    { sentence: "Ayna parlak ……… .", answer: "duruyor" },
    { sentence: "Tarak ince ……… .", answer: "yapılmış" },
    { sentence: "Sabun mis ……… .", answer: "kokuyor" },
    { sentence: "Şampuan köpüklü ……… .", answer: "oldu" },
    { sentence: "Havlu kuru ……… .", answer: "kaldı" },
    { sentence: "Fırça sert ……… .", answer: "oldu" },
    { sentence: "Macun beyaz ……… .", answer: "görünüyor" },
    { sentence: "Bardak cam ……… .", answer: "yapılmış" },
    { sentence: "Tabak seramik ……… .", answer: "oldu" },
    { sentence: "Kaşık metal ……… .", answer: "yapılmış" },
    { sentence: "Çatal sivri ……… .", answer: "oldu" },
    { sentence: "Bıçak keskin ……… .", answer: "oldu" },
    { sentence: "Tencere sıcak ……… .", answer: "oldu" },
    { sentence: "Tava yağlı ……… .", answer: "kaldı" },
    { sentence: "Süzgeç delikli ……… .", answer: "yapılmış" },
    { sentence: "Rende tırtıklı ……… .", answer: "oldu" },
    { sentence: "Masa örtüsü ……… .", answer: "serildi" },
    { sentence: "Mutfak temiz ……… .", answer: "kaldı" },
    { sentence: "Antre dar ……… .", answer: "görünüyor" },
    { sentence: "Koridor uzun ……… .", answer: "yapılmış" },
    { sentence: "Balkon havadar ……… .", answer: "oldu" },
    { sentence: "Çatı dik ……… .", answer: "yapıldı" },
    { sentence: "Baca tüter ……… .", answer: "duruyor" },
    { sentence: "Kapı kapalı ……… .", answer: "kaldı" },
    { sentence: "Pencere açık ……… .", answer: "duruyor" },
    { sentence: "Bahçe kapısı ……… .", answer: "kilitlendi" },
    { sentence: "Garaj kapısı ……… .", answer: "kapandı" },
    { sentence: "Zil yüksek ……… .", answer: "çaldı" },
    { sentence: "Anahtar demir ……… .", answer: "yapılmış" },
    { sentence: "Kilit sağlam ……… .", answer: "oldu" },
    { sentence: "Çanta deri ……… .", answer: "yapılmış" },
    { sentence: "Cüzdan para ……… .", answer: "dolu" },
    { sentence: "Kemer siyah ……… .", answer: "oldu" },
    { sentence: "Şapka bordo ……… .", answer: "kaldı" },
    { sentence: "Eldiven yün ……… .", answer: "yapılmış" },
    { sentence: "Atkı örgü ……… .", answer: "yapıldı" },
    { sentence: "Çorap delik ……… .", answer: "oldu" },
    { sentence: "Pabuç yeni ……… .", answer: "alındı" },
    { sentence: "Çizme uzun ……… .", answer: "duruyor" },
    { sentence: "Sandalet hafif ……… .", answer: "oldu" },
    { sentence: "Terlik rahat ……… .", answer: "yapılmış" },
    { sentence: "Gözlük camı ……… .", answer: "kırıldı" },
    { sentence: "Saat kordonu ……… .", answer: "koptu" },
    { sentence: "Yüzük altın ……… .", answer: "yapılmış" },
    { sentence: "Küpe parlak ……… .", answer: "görünüyor" },
    { sentence: "Kolye inci ……… .", answer: "dizili" },
    { sentence: "Bilezik gümüş ……… .", answer: "yapıldı" },
    { sentence: "Toka çiçekli ……… .", answer: "oldu" },
    { sentence: "Parfüm hoş ……… .", answer: "kokuyor" }
];
