import { KarisikCumleItem } from '../../types/kelimeCumle';

export const KARISIK_CUMLE_SOURCES: KarisikCumleItem[] = [
    { words: ["saat", "Kemal", "7.00 de", "sabah", "uyandı"], correctSentence: "Kemal sabah saat 7.00’de uyandı." },
    { words: ["Ömer", "yemek", "Yedi"], correctSentence: "Ömer yemek yedi." },
    { words: ["ve", "Hasan", "resim", "Ayşe", "güzel", "yapıyor"], correctSentence: "Hasan ve Ayşe güzel resim yapıyor." },
    { words: ["günü", "oynadı", "Hasan", "top", "pazar"], correctSentence: "Hasan pazar günü top oynadı." },
    { words: ["aldı", "çikolata", "bakkaldan", "iki", "Ahmet"], correctSentence: "Ahmet bakkaldan iki çikolata aldı." },
    { words: ["koydu", "Anne", "çatal", "masaya"], correctSentence: "Anne masaya çatal koydu." },
    { words: ["mutfakta", "yapıyor", "Ayşe", "yemek"], correctSentence: "Ayşe mutfakta yemek yapıyor." },
    { words: ["dinliyor", "müzik", "İbrahim"], correctSentence: "İbrahim müzik dinliyor." },
    { words: ["bahçede", "uçuruyor", "Mustafa", "uçurtma"], correctSentence: "Mustafa bahçede uçurtma uçuruyor." },
    { words: ["verdi", "Yasemin", "yem", "tavuklara"], correctSentence: "Yasemin tavuklara yem verdi." },
    { words: ["duman", "Evin", "çıkıyor", "bacasından"], correctSentence: "Evin bacasından duman çıkıyor." },
    { words: ["yardım", "Zeynep", "ediyor", "annesine"], correctSentence: "Zeynep annesine yardım ediyor." },
    { words: ["ve", "kardeşim", "sinemaya", "gittik", "Ben"], correctSentence: "Ben ve kardeşim sinemaya gittik." },
    { words: ["saat", "Ramazan", "22.00’ de", "akşam", "uyudu"], correctSentence: "Ramazan akşam saat 22.00’de uyudu." },
    { words: ["olta", "Ben", "ile", "balık", "tuttum"], correctSentence: "Ben olta ile balık tuttum." },
    { words: ["hastaneye", "gittim", "Ben", "bugün"], correctSentence: "Ben bugün hastaneye gittim." },
    { words: ["seyretti", "Hüseyin", "akşam", "televizyon"], correctSentence: "Hüseyin akşam televizyon seyretti." },
    { words: ["süt", "bugün", "içtik", "okulda", "Biz"], correctSentence: "Biz bugün okulda süt içtik." },
    { words: ["okuyor", "gazete", "Dedem"], correctSentence: "Dedem gazete okuyor." },
    { words: ["içti", "Öğretmen", "maden suyu"], correctSentence: "Öğretmen maden suyu içti." },
    { words: ["yaptı", "Kerem", "ödevini", "doğru"], correctSentence: "Kerem ödevini doğru yaptı." },
    { words: ["kırmızı", "Rabia", "yedi", "elma"], correctSentence: "Rabia kırmızı elma yedi." },
    { words: ["bahçede", "oynuyor", "top", "Öğrenciler"], correctSentence: "Öğrenciler bahçede top oynuyor." },
    { words: ["bana", "Annem", "verdi", "hediye"], correctSentence: "Annem bana hediye verdi." },
    { words: ["Sertaç", "verdi", "öğrencilere", "süt"], correctSentence: "Sertaç öğrencilere süt verdi." },
    { words: ["anlattı", "ders", "sınıfta", "Öğretmen"], correctSentence: "Öğretmen sınıfta ders anlattı." },
    { words: ["yedi", "köpek", "kemik"], correctSentence: "Köpek kemik yedi." },
    { words: ["soğuk", "içti", "Ayşe", "su"], correctSentence: "Ayşe soğuk su içti." },
    { words: ["aldı", "Anne", "portakal", "pazardan"], correctSentence: "Anne pazardan portakal aldı." },
    { words: ["yüzüyor", "balıklar", "Gölde"], correctSentence: "Gölde balıklar yüzüyor." },
    { words: ["ve", "Kemal", "Eren", "etti", "kavga"], correctSentence: "Kemal ve Eren kavga etti." },
    { words: ["Ali", "okula", "geç", "kaldı"], correctSentence: "Ali okula geç kaldı." },
    { words: ["Babam", "pazardan", "elma", "aldı"], correctSentence: "Babam pazardan elma aldı." },
    { words: ["Ayşe", "kitap", "okumayı", "seviyor"], correctSentence: "Ayşe kitap okumayı seviyor." },
    { words: ["Kardeşim", "parkta", "top", "oynuyor"], correctSentence: "Kardeşim parkta top oynuyor." },
    { words: ["Hava", "bugün", "çok", "soğuk"], correctSentence: "Hava bugün çok soğuk." },
    { words: ["Annem", "pasta", "yaptı"], correctSentence: "Annem pasta yaptı." },
    { words: ["Köpeğim", "bahçede", "koşuyor"], correctSentence: "Köpeğim bahçede koşuyor." },
    { words: ["Kuşlar", "gökyüzünde", "uçuyor"], correctSentence: "Kuşlar gökyüzünde uçuyor." },
    { words: ["Sınıfımızda", "yeni", "bir", "arkadaş", "var"], correctSentence: "Sınıfımızda yeni bir arkadaş var." },
    { words: ["Öğretmenimiz", "ödev", "verdi"], correctSentence: "Öğretmenimiz ödev verdi." },
    { words: ["Sabah", "erkenden", "uyandım"], correctSentence: "Sabah erkenden uyandım." },
    { words: ["Dişlerimi", "her gün", "fırçalarım"], correctSentence: "Dişlerimi her gün fırçalarım." },
    { words: ["Okula", "servis", "ile", "gidiyorum"], correctSentence: "Okula servis ile gidiyorum." },
    { words: ["Kışın", "kar", "yağar"], correctSentence: "Kışın kar yağar." },
    { words: ["Yazın", "denizde", "yüzeriz"], correctSentence: "Yazın denizde yüzeriz." },
    { words: ["Çiçekler", "ilkbaharda", "açar"], correctSentence: "Çiçekler ilkbaharda açar." },
    { words: ["Sonbaharda", "yapraklar", "sararır"], correctSentence: "Sonbaharda yapraklar sararır." },
    { words: ["Kedim", "süt", "içmeyi", "sever"], correctSentence: "Kedim süt içmeyi sever." },
    { words: ["Babam", "işten", "eve", "geldi"], correctSentence: "Babam işten eve geldi." },
    { words: ["Akşam", "yemeğinde", "makarna", "var"], correctSentence: "Akşam yemeğinde makarna var." },
    { words: ["Televizyonda", "çizgi film", "izledim"], correctSentence: "Televizyonda çizgi film izledim." },
    { words: ["Bilgisayarda", "oyun", "oynadım"], correctSentence: "Bilgisayarda oyun oynadım." },
    { words: ["Kitaplarımı", "çantama", "koydum"], correctSentence: "Kitaplarımı çantama koydum." },
    { words: ["Resim", "yapmayı", "çok", "seviyorum"], correctSentence: "Resim yapmayı çok seviyorum." },
    { words: ["Arkadaşımla", "oyuncaklarımı", "paylaşırım"], correctSentence: "Arkadaşımla oyuncaklarımı paylaşırım." },
    { words: ["Bahçedeki", "ağaçtan", "erik", "topladık"], correctSentence: "Bahçedeki ağaçtan erik topladık." },
    { words: ["Dün", "gece", "rüya", "gördüm"], correctSentence: "Dün gece rüya gördüm." },
    { words: ["Anneannem", "bana", "kazak", "ördü"], correctSentence: "Anneannem bana kazak ördü." },
    { words: ["Dedem", "gazete", "okumayı", "sever"], correctSentence: "Dedem gazete okumayı sever." },
    { words: ["Abim", "bisiklete", "binmeyi", "öğretti"], correctSentence: "Abim bisiklete binmeyi öğretti." },
    { words: ["Sokakta", "yavru", "bir", "kedi", "bulduk"], correctSentence: "Sokakta yavru bir kedi bulduk." },
    { words: ["Ellerimi", "sabunla", "yıkadım"], correctSentence: "Ellerimi sabunla yıkadım." },
    { words: ["Banyodan", "sonra", "bornozumu", "giydim"], correctSentence: "Banyodan sonra bornozumu giydim." },
    { words: ["Pikniğe", "gitmek", "için", "hazırlandık"], correctSentence: "Pikniğe gitmek için hazırlandık." },
    { words: ["Hava", "kararınca", "eve", "döndük"], correctSentence: "Hava kararınca eve döndük." },
    { words: ["Yıldızlar", "gece", "parlıyor"], correctSentence: "Yıldızlar gece parlıyor." },
    { words: ["Ay", "gökyüzünde", "yükseldi"], correctSentence: "Ay gökyüzünde yükseldi." },
    { words: ["Güneş", "doğudan", "doğar"], correctSentence: "Güneş doğudan doğar." },
    { words: ["Yağmur", "yağınca", "şemsiye", "açtık"], correctSentence: "Yağmur yağınca şemsiye açtık." },
    { words: ["Rüzgar", "sert", "esiyor"], correctSentence: "Rüzgar sert esiyor." },
    { words: ["Kar", "her", "yeri", "beyaza", "boyadı"], correctSentence: "Kar her yeri beyaza boyadı." },
    { words: ["Tavşan", "havuç", "yemeyi", "sever"], correctSentence: "Tavşan havuç yemeyi sever." },
    { words: ["Filin", "hortumu", "çok", "uzundur"], correctSentence: "Filin hortumu çok uzundur." },
    { words: ["Zürafa", "uzun", "boyunlu", "bir", "hayvandır"], correctSentence: "Zürafa uzun boyunlu bir hayvandır." },
    { words: ["Arılar", "bal", "yapar"], correctSentence: "Arılar bal yapar." },
    { words: ["Kelebekler", "çiçeklere", "konar"], correctSentence: "Kelebekler çiçeklere konar." },
    { words: ["Karıncalar", "çok", "çalışkandır"], correctSentence: "Karıncalar çok çalışkandır." },
    { words: ["Örümcek", "ağ", "yapar"], correctSentence: "Örümcek ağ yapar." },
    { words: ["Balıklar", "suyun", "altında", "yaşar"], correctSentence: "Balıklar suyun altında yaşar." },
    { words: ["Kaplumbağa", "yavaş", "yürür"], correctSentence: "Kaplumbağa yavaş yürür." },
    { words: ["Atlar", "çok", "hızlı", "koşar"], correctSentence: "Atlar çok hızlı koşar." },
    { words: ["Aslan", "ormanların", "kralıdır"], correctSentence: "Aslan ormanların kralıdır." },
    { words: ["Maymunlar", "muz", "yer"], correctSentence: "Maymunlar muz yer." },
    { words: ["İnekler", "bize", "süt", "verir"], correctSentence: "İnekler bize süt verir." },
    { words: ["Tavuklar", "yumurta", "verir"], correctSentence: "Tavuklar yumurta verir." },
    { words: ["Koyunların", "yünü", "yumuşaktır"], correctSentence: "Koyunların yünü yumuşaktır." },
    { words: ["Ördekler", "gölde", "yüzüyor"], correctSentence: "Ördekler gölde yüzüyor." },
    { words: ["Kuşlar", "yuva", "yapar"], correctSentence: "Kuşlar yuva yapar." },
    { words: ["Civcivler", "babamın", "peşinden", "koşuyor"], correctSentence: "Civcivler babamın peşinden koşuyor." },
    { words: ["Araba", "yolda", "hızlı", "gidiyor"], correctSentence: "Araba yolda hızlı gidiyor." },
    { words: ["Bisikletim", "çok", "güzel"], correctSentence: "Bisikletim çok güzel." },
    { words: ["Patinaj", "yapmak", "eğlencelidir"], correctSentence: "Patinaj yapmak eğlencelidir." },
    { words: ["Kaydıraktan", "kaymayı", "seviyorum"], correctSentence: "Kaydıraktan kaymayı seviyorum." },
    { words: ["Salıncakta", "sallanmak", "dinlendiricidir"], correctSentence: "Salıncakta sallanmak dinlendiricidir." },
    { words: ["Uçurtmam", "göklere", "çıktı"], correctSentence: "Uçurtmam göklere çıktı." },
    { words: ["Balonum", "patladı", "diye", "ağladım"], correctSentence: "Balonum patladı diye ağladım." },
    { words: ["Oyuncaklarım", "odamda", "duruyor"], correctSentence: "Oyuncaklarım odamda duruyor." },
    { words: ["Kitaplığım", "kitap", "dolu"], correctSentence: "Kitaplığım kitap dolu." },
    { words: ["Masamın", "üstü", "çok", "dağınık"], correctSentence: "Masamın üstü çok dağınık." },
    { words: ["Kalemliğimde", "renkli", "kalemlerim", "var"], correctSentence: "Kalemliğimde renkli kalemlerim var." },
    { words: ["Defterime", "yazı", "yazdım"], correctSentence: "Defterime yazı yazdım." },
    { words: ["Müzik", "dinlemeyi", "severim"], correctSentence: "Müzik dinlemeyi severim." },
    { words: ["Şarkı", "söylemek", "beni", "mutlu", "eder"], correctSentence: "Şarkı söylemek beni mutlu eder." },
    { words: ["Dans", "etmeyi", "öğreniyorum"], correctSentence: "Dans etmeyi öğreniyorum." },
    { words: ["Yazın", "dondurma", "yeriz"], correctSentence: "Yazın dondurma yeriz." },
    { words: ["Karpuz", "yazın", "en", "sevdiğim", "meyvedir"], correctSentence: "Karpuz yazın en sevdiğim meyvedir." },
    { words: ["Okul", "başlayınca", "erken", "kalkacağız"], correctSentence: "Okul başlayınca erken kalkacağız." },
    { words: ["Tatil", "bitince", "arkadaşlarımı", "göreceğim"], correctSentence: "Tatil bitince arkadaşlarımı göreceğim." },
    { words: ["Öğretmenimizi", "çok", "özledik"], correctSentence: "Öğretmenimizi çok özledik." },
    { words: ["Yeni", "çantamı", "çok", "beğendim"], correctSentence: "Yeni çantamı çok beğendim." },
    { words: ["Ayakkabılarım", "ayağımı", "sıktı"], correctSentence: "Ayakkabılarım ayağımı sıktı." },
    { words: ["Gözlüklerimi", "evde", "unutmuşum"], correctSentence: "Gözlüklerimi evde unutmuşum." },
    { words: ["Saat", "dokuzda", "yatmalıyım"], correctSentence: "Saat dokuzda yatmalıyım." },
    { words: ["Sabahları", "süt", "içerim"], correctSentence: "Sabahları süt içerim." },
    { words: ["Yumurta", "sağlıklıdır"], correctSentence: "Yumurta sağlıklıdır." },
    { words: ["Zeytin", "ve", "peynir", "yedim"], correctSentence: "Zeytin ve peynir yedim." },
    { words: ["Bal", "tatlıdır"], correctSentence: "Bal tatlıdır." },
    { words: ["Reçel", "çilekten", "yapılır"], correctSentence: "Reçel çilekten yapılır." },
    { words: ["Ekmek", "taze", "olsun"], correctSentence: "Ekmek taze olsun." },
    { words: ["Su", "içmek", "yararlıdır"], correctSentence: "Su içmek yararlıdır." },
    { words: ["Meyve", "suyu", "vitamin", "deposudur"], correctSentence: "Meyve suyu vitamin deposudur." },
    { words: ["Çorba", "sıcak", "içilir"], correctSentence: "Çorba sıcak içilir." },
    { words: ["Salata", "renkli", "görünüyor"], correctSentence: "Salata renkli görünüyor." },
    { words: ["Pilavı", "kaşıkla", "yerim"], correctSentence: "Pilavı kaşıkla yerim." },
    { words: ["Eti", "bıçakla", "keseriz"], correctSentence: "Eti bıçakla keseriz." },
    { words: ["Patates", "kızartmasını", "severim"], correctSentence: "Patates kızartmasını severim." },
    { words: ["Ispanak", "güç", "verir"], correctSentence: "Ispanak güç verir." },
    { words: ["Havuç", "göze", "iyidir"], correctSentence: "Havuç göze iyidir." },
    { words: ["Elma", "en", "sevdiğim", "meyvedir"], correctSentence: "Elma en sevdiğim meyvedir." },
    { words: ["Çilek", "mis", "gibi", "kokuyor"], correctSentence: "Çilek mis gibi kokuyor." },
    { words: ["Muz", "yumuşak", "bir", "meyvedir"], correctSentence: "Muz yumuşak bir meyvedir." },
    { words: ["Üzüm", "tatlıdır"], correctSentence: "Üzüm tatlıdır." },
    { words: ["Erik", "ekşidir"], correctSentence: "Erik ekşidir." },
    { words: ["Limon", "çok", "sarıdır"], correctSentence: "Limon çok sarıdır." },
    { words: ["Portakal", "vitaminli", "bir", "meyvedir"], correctSentence: "Portakal vitaminli bir meyvedir." },
    { words: ["Mandalina", "kolay", "soyulur"], correctSentence: "Mandalina kolay soyulur." },
    { words: ["Kirazı", "yazın", "yeriz"], correctSentence: "Kirazı yazın yeriz." },
    { words: ["Vişne", "suyu", "kırmızıdır"], correctSentence: "Vişne suyu kırmızıdır." },
    { words: ["Kayısı", "turuncu", "renklidir"], correctSentence: "Kayısı turuncu renklidir." },
    { words: ["Şeftali", "tüylüdür"], correctSentence: "Şeftali tüylüdür." },
    { words: ["Kavun", "mis", "gibi", "kokar"], correctSentence: "Kavun mis gibi kokar." },
    { words: ["Karpuzu", "soğuk", "yeriz"], correctSentence: "Karpuzu soğuk yeriz." },
    { words: ["Fındık", "çıtır", "çıtırdır"], correctSentence: "Fındık çıtır çıtırdır." },
    { words: ["Ceviz", "beyne", "yararlıdır"], correctSentence: "Ceviz beyne yararlıdır." },
    { words: ["Badem", "lezzetlidir"], correctSentence: "Badem lezzetlidir." },
    { words: ["Leblebi", "sarıdır"], correctSentence: "Leblebi sarıdır." },
    { words: ["Çekirdek", "çıtlatmayı", "severiz"], correctSentence: "Çekirdek çıtlatmayı severiz." },
    { words: ["Mısır", "patlatıp", "film", "izledik"], correctSentence: "Mısır patlatıp film izledik." },
    { words: ["Kestane", "kışın", "pişirilir"], correctSentence: "Kestane kışın pişirilir." },
    { words: ["Dut", "ağacı", "çok", "büyüktür"], correctSentence: "Dut ağacı çok büyüktür." },
    { words: ["İncir", "tatlı", "bir", "meyvedir"], correctSentence: "İncir tatlı bir meyvedir." },
    { words: ["Zeytin", "dalı", "barış", "demektir"], correctSentence: "Zeytin dalı barış demektir." }
];
