import { KarisikCumleItem } from '../../types/kelimeCumle';

export const KARISIK_CUMLE_SOURCES: KarisikCumleItem[] = [
    { words: ["saat", "Kemal", "7.00 de", "sabah", "uyandı"], correctSentence: "Kemal sabah saat 7.00’de uyandı." },
    { words: ["Ömer", "yemek", "Yedi"], correctSentence: "Ömer yemek yedi." },
    { words: ["ve", "Hasan", "resim", "Ayşe", "güzel", "yapıyor"], correctSentence: "Hasan ve Ayşe güzel resim yapıyor." },
    { words: ["günü", "oynadı", "Hasan", "top", "pazar"], correctSentence: "Hasan pazar günü top oynadı." },
    { words: ["aldı", "çikolata", "bakkaldan", "iki", "Ahmet"], correctSentence: "Ahmet bakkaldan iki çikolata aldı." },
    { words: ["koydu", "Anne", "çatal", "masaya"], correctSentence: "Anne masaya çatal koydu." },
    { words: ["mutfakta", "yapıyor", "Ayşe", "yemek"], correctSentence: "Ayşe mutfakta yemek yapıyor." },
    { words: ["dinliyor", "müzik", "İbrahim"], correctSentence: "İbrahim müzik dinliyor." },
    { words: ["bahçede", "uçuruyor", "Mustafa", "uçurtma"], correctSentence: "Mustafa bahçede uçurtma uçuruyor." },
    { words: ["verdi", "Yasemin", "yem", "tavuklara"], correctSentence: "Yasemin tavuklara yem verdi." },
    { words: ["duman", "Evin", "çıkıyor", "bacasından"], correctSentence: "Evin bacasından duman çıkıyor." },
    { words: ["yardım", "Zeynep", "ediyor", "annesine"], correctSentence: "Zeynep annesine yardım ediyor." },
    { words: ["ve", "kardeşim", "sinemaya", "gittik", "Ben"], correctSentence: "Ben ve kardeşim sinemaya gittik." },
    { words: ["saat", "Ramazan", "22.00’ de", "akşam", "uyudu"], correctSentence: "Ramazan akşam saat 22.00’de uyudu." },
    { words: ["olta", "Ben", "ile", "balık", "tuttum"], correctSentence: "Ben olta ile balık tuttum." },
    { words: ["hastaneye", "gittim", "Ben", "bugün"], correctSentence: "Ben bugün hastaneye gittim." },
    { words: ["seyretti", "Hüseyin", "akşam", "televizyon"], correctSentence: "Hüseyin akşam televizyon seyretti." },
    { words: ["süt", "bugün", "içtik", "okulda", "Biz"], correctSentence: "Biz bugün okulda süt içtik." },
    { words: ["okuyor", "gazete", "Dedem"], correctSentence: "Dedem gazete okuyor." },
    { words: ["içti", "Öğretmen", "maden suyu"], correctSentence: "Öğretmen maden suyu içti." },
    { words: ["yaptı", "Kerem", "ödevini", "doğru"], correctSentence: "Kerem ödevini doğru yaptı." },
    { words: ["kırmızı", "Rabia", "yedi", "elma"], correctSentence: "Rabia kırmızı elma yedi." },
    { words: ["bahçede", "oynuyor", "top", "Öğrenciler"], correctSentence: "Öğrenciler bahçede top oynuyor." },
    { words: ["bana", "Annem", "verdi", "hediye"], correctSentence: "Annem bana hediye verdi." },
    { words: ["Sertaç", "verdi", "öğrencilere", "süt"], correctSentence: "Sertaç öğrencilere süt verdi." },
    { words: ["anlattı", "ders", "sınıfta", "Öğretmen"], correctSentence: "Öğretmen sınıfta ders anlattı." },
    { words: ["yedi", "köpek", "kemik"], correctSentence: "Köpek kemik yedi." },
    { words: ["soğuk", "içti", "Ayşe", "su"], correctSentence: "Ayşe soğuk su içti." },
    { words: ["aldı", "Anne", "portakal", "pazardan"], correctSentence: "Anne pazardan portakal aldı." },
    { words: ["yüzüyor", "balıklar", "Gölde"], correctSentence: "Gölde balıklar yüzüyor." },
    { words: ["ve", "Kemal", "Eren", "etti", "kavga"], correctSentence: "Kemal ve Eren kavga etti." },
    { words: ["Ali", "okula", "geç", "kaldı"], correctSentence: "Ali okula geç kaldı." },
    { words: ["Babam", "pazardan", "elma", "aldı"], correctSentence: "Babam pazardan elma aldı." },
    { words: ["Ayşe", "kitap", "okumayı", "seviyor"], correctSentence: "Ayşe kitap okumayı seviyor." },
    { words: ["Kardeşim", "parkta", "top", "oynuyor"], correctSentence: "Kardeşim parkta top oynuyor." },
    { words: ["Hava", "bugün", "çok", "soğuk"], correctSentence: "Hava bugün çok soğuk." },
    { words: ["Annem", "pasta", "yaptı"], correctSentence: "Annem pasta yaptı." },
    { words: ["Köpeğim", "bahçede", "koşuyor"], correctSentence: "Köpeğim bahçede koşuyor." },
    { words: ["Kuşlar", "gökyüzünde", "uçuyor"], correctSentence: "Kuşlar gökyüzünde uçuyor." },
    { words: ["Sınıfımızda", "yeni", "bir", "arkadaş", "var"], correctSentence: "Sınıfımızda yeni bir arkadaş var." },
    { words: ["Öğretmenimiz", "ödev", "verdi"], correctSentence: "Öğretmenimiz ödev verdi." },
    { words: ["Sabah", "erkenden", "uyandım"], correctSentence: "Sabah erkenden uyandım." },
    { words: ["Dişlerimi", "her gün", "fırçalarım"], correctSentence: "Dişlerimi her gün fırçalarım." },
    { words: ["Okula", "servis", "ile", "gidiyorum"], correctSentence: "Okula servis ile gidiyorum." },
    { words: ["Kışın", "kar", "yağar"], correctSentence: "Kışın kar yağar." },
    { words: ["Yazın", "denizde", "yüzeriz"], correctSentence: "Yazın denizde yüzeriz." },
    { words: ["Çiçekler", "ilkbaharda", "açar"], correctSentence: "Çiçekler ilkbaharda açar." },
    { words: ["Sonbaharda", "yapraklar", "sararır"], correctSentence: "Sonbaharda yapraklar sararır." },
    { words: ["Kedim", "süt", "içmeyi", "sever"], correctSentence: "Kedim süt içmeyi sever." },
    { words: ["Babam", "işten", "eve", "geldi"], correctSentence: "Babam işten eve geldi." },
    { words: ["Akşam", "yemeğinde", "makarna", "var"], correctSentence: "Akşam yemeğinde makarna var." },
    { words: ["Televizyonda", "çizgi film", "izledim"], correctSentence: "Televizyonda çizgi film izledim." },
    { words: ["Bilgisayarda", "oyun", "oynadım"], correctSentence: "Bilgisayarda oyun oynadım." },
    { words: ["Kitaplarımı", "çantama", "koydum"], correctSentence: "Kitaplarımı çantama koydum." },
    { words: ["Resim", "yapmayı", "çok", "seviyorum"], correctSentence: "Resim yapmayı çok seviyorum." },
    { words: ["Arkadaşımla", "oyuncaklarımı", "paylaşırım"], correctSentence: "Arkadaşımla oyuncaklarımı paylaşırım." },
    { words: ["Bahçedeki", "ağaçtan", "erik", "topladık"], correctSentence: "Bahçedeki ağaçtan erik topladık." },
    { words: ["Dün", "gece", "rüya", "gördüm"], correctSentence: "Dün gece rüya gördüm." },
    { words: ["Anneannem", "bana", "kazak", "ördü"], correctSentence: "Anneannem bana kazak ördü." },
    { words: ["Dedem", "gazete", "okumayı", "sever"], correctSentence: "Dedem gazete okumayı sever." },
    { words: ["Abim", "bisiklete", "binmeyi", "öğretti"], correctSentence: "Abim bisiklete binmeyi öğretti." },
    { words: ["Sokakta", "yavru", "bir", "kedi", "bulduk"], correctSentence: "Sokakta yavru bir kedi bulduk." },
    { words: ["Ellerimi", "sabunla", "yıkadım"], correctSentence: "Ellerimi sabunla yıkadım." },
    { words: ["Banyodan", "sonra", "bornozumu", "giydim"], correctSentence: "Banyodan sonra bornozumu giydim." },
    { words: ["Pikniğe", "gitmek", "için", "hazırlandık"], correctSentence: "Pikniğe gitmek için hazırlandık." },
    { words: ["Hava", "kararınca", "eve", "döndük"], correctSentence: "Hava kararınca eve döndük." },
    { words: ["Yıldızlar", "gece", "parlıyor"], correctSentence: "Yıldızlar gece parlıyor." },
    { words: ["Ay", "gökyüzünde", "yükseldi"], correctSentence: "Ay gökyüzünde yükseldi." },
    { words: ["Güneş", "doğudan", "doğar"], correctSentence: "Güneş doğudan doğar." },
    { words: ["Yağmur", "yağınca", "şemsiye", "açtık"], correctSentence: "Yağmur yağınca şemsiye açtık." },
    { words: ["Rüzgar", "sert", "esiyor"], correctSentence: "Rüzgar sert esiyor." },
    { words: ["Kar", "her", "yeri", "beyaza", "boyadı"], correctSentence: "Kar her yeri beyaza boyadı." },
    { words: ["Tavşan", "havuç", "yemeyi", "sever"], correctSentence: "Tavşan havuç yemeyi sever." },
    { words: ["Filin", "hortumu", "çok", "uzundur"], correctSentence: "Filin hortumu çok uzundur." },
    { words: ["Zürafa", "uzun", "boyunlu", "bir", "hayvandır"], correctSentence: "Zürafa uzun boyunlu bir hayvandır." },
    { words: ["Arılar", "bal", "yapar"], correctSentence: "Arılar bal yapar." },
    { words: ["Kelebekler", "çiçeklere", "konar"], correctSentence: "Kelebekler çiçeklere konar." },
    { words: ["Karıncalar", "çok", "çalışkandır"], correctSentence: "Karıncalar çok çalışkandır." },
    { words: ["Örümcek", "ağ", "yapar"], correctSentence: "Örümcek ağ yapar." },
    { words: ["Balıklar", "suyun", "altında", "yaşar"], correctSentence: "Balıklar suyun altında yaşar." },
    { words: ["Kaplumbağa", "yavaş", "yürür"], correctSentence: "Kaplumbağa yavaş yürür." },
    { words: ["Atlar", "çok", "hızlı", "koşar"], correctSentence: "Atlar çok hızlı koşar." },
    { words: ["Aslan", "ormanların", "kralıdır"], correctSentence: "Aslan ormanların kralıdır." },
    { words: ["Maymunlar", "muz", "yer"], correctSentence: "Maymunlar muz yer." },
    { words: ["İnekler", "bize", "süt", "verir"], correctSentence: "İnekler bize süt verir." },
    { words: ["Tavuklar", "yumurta", "verir"], correctSentence: "Tavuklar yumurta verir." },
    { words: ["Koyunların", "yünü", "yumuşaktır"], correctSentence: "Koyunların yünü yumuşaktır." },
    { words: ["Ördekler", "gölde", "yüzüyor"], correctSentence: "Ördekler gölde yüzüyor." },
    { words: ["Kuşlar", "yuva", "yapar"], correctSentence: "Kuşlar yuva yapar." },
    { words: ["Civcivler", "babamın", "peşinden", "koşuyor"], correctSentence: "Civcivler babamın peşinden koşuyor." },
    { words: ["Araba", "yolda", "hızlı", "gidiyor"], correctSentence: "Araba yolda hızlı gidiyor." },
    { words: ["Bisikletim", "çok", "güzel"], correctSentence: "Bisikletim çok güzel." },
    { words: ["Patinaj", "yapmak", "eğlencelidir"], correctSentence: "Patinaj yapmak eğlencelidir." },
    { words: ["Kaydıraktan", "kaymayı", "seviyorum"], correctSentence: "Kaydıraktan kaymayı seviyorum." },
    { words: ["Salıncakta", "sallanmak", "dinlendiricidir"], correctSentence: "Salıncakta sallanmak dinlendiricidir." },
    { words: ["Uçurtmam", "göklere", "çıktı"], correctSentence: "Uçurtmam göklere çıktı." },
    { words: ["Balonum", "patladı", "diye", "ağladım"], correctSentence: "Balonum patladı diye ağladım." },
    { words: ["Oyuncaklarım", "odamda", "duruyor"], correctSentence: "Oyuncaklarım odamda duruyor." },
    { words: ["Kitaplığım", "kitap", "dolu"], correctSentence: "Kitaplığım kitap dolu." },
    { words: ["Masamın", "üstü", "çok", "dağınık"], correctSentence: "Masamın üstü çok dağınık." },
    { words: ["Kalemliğimde", "renkli", "kalemlerim", "var"], correctSentence: "Kalemliğimde renkli kalemlerim var." },
    { words: ["Defterime", "yazı", "yazdım"], correctSentence: "Defterime yazı yazdım." },
    { words: ["Müzik", "dinlemeyi", "severim"], correctSentence: "Müzik dinlemeyi severim." },
    { words: ["Şarkı", "söylemek", "beni", "mutlu", "eder"], correctSentence: "Şarkı söylemek beni mutlu eder." },
    { words: ["Dans", "etmeyi", "öğreniyorum"], correctSentence: "Dans etmeyi öğreniyorum." },
    { words: ["Yazın", "dondurma", "yeriz"], correctSentence: "Yazın dondurma yeriz." },
    { words: ["Karpuz", "yazın", "en", "sevdiğim", "meyvedir"], correctSentence: "Karpuz yazın en sevdiğim meyvedir." },
    { words: ["Okul", "başlayınca", "erken", "kalkacağız"], correctSentence: "Okul başlayınca erken kalkacağız." },
    { words: ["Tatil", "bitince", "arkadaşlarımı", "göreceğim"], correctSentence: "Tatil bitince arkadaşlarımı göreceğim." },
    { words: ["Öğretmenimizi", "çok", "özledik"], correctSentence: "Öğretmenimizi çok özledik." },
    { words: ["Yeni", "çantamı", "çok", "beğendim"], correctSentence: "Yeni çantamı çok beğendim." },
    { words: ["Ayakkabılarım", "ayağımı", "sıktı"], correctSentence: "Ayakkabılarım ayağımı sıktı." },
    { words: ["Gözlüklerimi", "evde", "unutmuşum"], correctSentence: "Gözlüklerimi evde unutmuşum." },
    { words: ["Saat", "dokuzda", "yatmalıyım"], correctSentence: "Saat dokuzda yatmalıyım." },
    { words: ["Sabahları", "süt", "içerim"], correctSentence: "Sabahları süt içerim." },
    { words: ["Yumurta", "sağlıklıdır"], correctSentence: "Yumurta sağlıklıdır." },
    { words: ["Zeytin", "ve", "peynir", "yedim"], correctSentence: "Zeytin ve peynir yedim." },
    { words: ["Bal", "tatlıdır"], correctSentence: "Bal tatlıdır." },
    { words: ["Reçel", "çilekten", "yapılır"], correctSentence: "Reçel çilekten yapılır." },
    { words: ["Ekmek", "taze", "olsun"], correctSentence: "Ekmek taze olsun." },
    { words: ["Su", "içmek", "yararlıdır"], correctSentence: "Su içmek yararlıdır." },
    { words: ["Meyve", "suyu", "vitamin", "deposudur"], correctSentence: "Meyve suyu vitamin deposudur." },
    { words: ["Çorba", "sıcak", "içilir"], correctSentence: "Çorba sıcak içilir." },
    { words: ["Salata", "renkli", "görünüyor"], correctSentence: "Salata renkli görünüyor." },
    { words: ["Pilavı", "kaşıkla", "yerim"], correctSentence: "Pilavı kaşıkla yerim." },
    { words: ["Eti", "bıçakla", "keseriz"], correctSentence: "Eti bıçakla keseriz." },
    { words: ["Patates", "kızartmasını", "severim"], correctSentence: "Patates kızartmasını severim." },
    { words: ["Ispanak", "güç", "verir"], correctSentence: "Ispanak güç verir." },
    { words: ["Havuç", "göze", "iyidir"], correctSentence: "Havuç göze iyidir." },
    { words: ["Elma", "en", "sevdiğim", "meyvedir"], correctSentence: "Elma en sevdiğim meyvedir." },
    { words: ["Çilek", "mis", "gibi", "kokuyor"], correctSentence: "Çilek mis gibi kokuyor." },
    { words: ["Muz", "yumuşak", "bir", "meyvedir"], correctSentence: "Muz yumuşak bir meyvedir." },
    { words: ["Üzüm", "tatlıdır"], correctSentence: "Üzüm tatlıdır." },
    { words: ["Erik", "ekşidir"], correctSentence: "Erik ekşidir." },
    { words: ["Limon", "çok", "sarıdır"], correctSentence: "Limon çok sarıdır." },
    { words: ["Portakal", "vitaminli", "bir", "meyvedir"], correctSentence: "Portakal vitaminli bir meyvedir." },
    { words: ["Mandalina", "kolay", "soyulur"], correctSentence: "Mandalina kolay soyulur." },
    { words: ["Kirazı", "yazın", "yeriz"], correctSentence: "Kirazı yazın yeriz." },
    { words: ["Vişne", "suyu", "kırmızıdır"], correctSentence: "Vişne suyu kırmızıdır." },
    { words: ["Kayısı", "turuncu", "renklidir"], correctSentence: "Kayısı turuncu renklidir." },
    { words: ["Şeftali", "tüylüdür"], correctSentence: "Şeftali tüylüdür." },
    { words: ["Kavun", "mis", "gibi", "kokar"], correctSentence: "Kavun mis gibi kokar." },
    { words: ["Karpuzu", "soğuk", "yeriz"], correctSentence: "Karpuzu soğuk yeriz." },
    { words: ["Fındık", "çıtır", "çıtırdır"], correctSentence: "Fındık çıtır çıtırdır." },
    { words: ["Ceviz", "beyne", "yararlıdır"], correctSentence: "Ceviz beyne yararlıdır." },
    { words: ["Badem", "lezzetlidir"], correctSentence: "Badem lezzetlidir." },
    { words: ["Leblebi", "sarıdır"], correctSentence: "Leblebi sarıdır." },
    { words: ["Çekirdek", "çıtlatmayı", "severiz"], correctSentence: "Çekirdek çıtlatmayı severiz." },
    { words: ["Mısır", "patlatıp", "film", "izledik"], correctSentence: "Mısır patlatıp film izledik." },
    { words: ["Kestane", "kışın", "pişirilir"], correctSentence: "Kestane kışın pişirilir." },
    { words: ["Dut", "ağacı", "çok", "büyüktür"], correctSentence: "Dut ağacı çok büyüktür." },
    { words: ["İncir", "tatlı", "bir", "meyvedir"], correctSentence: "İncir tatlı bir meyvedir." },
    { words: ["Zeytin", "dalı", "barış", "demektir"], correctSentence: "Zeytin dalı barış demektir." },
    { words: ["Arkadaşlarımla", "okulda", "top", "oynadık"], correctSentence: "Arkadaşlarımla okulda top oynadık." },
    { words: ["Öğretmenimiz", "bize", "masal", "okudu"], correctSentence: "Öğretmenimiz bize masal okudu." },
    { words: ["Annem", "pazardan", "meyve", "aldı"], correctSentence: "Annem pazardan meyve aldı." },
    { words: ["Babam", "akşam", "geç", "geldi"], correctSentence: "Babam akşam geç geldi." },
    { words: ["Kardeşim", "odasında", "ders", "çalışıyor"], correctSentence: "Kardeşim odasında ders çalışıyor." },
    { words: ["Bahçedeki", "ağaçlar", "meyve", "verdi"], correctSentence: "Bahçedeki ağaçlar meyve verdi." },
    { words: ["Kuşlar", "yuvadan", "uçtu"], correctSentence: "Kuşlar yuvadan uçtu." },
    { words: ["Kedim", "yumuşak", "yastıkta", "uyuyor"], correctSentence: "Kedim yumuşak yastıkta uyuyor." },
    { words: ["Köpeğim", "kemik", "yemeyi", "seviyor"], correctSentence: "Köpeğim kemik yemeyi seviyor." },
    { words: ["Gökyüzü", "bulutlarla", "kapalı"], correctSentence: "Gökyüzü bulutlarla kapalı." },
    { words: ["Yağmur", "sabahın", "ilk", "ışıklarında", "başladı"], correctSentence: "Yağmur sabahın ilk ışıklarında başladı." },
    { words: ["Güneş", "dağların", "ardından", "doğdu"], correctSentence: "Güneş dağların ardından doğdu." },
    { words: ["Denizdeki", "balıklar", "çok", "hızlı"], correctSentence: "Denizdeki balıklar çok hızlı." },
    { words: ["Gemi", "uzak", "limana", "yanaştı"], correctSentence: "Gemi uzak limana yanaştı." },
    { words: ["Bisikletim", "zinciri", "yerinden", "çıktı"], correctSentence: "Bisikletim zinciri yerinden çıktı." },
    { words: ["Okul", "çantama", "kitaplarımı", "yerleştirdim"], correctSentence: "Okul çantama kitaplarımı yerleştirdim." },
    { words: ["Sınıfın", "tahtası", "tertemiz", "yapıldı"], correctSentence: "Sınıfın tahtası tertemiz yapıldı." },
    { words: ["Beslenme", "çantamda", "zeytinli", "açma", "var"], correctSentence: "Beslenme çantamda zeytinli açma var." },
    { words: ["Matematik", "defterim", "çantamda", "kalmış"], correctSentence: "Matematik defterim çantamda kalmış." },
    { words: ["Müzik", "dersinde", "flüt", "çaldık"], correctSentence: "Müzik dersinde flüt çaldık." },
    { words: ["Beden", "dersinde", "yarış", "yaptık"], correctSentence: "Beden dersinde yarış yaptık." },
    { words: ["Resim", "sergimizi", "veliler", "gezdi"], correctSentence: "Resim sergimizi veliler gezdi." },
    { words: ["Tiyatro", "oyunundaki", "rolümü", "ezberledim"], correctSentence: "Tiyatro oyunundaki rolümü ezberledim." },
    { words: ["Sinemadaki", "film", "çok", "Heyecanlıydı"], correctSentence: "Sinemadaki film çok heyecanlıydı." },
    { words: ["Parktaki", "çocuklar", "neşeyle", "bağırıyordu"], correctSentence: "Parktaki çocuklar neşeyle bağırıyordu." },
    { words: ["Yürüyüş", "yapmak", "kalbe", "iyidir"], correctSentence: "Yürüyüş yapmak kalbe iyidir." },
    { words: ["Düzenli", "uyku", "bizi", "dinç", "tutar"], correctSentence: "Düzenli uyku bizi dinç tutar." },
    { words: ["Sebze", "yemek", "vücudu", "güçlendirir"], correctSentence: "Sebze yemek vücudu güçlendirir." },
    { words: ["Su", "hayattır", "boşa", "akıtma"], correctSentence: "Su hayattır boşa akıtma." },
    { words: ["Dişlerini", "günde", "iki", "kez", "fırçala"], correctSentence: "Dişlerini günde iki kez fırçala." },
    { words: ["Ellerini", "sabunla", "ovlayarak", "yıka"], correctSentence: "Ellerini sabunla ovlayarak yıka." },
    { words: ["Çöpleri", "çöp", "kutusuna", "at"], correctSentence: "Çöpleri çöp kutusuna at." },
    { words: ["Doğayı", "sev", "ve", "koru"], correctSentence: "Doğayı sev ve koru." },
    { words: ["Hayvanlara", "merhametli", "davran"], correctSentence: "Hayvanlara merhametli davran." },
    { words: ["Kuşlara", "bir", "kap", "su", "koy"], correctSentence: "Kuşlara bir kap su koy." },
    { words: ["Karıncalar", "çok", "çalışkan", "hayvanlardır"], correctSentence: "Karıncalar çok çalışkan hayvanlardır." },
    { words: ["Arılar", "çiçeklerden", "öz", "toplar"], correctSentence: "Arılar çiçeklerden öz toplar." },
    { words: ["Kelebeğin", "kanatları", "çok", "narin"], correctSentence: "Kelebeğin kanatları çok narin." },
    { words: ["Uğur", "böceği", "benekli", "bir", "böcektir"], correctSentence: "Uğur böceği benekli bir böcektir." },
    { words: ["Eski", "eşyaları", "geri", "dönüştürelim"], correctSentence: "Eski eşyaları geri dönüştürelim." },
    { words: ["Kağıdı", "boşa", "harcama"], correctSentence: "Kağıdı boşa harcama." },
    { words: ["Elektriği", "tasarruflu", "kullan"], correctSentence: "Elektriği tasarruflu kullan." },
    { words: ["Güneş", "enerjisi", "doğa", "dostudur"], correctSentence: "Güneş enerjisi doğa dostudur." },
    { words: ["Yağmuru", "seviyorum", "çünkü", "bereketli"], correctSentence: "Yağmuru seviyorum çünkü bereketli." },
    { words: ["Karda", "kaymak", "çok", "eğlenceli"], correctSentence: "Karda kaymak çok eğlenceli." },
    { words: ["Yaz", "tatilini", "iple", "çekiyorum"], correctSentence: "Yaz tatilini iple çekiyorum." },
    { words: ["Okula", "gitmek", "beni", "mutlu", "ediyor"], correctSentence: "Okula gitmek beni mutlu ediyor." },
    { words: ["Yeni", "kitaplarımı", "çok", "sevdim"], correctSentence: "Yeni kitaplarımı çok sevdim." },
    { words: ["Kütüphane", "çok", "sessiz", "bir", "yerdir"], correctSentence: "Kütüphane çok sessiz bir yerdir." },
    { words: ["Ödevlerimi", "vaktinde", "bitirmeliyim"], correctSentence: "Ödevlerimi vaktinde bitirmeliyim." },
    { words: ["Ders", "dinlerken", "not", "alırım"], correctSentence: "Ders dinlerken not alırım." },
    { words: ["Sınavlara", "severek", "hazırlanırım"], correctSentence: "Sınavlara severek hazırlanırım." },
    { words: ["Başarı", "çalışmakla", "mümkündür"], correctSentence: "Başarı çalışmakla mümkündür." },
    { words: ["Hayallerimin", "peşinden", "koşacağım"], correctSentence: "Hayallerimin peşinden koşacağım." },
    { words: ["Zamanı", "iyi", "değerlendir"], correctSentence: "Zamanı iyi değerlendir." },
    { words: ["Dürüst", "olmak", "en", "büyük", "erdemdir"], correctSentence: "Dürüst olmak en büyük erdemdir." },
    { words: ["Yalan", "söylemek", "insanı", "yalnızlaştırır"], correctSentence: "Yalan söylemek insanı yalnızlaştırır." },
    { words: ["Arkadaşlık", "paylaşınca", "güzel"], correctSentence: "Arkadaşlık paylaşınca güzel." },
    { words: ["Birbirimize", "saygılı", "davranmalıyız"], correctSentence: "Birbirimize saygılı davranmalıyız." },
    { words: ["Sevgi", "dünyayı", "güzelleştirir"], correctSentence: "Sevgi dünyayı güzelleştirir." },
    { words: ["Barış", "içinde", "yaşayalım"], correctSentence: "Barış içinde yaşayalım." },
    { words: ["Hoşgörülü", "bir", "insan", "ol"], correctSentence: "Hoşgörülü bir insan ol." },
    { words: ["Yardımseverlik", "kalbi", "yumuşatır"], correctSentence: "Yardımseverlik kalbi yumuşatır." },
    { words: ["Yaşlılara", "yardım", "etmeliyiz"], correctSentence: "Yaşlılara yardım etmeliyiz." },
    { words: ["Engelli", "vatandaşlarımıza", "destek", "olalım"], correctSentence: "Engelli vatandaşlarımıza destek olalım." },
    { words: ["Zorlukların", "üstesinden", "beraber", "geleceğiz"], correctSentence: "Zorlukların üstesinden beraber geleceğiz." },
    { words: ["Kitap", "en", "iyi", "dosttur"], correctSentence: "Kitap en iyi dosttur." },
    { words: ["Bilgi", "paylaştıkça", "çoğalır"], correctSentence: "Bilgi paylaştıkça çoğalır." },
    { words: ["Okumak", "zihni", "açar"], correctSentence: "Okumak zihni açar." },
    { words: ["Yazmak", "düşünceleri", "netleştirir"], correctSentence: "Yazmak düşünceleri netleştirir." },
    { words: ["Düşünmek", "özgürlüktür"], correctSentence: "Düşünmek özgürlüktür." },
    { words: ["Merak", "etmek", "öğrenmenin", "başıdır"], correctSentence: "Merak etmek öğrenmenin başıdır." },
    { words: ["Soru", "sormaktan", "korkma"], correctSentence: "Soru sormaktan korkma." },
    { words: ["Cevaplar", "kitaplarda", "gizlidir"], correctSentence: "Cevaplar kitaplarda gizlidir." },
    { words: ["Dünya", "çok", "büyük", "bir", "yer"], correctSentence: "Dünya çok büyük bir yer." },
    { words: ["Uzay", "sonu", "olmayan", "bir", "boşluk"], correctSentence: "Uzay sonu olmayan bir boşluk." },
    { words: ["Gezegenler", "güneşin", "etrafında", "döner"], correctSentence: "Gezegenler güneşin etrafında döner." },
    { words: ["Yıldızlar", "gece", "bize", "göz", "kırpar"], correctSentence: "Yıldızlar gece bize göz kırpar." },
    { words: ["Ay", "geceyi", "aydınlatır"], correctSentence: "Ay geceyi aydınlatır." },
    { words: ["Fener", "karanlıkta", "Yol", "gösterir"], correctSentence: "Fener karanlıkta yol gösterir." },
    { words: ["Mum", "dibine", "ışık", "vermez"], correctSentence: "Mum dibine ışık vermez." },
    { words: ["Ateş", "ile", "şaka", "olmaz"], correctSentence: "Ateş ile şaka olmaz." },
    { words: ["Barut", "ile", "ateş", "yan", "yana", "durmaz"], correctSentence: "Barut ile ateş yan yana durmaz." },
    { words: ["Su", "akar", "yolunu", "bulur"], correctSentence: "Su akar yolunu bulur." },
    { words: ["Emek", "olmadan", "yemek", "olmaz"], correctSentence: "Emek olmadan yemek olmaz." },
    { words: ["Sakla", "semanı", "gelir", "zamanı"], correctSentence: "Sakla samanı gelir zamanı." },
    { words: ["İyilik", "yapan", "iyilik", "bulur"], correctSentence: "İyilik yapan iyilik bulur." },
    { words: ["Gülme", "komşuna", "gelir", "başına"], correctSentence: "Gülme komşuna gelir başına." },
    { words: ["Damlaya", "damlaya", "göl", "olur"], correctSentence: "Damlaya damlaya göl olur." },
    { words: ["Ağaç", "yaşken", "eğilir"], correctSentence: "Ağaç yaşken eğilir." },
    { words: ["Birlikten", "kuvvet", "doğar"], correctSentence: "Birlikten kuvvet doğar." },
    { words: ["Tatlı", "dil", "yılanı", "deliğinden", "çıkarır"], correctSentence: "Tatlı dil yılanı deliğinden çıkarır." },
    { words: ["Sabreden", "derviş", "muradına", "ermiş"], correctSentence: "Sabreden derviş muradına ermiş." },
    { words: ["Vakit", "nakittir"], correctSentence: "Vakit nakittir." }
];
