import { KarisikCumleItem } from '../../types/kelimeCumle';

export const KARISIK_CUMLE_SOURCES: KarisikCumleItem[] = [
    { words: ["saat", "Kemal", "7.00 de", "sabah", "uyandı"], correctSentence: "Kemal sabah saat 7.00’de uyandı." },
    { words: ["Ömer", "yemek", "Yedi"], correctSentence: "Ömer yemek yedi." },
    { words: ["ve", "Hasan", "resim", "Ayşe", "güzel", "yapıyor"], correctSentence: "Hasan ve Ayşe güzel resim yapıyor." },
    { words: ["günü", "oynadı", "Hasan", "top", "pazar"], correctSentence: "Hasan pazar günü top oynadı." },
    { words: ["aldı", "çikolata", "bakkaldan", "iki", "Ahmet"], correctSentence: "Ahmet bakkaldan iki çikolata aldı." },
    { words: ["koydu", "Anne", "çatal", "masaya"], correctSentence: "Anne masaya çatal koydu." },
    { words: ["mutfakta", "yapıyor", "Ayşe", "yemek"], correctSentence: "Ayşe mutfakta yemek yapıyor." },
    { words: ["dinliyor", "müzik", "İbrahim"], correctSentence: "İbrahim müzik dinliyor." },
    { words: ["bahçede", "uçuruyor", "Mustafa", "uçurtma"], correctSentence: "Mustafa bahçede uçurtma uçuruyor." },
    { words: ["verdi", "Yasemin", "yem", "tavuklara"], correctSentence: "Yasemin tavuklara yem verdi." },
    { words: ["duman", "Evin", "çıkıyor", "bacasından"], correctSentence: "Evin bacasından duman çıkıyor." },
    { words: ["yardım", "Zeynep", "ediyor", "annesine"], correctSentence: "Zeynep annesine yardım ediyor." },
    { words: ["ve", "kardeşim", "sinemaya", "gittik", "Ben"], correctSentence: "Ben ve kardeşim sinemaya gittik." },
    { words: ["saat", "Ramazan", "22.00’ de", "akşam", "uyudu"], correctSentence: "Ramazan akşam saat 22.00’de uyudu." },
    { words: ["olta", "Ben", "ile", "balık", "tuttum"], correctSentence: "Ben olta ile balık tuttum." },
    { words: ["hastaneye", "gittim", "Ben", "bugün"], correctSentence: "Ben bugün hastaneye gittim." },
    { words: ["seyretti", "Hüseyin", "akşam", "televizyon"], correctSentence: "Hüseyin akşam televizyon seyretti." },
    { words: ["süt", "bugün", "içtik", "okulda", "Biz"], correctSentence: "Biz bugün okulda süt içtik." },
    { words: ["okuyor", "gazete", "Dedem"], correctSentence: "Dedem gazete okuyor." },
    { words: ["içti", "Öğretmen", "maden suyu"], correctSentence: "Öğretmen maden suyu içti." },
    { words: ["yaptı", "Kerem", "ödevini", "doğru"], correctSentence: "Kerem ödevini doğru yaptı." },
    { words: ["kırmızı", "Rabia", "yedi", "elma"], correctSentence: "Rabia kırmızı elma yedi." },
    { words: ["bahçede", "oynuyor", "top", "Öğrenciler"], correctSentence: "Öğrenciler bahçede top oynuyor." },
    { words: ["bana", "Annem", "verdi", "hediye"], correctSentence: "Annem bana hediye verdi." },
    { words: ["Sertaç", "verdi", "öğrencilere", "süt"], correctSentence: "Sertaç öğrencilere süt verdi." },
    { words: ["anlattı", "ders", "sınıfta", "Öğretmen"], correctSentence: "Öğretmen sınıfta ders anlattı." },
    { words: ["yedi", "köpek", "kemik"], correctSentence: "Köpek kemik yedi." },
    { words: ["soğuk", "içti", "Ayşe", "su"], correctSentence: "Ayşe soğuk su içti." },
    { words: ["aldı", "Anne", "portakal", "pazardan"], correctSentence: "Anne pazardan portakal aldı." },
    { words: ["yüzüyor", "balıklar", "Gölde"], correctSentence: "Gölde balıklar yüzüyor." },
    { words: ["ve", "Kemal", "Eren", "etti", "kavga"], correctSentence: "Kemal ve Eren kavga etti." }
];
