import { KelimeTamamlamaItem } from '../../types/kelimeCumle';

export const KELIME_TAMAMLAMA_SOURCES: KelimeTamamlamaItem[] = [
    { word: "Silgi", fullWord: "Silgi", clue: "Silmeye yarayan ders aracı" },
    { word: "İnek", fullWord: "İnek", clue: "Süt veren hayvan" },
    { word: "Horoz", fullWord: "Horoz", clue: "Kümeste yaşar" },
    { word: "Halı", fullWord: "Halı", clue: "Evde yere sereriz" },
    { word: "Gözlük", fullWord: "Gözlük", clue: "Gözümüze takarız" },
    { word: "Gazete", fullWord: "Gazete", clue: "Okuruz" },
    { word: "Ekmek", fullWord: "Ekmek", clue: "Yemekte yeriz" },
    { word: "Domuz", fullWord: "Domuz", clue: "Bir hayvan" },
    { word: "Çorba", fullWord: "Çorba", clue: "Yemekte içeriz" },
    { word: "Çilek", fullWord: "Çilek", clue: "Bir meyve adı" },
    { word: "Cüzdan", fullWord: "Cüzdan", clue: "İçine para koyarız" },
    { word: "Cetvel", fullWord: "Cetvel", clue: "Çizgi çizeriz" },
    { word: "Bıçak", fullWord: "Bıçak", clue: "Kesme aracı" },
    { word: "Ayran", fullWord: "Ayran", clue: "Beyaz bir içecek" },
    { word: "Bakkal", fullWord: "Bakkal", clue: "Alışveriş yapılan yer" },
    { word: "Bardak", fullWord: "Bardak", clue: "Su içeriz" },
    { word: "Yağmur", fullWord: "Yağmur", clue: "Gökyüzünden yağar" },
    { word: "Toka", fullWord: "Toka", clue: "Kızlar saçına takar" },
    { word: "Telefon", fullWord: "Telefon", clue: "Konuşuruz" },
    { word: "Tavuk", fullWord: "Tavuk", clue: "Bir hayvan" },
    { word: "Salı", fullWord: "Salı", clue: "Haftanın bir günü" },
    { word: "Şeftali", fullWord: "Şeftali", clue: "Bir meyve" },
    { word: "Şapka", fullWord: "Şapka", clue: "Başımıza giyeriz" },
    { word: "Sucuk", fullWord: "Sucuk", clue: "Bir yiyecek" },
    { word: "Simit", fullWord: "Simit", clue: "Unlu bir yiyecek" },
    { word: "Sabun", fullWord: "Sabun", clue: "Ellerimizi yıkarız" },
    { word: "Pusula", fullWord: "Pusula", clue: "Yönleri gösterir" },
    { word: "Portakal", fullWord: "Portakal", clue: "Bir meyve" },
    { word: "Pilav", fullWord: "Pilav", clue: "Bir yemek adı" },
    { word: "Peynir", fullWord: "Peynir", clue: "Kahvaltıda yeriz" },
    { word: "Pasta", fullWord: "Pasta", clue: "Doğum gününde yeriz" },
    { word: "Öğretmen", fullWord: "Öğretmen", clue: "Sınıfta ders anlatır" },
    { word: "Orman", fullWord: "Orman", clue: "Çok ağaç olan yer" },
    { word: "Olta", fullWord: "Olta", clue: "Balık tutarız" },
    { word: "Müdür", fullWord: "Müdür", clue: "Okulu yönetir" },
    { word: "Mutfak", fullWord: "Mutfak", clue: "Evin bir bölümü" },
    { word: "Makas", fullWord: "Makas", clue: "Kağıt kesme aracı" },
    { word: "Limon", fullWord: "Limon", clue: "Sarı renkli ekşi bir meyve" },
    { word: "Leylek", fullWord: "Leylek", clue: "Uçan büyük bir hayvan" },
    { word: "Lamba", fullWord: "Lamba", clue: "Işık verir" },
    { word: "Küpe", fullWord: "Küpe", clue: "Kızlar kulağa takar" },
    { word: "Araba", fullWord: "Araba", clue: "Dört tekerlekli ulaşım aracı" },
    { word: "Balık", fullWord: "Balık", clue: "Suda yaşayan pullu hayvan" },
    { word: "Resim", fullWord: "Resim", clue: "Kağıda çizilen görsel" },
    { word: "Masa", fullWord: "Masa", clue: "Üzerinde yemek yediğimiz mobilya" },
    { word: "Sandalye", fullWord: "Sandalye", clue: "Üzerine oturduğumuz eşya" },
    { word: "Dolap", fullWord: "Dolap", clue: "Eşyalarımızı koyduğumuz mobilya" },
    { word: "Kitap", fullWord: "Kitap", clue: "Okuduğumuz sayfalar bütünü" },
    { word: "Kalem", fullWord: "Kalem", clue: "Yazı yazmaya yarayan araç" },
    { word: "Defter", fullWord: "Defter", clue: "Not aldığımız sayfalar" },
    { word: "Okul", fullWord: "Okul", clue: "Eğitim gördüğümüz yer" },
    { word: "Sınıf", fullWord: "Sınıf", clue: "Ders yapılan oda" },
    { word: "Tahta", fullWord: "Tahta", clue: "Öğretmenin üzerine yazı yazdığı yer" },
    { word: "Sıra", fullWord: "Sıra", clue: "Öğrencilerin oturduğu yer" },
    { word: "Çanta", fullWord: "Çanta", clue: "Eşyalarımızı taşıdığımız araç" },
    { word: "Ceket", fullWord: "Ceket", clue: "Üstümüze giydiğimiz kıyafet" },
    { word: "Pantolon", fullWord: "Pantolon", clue: "Bacaklarımıza giydiğimiz kıyafet" },
    { word: "Gömlek", fullWord: "Gömlek", clue: "Düğmeli üst kıyafeti" },
    { word: "Kazak", fullWord: "Kazak", clue: "Kışın giyilen yünlü kıyafet" },
    { word: "Çorap", fullWord: "Çorap", clue: "Ayağımıza giydiğimiz giysi" },
    { word: "Ayakkabı", fullWord: "Ayakkabı", clue: "Yürürken ayağımıza giyeriz" },
    { word: "Elma", fullWord: "Elma", clue: "Kırmızı veya yeşil meyve" },
    { word: "Armut", fullWord: "Armut", clue: "Sarı renkli meyve" },
    { word: "Muz", fullWord: "Muz", clue: "Uzun sarı meyve" },
    { word: "Üzüm", fullWord: "Üzüm", clue: "Salkım şeklinde meyve" },
    { word: "Kavun", fullWord: "Kavun", clue: "Yazın yenen tatlı meyve" },
    { word: "Karpuz", fullWord: "Karpuz", clue: "İçi kırmızı dışı yeşil meyve" },
    { word: "Kiraz", fullWord: "Kiraz", clue: "Küçük kırmızı saplı meyve" },
    { word: "Erik", fullWord: "Erik", clue: "Yeşil veya mor ekşi meyve" },
    { word: "Vişne", fullWord: "Vişne", clue: "Ekşi kırmızı meyve" },
    { word: "Kayısı", fullWord: "Kayısı", clue: "Turuncu tatlı meyve" },
    { word: "Domates", fullWord: "Domates", clue: "Kırmızı sebze/meyve" },
    { word: "Salatalık", fullWord: "Salatalık", clue: "Yeşil uzun sebze" },
    { word: "Patates", fullWord: "Patates", clue: "Toprak altında yetişen sebze" },
    { word: "Soğan", fullWord: "Soğan", clue: "Yemeklere tat veren acı sebze" },
    { word: "Havuç", fullWord: "Havuç", clue: "Turuncu uzun sebze" },
    { word: "Biber", fullWord: "Biber", clue: "Acı veya tatlı sebze" },
    { word: "Patlıcan", fullWord: "Patlıcan", clue: "Mor uzun sebze" },
    { word: "Kabak", fullWord: "Kabak", clue: "Yeşil dolmalık sebze" },
    { word: "Ispanak", fullWord: "Ispanak", clue: "Yeşil yapraklı sebze" },
    { word: "Pırasa", fullWord: "Pırasa", clue: "Beyaz saplı yeşil yapraklı sebze" },
    { word: "Lahana", fullWord: "Lahana", clue: "Kat kat yapraklı sebze" },
    { word: "Kedi", fullWord: "Kedi", clue: "Miyavlayan evcil hayvan" },
    { word: "Köpek", fullWord: "Köpek", clue: "Havlayan sadık hayvan" },
    { word: "Kuş", fullWord: "Kuş", clue: "Uçan ve öten hayvan" },
    { word: "Tavşan", fullWord: "Tavşan", clue: "Uzun kulaklı zıplayan hayvan" },
    { word: "Aslan", fullWord: "Aslan", clue: "Ormanların kralı" },
    { word: "Kaplan", fullWord: "Kaplan", clue: "Çizgili büyük kedi" },
    { word: "Zürafa", fullWord: "Zürafa", clue: "Uzun boyunlu hayvan" },
    { word: "Fil", fullWord: "Fil", clue: "Hortumlu dev hayvan" },
    { word: "Maymun", fullWord: "Maymun", clue: "Ağaçlara tırmanan hayvan" },
    { word: "Zebra", fullWord: "Zebra", clue: "Siyah beyaz çizgili at" },
    { word: "Ayı", fullWord: "Ayı", clue: "Kış uykusuna yatan hayvan" },
    { word: "Kurt", fullWord: "Kurt", clue: "Uluyan yabani hayvan" },
    { word: "Tilki", fullWord: "Tilki", clue: "Kurnazlığıyla bilinen hayvan" },
    { word: "Geyik", fullWord: "Geyik", clue: "Boynuzlu zarif hayvan" },
    { word: "Ördek", fullWord: "Ördek", clue: "Vak vak diyen kuş" },
    { word: "Kaz", fullWord: "Kaz", clue: "Büyük beyaz su kuşu" },
    { word: "Kuzu", fullWord: "Kuzu", clue: "Koyunun yavrusu" },
    { word: "At", fullWord: "At", clue: "Üzerine binilen binek hayvanı" },
    { word: "Eşek", fullWord: "Eşek", clue: "Uzun kulaklı yük taşıyan hayvan" },
    { word: "Bebek", fullWord: "Bebek", clue: "Yeni doğmuş insan" },
    { word: "Anne", fullWord: "Anne", clue: "Kadın ebeveyn" },
    { word: "Baba", fullWord: "Baba", clue: "Erkek ebeveyn" },
    { word: "Dede", fullWord: "Dede", clue: "Annenin veya babanın babası" },
    { word: "Nene", fullWord: "Nene", clue: "Annenin veya babanın annesi" },
    { word: "Kardeş", fullWord: "Kardeş", clue: "Aynı anne babadan olan" },
    { word: "Abla", fullWord: "Abla", clue: "Büyük kız kardeş" },
    { word: "Abi", fullWord: "Abi", clue: "Büyük erkek kardeş" },
    { word: "Hala", fullWord: "Hala", clue: "Babanın kız kardeşi" },
    { word: "Teyze", fullWord: "Teyze", clue: "Annenin kız kardeşi" },
    { word: "Amca", fullWord: "Amca", clue: "Babanın erkek kardeşi" },
    { word: "Dayı", fullWord: "Dayı", clue: "Annenin erkek kardeşi" },
    { word: "Ev", fullWord: "Ev", clue: "İçinde yaşadığımız bina" },
    { word: "Oda", fullWord: "Oda", clue: "Evin bölümleri" },
    { word: "Salon", fullWord: "Salon", clue: "Misafir ağırlanan büyük oda" },
    { word: "Yatak", fullWord: "Yatak", clue: "Üzerinde uyuduğumuz eşya" },
    { word: "Banyo", fullWord: "Banyo", clue: "Yıkandığımız yer" },
    { word: "Tuvalet", fullWord: "Tuvalet", clue: "İhtiyacımızı giderdiğimiz yer" },
    { word: "Balkon", fullWord: "Balkon", clue: "Evin dışa açılan bölümü" },
    { word: "Çatı", fullWord: "Çatı", clue: "Evin en üst kısmı" },
    { word: "Pencere", fullWord: "Pencere", clue: "Duvarlardaki camlı açıklık" },
    { word: "Kapı", fullWord: "Kapı", clue: "İçeri girmeye yarayan bölüm" },
    { word: "Merdiven", fullWord: "Merdiven", clue: "Üst katlara çıkmaya yarar" },
    { word: "Yol", fullWord: "Yol", clue: "Üzerinde yürünen veya gidilen yer" },
    { word: "Sokak", fullWord: "Sokak", clue: "Evlerin arasındaki yol" },
    { word: "Park", fullWord: "Park", clue: "Oyun oynanan açık alan" },
    { word: "Bahçe", fullWord: "Bahçe", clue: "Evin önündeki açık alan" },
    { word: "Deniz", fullWord: "Deniz", clue: "Büyük tuzlu su kütlesi" },
    { word: "Göl", fullWord: "Göl", clue: "Dört tarafı kapalı tatlı su kütlesi" },
    { word: "Nehir", fullWord: "Nehir", clue: "Akan su kütlesi" },
    { word: "Dağ", fullWord: "Dağ", clue: "Çok yüksek yer şekli" },
    { word: "Orman", fullWord: "Orman", clue: "Ağaçlarla kaplı geniş alan" },
    { word: "Çöl", fullWord: "Çöl", clue: "Kumlarla kaplı kurak alan" },
    { word: "Ada", fullWord: "Ada", clue: "Dört tarafı sularla çevrili kara" },
    { word: "Güneş", fullWord: "Güneş", clue: "Dünyamızı ısıtan ve aydınlatan" },
    { word: "Ay", fullWord: "Ay", clue: "Geceleri görülen gök cismi" },
    { word: "Yıldız", fullWord: "Yıldız", clue: "Geceleri parlayan küçük gök cisimleri" },
    { word: "Bulut", fullWord: "Bulut", clue: "Gökyüzündeki beyaz kümeler" },
    { word: "Yağmur", fullWord: "Yağmur", clue: "Bulutlardan düşen su damlaları" },
    { word: "Kar", fullWord: "Kar", clue: "Bulutlardan düşen beyaz taneler" },
    { word: "Fırtına", fullWord: "Fırtına", clue: "Çok şiddetli rüzgar" },
    { word: "Şimşek", fullWord: "Şimşek", clue: "Gökyüzündeki ani ışık patlaması" },
    { word: "Gökkuşağı", fullWord: "Gökkuşağı", clue: "Yağmurdan sonra çıkan renkli kuşak" },
    { word: "Mevsim", fullWord: "Mevsim", clue: "Yılın dört bölümünden biri" },
    { word: "Yaz", fullWord: "Yaz", clue: "En sıcak mevsim" },
    { word: "Kış", fullWord: "Kış", clue: "En soğuk mevsim" },
    { word: "İlkbahar", fullWord: "İlkbahar", clue: "Çiçeklerin açtığı mevsim" },
    { word: "Sonbahar", fullWord: "Sonbahar", clue: "Yaprakların döküldüğü mevsim" },
    { word: "Pazartesi", fullWord: "Pazartesi", clue: "Haftanın ilk günü" },
    { word: "Salı", fullWord: "Salı", clue: "Haftanın ikinci günü" },
    { word: "Çarşamba", fullWord: "Çarşamba", clue: "Haftanın üçüncü günü" },
    { word: "Perşembe", fullWord: "Perşembe", clue: "Haftanın dördüncü günü" },
    { word: "Cuma", fullWord: "Cuma", clue: "Haftanın beşinci günü" },
    { word: "Cumartesi", fullWord: "Cumartesi", clue: "Tatil günlerinden biri" },
    { word: "Pazar", fullWord: "Pazar", clue: "Haftanın son günü" },
    { word: "Ocak", fullWord: "Ocak", clue: "Yılın ilk ayı" },
    { word: "Şubat", fullWord: "Şubat", clue: "Yılın ikinci ayı" },
    { word: "Mart", fullWord: "Mart", clue: "Yılın üçüncü ayı" },
    { word: "Nisan", fullWord: "Nisan", clue: "Yılın dördüncü ayı" },
    { word: "Mayıs", fullWord: "Mayıs", clue: "Yılın beşinci ayı" },
    { word: "Haziran", fullWord: "Haziran", clue: "Yılın altıncı ayı" },
    { word: "Temmuz", fullWord: "Temmuz", clue: "Yılın yedinci ayı" },
    { word: "Ağustos", fullWord: "Ağustos", clue: "Yılın sekizinci ayı" },
    { word: "Eylül", fullWord: "Eylül", clue: "Yılın dokuzuncu ayı" },
    { word: "Ekim", fullWord: "Ekim", clue: "Yılın onuncu ayı" },
    { word: "Kasım", fullWord: "Kasım", clue: "Yılın on birinci ayı" },
    { word: "Aralık", fullWord: "Aralık", clue: "Yılın son ayı" },
    { word: "Kırmızı", fullWord: "Kırmızı", clue: "Al rengi" },
    { word: "Mavi", fullWord: "Mavi", clue: "Gökyüzünün rengi" },
    { word: "Sarı", fullWord: "Sarı", clue: "Güneşin rengi" },
    { word: "Yeşil", fullWord: "Yeşil", clue: "Yaprağın rengi" },
    { word: "Beyaz", fullWord: "Beyaz", clue: "Karın rengi" },
    { word: "Siyah", fullWord: "Siyah", clue: "Gecenin rengi" },
    { word: "Mor", fullWord: "Mor", clue: "Patlıcanın rengi" },
    { word: "Turuncu", fullWord: "Turuncu", clue: "Havucun rengi" },
    { word: "Pembe", fullWord: "Pembe", clue: "Gülün bir rengi" },
    { word: "Gri", fullWord: "Gri", clue: "Bulutun bir rengi" },
    { word: "Kahverengi", fullWord: "Kahverengi", clue: "Toprağın rengi" },
    { word: "Lacivert", fullWord: "Lacivert", clue: "Koyu mavi" },
    { word: "Bir", fullWord: "Bir", clue: "En küçük sayma sayısı" },
    { word: "İki", fullWord: "İki", clue: "Birden sonra gelen sayı" },
    { word: "Üç", fullWord: "Üç", clue: "İkiden sonra gelen sayı" },
    { word: "Dört", fullWord: "Dört", clue: "Üçten sonra gelen sayı" },
    { word: "Beş", fullWord: "Beş", clue: "Dörtten sonra gelen sayı" },
    { word: "Altı", fullWord: "Altı", clue: "Beşten sonra gelen sayı" },
    { word: "Yedi", fullWord: "Yedi", clue: "Altıdan sonra gelen sayı" },
    { word: "Sekiz", fullWord: "Sekiz", clue: "Yediden sonra gelen sayı" },
    { word: "Dokuz", fullWord: "Dokuz", clue: "Sekizden sonra gelen sayı" },
    { word: "On", fullWord: "On", clue: "Dokuzdan sonra gelen sayı" },
    { word: "Yirmi", fullWord: "Yirmi", clue: "İki tane onluk" },
    { word: "Otuz", fullWord: "Otuz", clue: "Üç tane onluk" },
    { word: "Kırk", fullWord: "Kırk", clue: "Dört tane onluk" },
    { word: "Elli", fullWord: "Elli", clue: "Beş tane onluk" },
    { word: "Yüz", fullWord: "Yüz", clue: "On tane onluk" },
    { word: "Sıfır", fullWord: "Sıfır", clue: "Yokluk belirten sayı" },
    { word: "Doktor", fullWord: "Doktor", clue: "Hstları tedavi eden" },
    { word: "Hemşire", fullWord: "Hemşire", clue: "Doktorun yardımcısı" },
    { word: "Polis", fullWord: "Polis", clue: "Güvenliğimizi sağlayan" },
    { word: "Asker", fullWord: "Asker", clue: "Vatanımızı koruyan" },
    { word: "İtfaiyeci", fullWord: "İtfaiyeci", clue: "Yangın söndüren" },
    { word: "Aşçı", fullWord: "Aşçı", clue: "Yemek yapan kişi" },
    { word: "Terzi", fullWord: "Terzi", clue: "Elbise diken kişi" },
    { word: "Berber", fullWord: "Berber", clue: "Saç kesen kişi" },
    { word: "Şoför", fullWord: "Şoför", clue: "Araç kullanan kişi" },
    { word: "Pilot", fullWord: "Pilot", clue: "Uçak kullanan kişi" },
    { word: "Kaptan", fullWord: "Kaptan", clue: "Gemi kullanan kişi" },
    { word: "Çiftçi", fullWord: "Çiftçi", clue: "Tarlada çalışan kişi" },
    { word: "Mühendis", fullWord: "Mühendis", clue: "Proje çizen teknik kişi" },
    { word: "Avukat", fullWord: "Avukat", clue: "Haklarımızı savunan kişi" },
    { word: "Yazar", fullWord: "Yazar", clue: "Kitap yazan kişi" },
    { word: "Ressam", fullWord: "Ressam", clue: "Resim yapan kişi" },
    { word: "Müzisyen", fullWord: "Müzisyen", clue: "Müzik yapan kişi" },
    { word: "Sporcu", fullWord: "Sporcu", clue: "Spor yapan kişi" },
    { word: "Bahçıvan", fullWord: "Bahçıvan", clue: "Bahçeye bakan kişi" },
    { word: "Marangoz", fullWord: "Marangoz", clue: "Tahta eşya yapan kişi" },
    { word: "Sözlük", fullWord: "Sözlük", clue: "Kelimelerin anlamının yazdığı kitap" },
    { word: "Ansiklopedi", fullWord: "Ansiklopedi", clue: "Bilgi dolu kalın kitap" },
    { word: "Harita", fullWord: "Harita", clue: "Yeryüzünü gösteren çizim" },
    { word: "Küresel", fullWord: "Küresel", clue: "Dünya şekline benzeyen" },
    { word: "Pusula", fullWord: "Pusula", clue: "Yön bulmaya yarayan alet" },
    { word: "Dürbün", fullWord: "Dürbün", clue: "Uzağı yakın gösteren alet" },
    { word: "Büyüteç", fullWord: "Büyüteç", clue: "Küçüğü büyük gösteren alet" },
    { word: "Hesap", fullWord: "Hesap", clue: "Sayılarla yapılan işlem" },
    { word: "Rakam", fullWord: "Rakam", clue: "Sayıları yazmaya yarayan işaret" },
    { word: "Toplama", fullWord: "Toplama", clue: "Artırma işlemi" },
    { word: "Çıkarma", fullWord: "Çıkarma", clue: "Eksiltme işlemi" },
    { word: "Çarpma", fullWord: "Çarpma", clue: "Katlama işlemi" },
    { word: "Bölme", fullWord: "Bölme", clue: "Paylaştırma işlemi" },
    { word: "Eşittir", fullWord: "Eşittir", clue: "Sonucu gösteren işaret" },
    { word: "Artı", fullWord: "Artı", clue: "Ekleme işareti" },
    { word: "Eksi", fullWord: "Eksi", clue: "Çıkarma işareti" },
    { word: "Nokta", fullWord: "Nokta", clue: "Cümlenin sonuna konur" },
    { word: "Virgül", fullWord: "Virgül", clue: "Sıralı kelimelerin arasına konur" },
    { word: "Soru", fullWord: "Soru", clue: "Cevap almak için sorulur" },
    { word: "Ünlem", fullWord: "Ünlem", clue: "Heyecan veya korku işareti" },
    { word: "Parantez", fullWord: "Parantez", clue: "Ek bilgi ayraç içine alınır" },
    { word: "Tırnak", fullWord: "Tırnak", clue: "Alıntı cümleler içine alınır" },
    { word: "Satır", fullWord: "Satır", clue: "Sayfanın her bir sırası" },
    { word: "Paragraf", fullWord: "Paragraf", clue: "Yazıdaki her bir düşünce grubu" },
    { word: "Başlık", fullWord: "Başlık", clue: "Yazının en üstündeki ad" },
    { word: "Metin", fullWord: "Metin", clue: "Yazılmış olan yazı" },
    { word: "Şiir", fullWord: "Şiir", clue: "Duygulu kısa dizeler" },
    { word: "Dize", fullWord: "Dize", clue: "Şiirin her bir satırı" },
    { word: "Kıta", fullWord: "Kıta", clue: "Şiirin dörtlük bölümü" },
    { word: "Şair", fullWord: "Şair", clue: "Şiir yazan kişi" },
    { word: "Yazar", fullWord: "Yazar", clue: "Kitap yazan kişi" },
    { word: "Okuyucu", fullWord: "Okuyucu", clue: "Kitap okuyan kişi" },
    { word: "Kütüphane", fullWord: "Kütüphane", clue: "Kitapların olduğu bina" },
    { word: "Kitapçı", fullWord: "Kitapçı", clue: "Kitap satılan yer" },
    { word: "Defter", fullWord: "Defter", clue: "Yazı yazdığımız kağıtlar" },
    { word: "Kalem", fullWord: "Kalem", clue: "Yazı yazmaya yarayan araç" },
    { word: "Silgi", fullWord: "Silgi", clue: "Yazıyı silmeye yarayan araç" },
    { word: "Boya", fullWord: "Boya", clue: "Renklendirmeye yarayan madde" },
    { word: "Resim", fullWord: "Resim", clue: "Çizilmiş olan görsel" },
    { word: "Müzik", fullWord: "Müzik", clue: "Duyguları sesle anlatma" },
    { word: "Nota", fullWord: "Nota", clue: "Müzik alfabesi" },
    { word: "Şarkı", fullWord: "Şarkı", clue: "Söylenen müzik eseri" },
    { word: "Konser", fullWord: "Konser", clue: "Müzik dinletisi" },
    { word: "Tiyatro", fullWord: "Tiyatro", clue: "Sahnede oynanan oyun" },
    { word: "Sinema", fullWord: "Sinema", clue: "Film izlenen yer" },
    { word: "Ekran", fullWord: "Ekran", clue: "Görüntülerin çıktığı yer" },
    { word: "Klavye", fullWord: "Klavye", clue: "Bilgisayara yazı yazma tuşları" },
    { word: "Fare", fullWord: "Fare", clue: "Bilgisayar imlecini oynatan alet" },
    { word: "Hoparlör", fullWord: "Hoparlör", clue: "Sesin dışarı verilmesini sağlar" },
    { word: "Kulaklık", fullWord: "Kulaklık", clue: "Sesi kulağımıza ileten alet" },
    { word: "Tablet", fullWord: "Tablet", clue: "Küçük dokunmatik bilgisayar" },
    { word: "Telefon", fullWord: "Telefon", clue: "Haberleşmeyi sağlayan alet" },
    { word: "İnternet", fullWord: "İnternet", clue: "Dünya çapındaki bilgi ağı" },
    { word: "Oyun", fullWord: "Oyun", clue: "Eğlenmek için yapılan etkinlik" },
    { word: "Park", fullWord: "Park", clue: "Oyun oynanan açık alan" },
    { word: "Bahçe", fullWord: "Bahçe", clue: "Evin yanındaki toprak alan" },
    { word: "Orman", fullWord: "Orman", clue: "Ağaçların çok olduğu yer" },
    { word: "Deniz", fullWord: "Deniz", clue: "Çok büyük su kütlesi" },
    { word: "Okyanus", fullWord: "Okyanus", clue: "En büyük su kütlesi" },
    { word: "Göl", fullWord: "Göl", clue: "Etrafı kara ile çevrili su" },
    { word: "Nehir", fullWord: "Nehir", clue: "Akan büyük su kütlesi" },
    { word: "Dere", fullWord: "Dere", clue: "Küçük akarsu" },
    { word: "Dağ", fullWord: "Dağ", clue: "Çok yüksek yer şekli" },
    { word: "Tepe", fullWord: "Tepe", clue: "Küçük yükselti" },
    { word: "Vadi", fullWord: "Vadi", clue: "İki dağ arasındaki çukur alan" },
    { word: "Ova", fullWord: "Ova", clue: "Geniş düzlük alan" },
    { word: "Ada", fullWord: "Ada", clue: "Etrafı sularla çevrili kara" },
    { word: "Kumsal", fullWord: "Kumsal", clue: "Deniz kenarı kumlu yer" },
    { word: "Gökkuşağı", fullWord: "Gökkuşağı", clue: "Yağmur sonrası çıkan renkler" },
    { word: "Bulut", fullWord: "Bulut", clue: "Gökyüzündeki beyaz kümeler" },
    { word: "Güneş", fullWord: "Güneş", clue: "Bize ısı ve ışık veren yıldız" },
    { word: "Ay", fullWord: "Ay", clue: "Dünyanın uydusu" },
    { word: "Yıldız", fullWord: "Yıldız", clue: "Gece parlayan gök cismi" },
    { word: "Gezegen", fullWord: "Gezegen", clue: "Güneş etrafında dönen cisim" },
    { word: "Dünya", fullWord: "Dünya", clue: "Üzerinde yaşadığımız yer" },
    { word: "Uzay", fullWord: "Uzay", clue: "Gök cisimlerinin olduğu boşluk" },
    { word: "Astronot", fullWord: "Astronot", clue: "Uzaya giden kişi" },
    { word: "Roket", fullWord: "Roket", clue: "Uzaya fırlatılan araç" },
    { word: "Uçak", fullWord: "Uçak", clue: "Havada uçan araç" },
    { word: "Helikopter", fullWord: "Helikopter", clue: "Üstünde pervane olan hava aracı" },
    { word: "Balon", fullWord: "Balon", clue: "İçi hava dolu renkli nesne" },
    { word: "Gemi", fullWord: "Gemi", clue: "Denizde giden büyük araç" },
    { word: "Kayık", fullWord: "Kayık", clue: "Küçük deniz aracı" },
    { word: "Vapur", fullWord: "Vapur", clue: "İnsan taşıyan deniz aracı" },
    { word: "Tren", fullWord: "Tren", clue: "Raylarda giden araç" },
    { word: "Otobüs", fullWord: "Otobüs", clue: "Çok yolcu taşıyan kara aracı" },
    { word: "Araba", fullWord: "Araba", clue: "Dört tekerlekli hususi araç" },
    { word: "Bisiklet", fullWord: "Bisiklet", clue: "İki tekerlekli pedallı araç" },
    { word: "Motosiklet", fullWord: "Motosiklet", clue: "Motorlu iki tekerlekli araç" },
    { word: "Kamyon", fullWord: "Kamyon", clue: "Yük taşıyan büyük araç" },
    { word: "Traktör", fullWord: "Traktör", clue: "Tarlada çalışan araç" },
    { word: "Ev", fullWord: "Ev", clue: "Yaşadığımız bina" },
    { word: "Bina", fullWord: "Bina", clue: "Yüksek taş yapı" },
    { word: "Apartman", fullWord: "Apartman", clue: "Çok katlı bina" },
    { word: "Sokak", fullWord: "Sokak", clue: "Evlerin arasındaki yol" },
    { word: "Cadde", fullWord: "Cadde", clue: "Geniş ana yol" },
    { word: "Şehir", fullWord: "Şehir", clue: "Yerleşimin olduğu büyük yer" },
    { word: "Köy", fullWord: "Köy", clue: "Yerleşimin olduğu küçük yer" },
    { word: "Ülke", fullWord: "Ülke", clue: "Vatanımız olan büyük kara" },
    { word: "Dünya", fullWord: "Dünya", clue: "Sürekli döndüğümüz yer" },
    { word: "Kapı", fullWord: "Kapı", clue: "İçeri girmeye yarayan yer" },
    { word: "Pencere", fullWord: "Pencere", clue: "Dışarıyı görmeye yarayan yer" },
    { word: "Masa", fullWord: "Masa", clue: "Üstünde yemek yenilen eşya" },
    { word: "Sandalye", fullWord: "Sandalye", clue: "Üstüne oturulan eşya" },
    { word: "Koltuk", fullWord: "Koltuk", clue: "Yumuşak oturma eşyası" },
    { word: "Yatak", fullWord: "Yatak", clue: "Üstünde uyunan eşya" },
    { word: "Yastık", fullWord: "Yastık", clue: "Başımızı koyduğumuz yumuşak nesne" },
    { word: "Yorgan", fullWord: "Yorgan", clue: "Üstümüze örttüğümüz örtü" },
    { word: "Battaniye", fullWord: "Battaniye", clue: "Isınmaya yarayan örtü" },
    { word: "Lamba", fullWord: "Lamba", clue: "Işık vermeye yarayan alet" },
    { word: "Televizyon", fullWord: "Televizyon", clue: "Haber ve film izlenen eşya" },
    { word: "Buzdolabı", fullWord: "Buzdolabı", clue: "Yiyecekleri soğuk tutan eşya" },
    { word: "Fırın", fullWord: "Fırın", clue: "Yemek pişirilen sıcak eşya" },
    { word: "Ocak", fullWord: "Ocak", clue: "Yemek pişirilen ateşli yer" },
    { word: "Musluk", fullWord: "Musluk", clue: "Suyun aktığı yer" },
    { word: "Sabun", fullWord: "Sabun", clue: "Temizlenmeye yarayan madde" },
    { word: "Şampuan", fullWord: "Şampuan", clue: "Saç yıkamaya yarayan sıvı" },
    { word: "Havlu", fullWord: "Havlu", clue: "Kurulanmaya yarayan örtü" },
    { word: "Ayna", fullWord: "Ayna", clue: "Kendimize baktığımız parlak yüzey" },
    { word: "Tarak", fullWord: "Tarak", clue: "Saçı düzeltmeye yarayan alet" },
    { word: "Fırça", fullWord: "Fırça", clue: "Temizleme veya boyama aleti" },
    { word: "Süpürge", fullWord: "Süpürge", clue: "Yeri temizlemeye yarayan alet" },
    { word: "Kova", fullWord: "Kova", clue: "Su taşımaya yarayan kap" },
    { word: "Bardak", fullWord: "Bardak", clue: "Su içilen kap" },
    { word: "Tabak", fullWord: "Tabak", clue: "Yemek yenilen kap" },
    { word: "Kaşık", fullWord: "Kaşık", clue: "Sulu yemek yenilen alet" },
    { word: "Çatal", fullWord: "Çatal", clue: "Yemek batırılan alet" },
    { word: "Bıçak", fullWord: "Bıçak", clue: "Kesmeye yarayan alet" },
    { word: "Tencere", fullWord: "Tencere", clue: "Yemek pişirilen kap" },
    { word: "Tava", fullWord: "Tava", clue: "Kızartma yapılan kap" },
    { word: "Çaydanlık", fullWord: "Çaydanlık", clue: "Çay demlenen eşya" },
    { word: "Kahve", fullWord: "Kahve", clue: "Sıcak içilen bir içecek" },
    { word: "Şeker", fullWord: "Şeker", clue: "Tatlı olan madde" },
    { word: "Tuz", fullWord: "Tuz", clue: "Tuzlu olan beyaz madde" },
    { word: "Biber", fullWord: "Biber", clue: "Acı olan sebze" },
    { word: "Soğan", fullWord: "Soğan", clue: "Yemeklere konan acı sebze" },
    { word: "Sarımsak", fullWord: "Sarımsak", clue: "Güçlü kokusu olan sebze" },
    { word: "Patates", fullWord: "Patates", clue: "Kızartması sevilen sebze" },
    { word: "Domates", fullWord: "Domates", clue: "Kırmızı yuvarlak sebze" },
    { word: "Salatalık", fullWord: "Salatalık", clue: "Yeşil uzun sebze" },
    { word: "Marul", fullWord: "Marul", clue: "Yeşil yapraklı sebze" },
    { word: "Havuç", fullWord: "Havuç", clue: "Turuncu uzun sebze" },
    { word: "Elma", fullWord: "Elma", clue: "Kırmızı tatlı meyve" },
    { word: "Armut", fullWord: "Armut", clue: "Sarı tatlı meyve" },
    { word: "Muz", fullWord: "Muz", clue: "Uzun sarı tatlı meyve" },
    { word: "Çilek", fullWord: "Çilek", clue: "Kırmızı küçük benekli meyve" },
    { word: "Kiraz", fullWord: "Kiraz", clue: "Kırmızı saplı meyve" },
    { word: "Üzüm", fullWord: "Üzüm", clue: "Salkımlı küçük meyve" },
    { word: "Karpuz", fullWord: "Karpuz", clue: "Dışı yeşil içi kırmızı büyük meyve" },
    { word: "Kavun", fullWord: "Kavun", clue: "Sarı kokulu büyük meyve" },
    { word: "Portakal", fullWord: "Portakal", clue: "Turuncu kış meyvesi" },
    { word: "Limon", fullWord: "Limon", clue: "Sarı ekşi meyve" },
    { word: "Ekmek", fullWord: "Ekmek", clue: "En temel gıda maddesi" },
    { word: "Süt", fullWord: "Süt", clue: "Beyaz besleyici içecek" },
    { word: "Yoğurt", fullWord: "Yoğurt", clue: "Sütten yapılan beyaz yiyecek" },
    { word: "Peynir", fullWord: "Peynir", clue: "Kahvaltıda yenilen süt ürünü" },
    { word: "Zeytin", fullWord: "Zeytin", clue: "Dalından toplanan küçük kahvaltılık" },
    { word: "Bal", fullWord: "Bal", clue: "Arıların yaptığı tatlı yiyecek" },
    { word: "Yumurta", fullWord: "Yumurta", clue: "Tavukların yaptığı yiyecek" },
    { word: "Et", fullWord: "Et", clue: "Hayvanlardan elde edilen gıda" },
    { word: "Balık", fullWord: "Balık", clue: "Suda yaşayan yenilen canlı" },
    { word: "Tavuk", fullWord: "Tavuk", clue: "Kümes hayvanı olan gıda" },
    { word: "Pilav", fullWord: "Pilav", clue: "Pirinçten yapılan yemek" },
    { word: "Makarna", fullWord: "Makarna", clue: "Hamurdan yapılan sevilen yemek" },
    { word: "Çorba", fullWord: "Çorba", clue: "Sıcak içilen sulu yemek" },
    { word: "Salata", fullWord: "Salata", clue: "Sebzelerle yapılan karışım" },
    { word: "Pasta", fullWord: "Pasta", clue: "Doğum gününde yenen tatlı" },
    { word: "Bisküvi", fullWord: "Bisküvi", clue: "Çıtır tatlı yiyecek" },
    { word: "Çikolata", fullWord: "Çikolata", clue: "En sevilen kahverengi tatlı" },
    { word: "Dondurma", fullWord: "Dondurma", clue: "Yazın yenen soğuk tatlı" },
    { word: "Gömlek", fullWord: "Gömlek", clue: "Düğmeli giysi" },
    { word: "Pantolon", fullWord: "Pantolon", clue: "Bacağa giyilen giysi" },
    { word: "Etek", fullWord: "Etek", clue: "Kızların giydiği giysi" },
    { word: "Elbise", fullWord: "Elbise", clue: "Tek parça kadın giysisi" },
    { word: "Ceket", fullWord: "Ceket", clue: "Üste giyilen kalın giysi" },
    { word: "Palto", fullWord: "Palto", clue: "Kışın giyilen çok kalın giysi" },
    { word: "Kazak", fullWord: "Kazak", clue: "Yünden yapılan giysi" },
    { word: "Hırka", fullWord: "Hırka", clue: "Önü açık yün giysi" },
    { word: "Şapka", fullWord: "Şapka", clue: "Başa takılan aksesuar" },
    { word: "Atkı", fullWord: "Atkı", clue: "Boyuna sarılan yün örtü" },
    { word: "Eldiven", fullWord: "Eldiven", clue: "Ele takılan giysi" },
    { word: "Çorap", fullWord: "Çorap", clue: "Ayağa giyilen koruyucu" },
    { word: "Ayakkabı", fullWord: "Ayakkabı", clue: "Dışarıda ayağımıza giydiğimiz" },
    { word: "Terlik", fullWord: "Terlik", clue: "Evde ayağımıza giydiğimiz" },
    { word: "Çizme", fullWord: "Çizme", clue: "Yağmurda giyilen uzun ayakkabı" },
    { word: "Düğme", fullWord: "Düğme", clue: "Giysileri kapatmaya yarayan nesne" },
    { word: "Fermuar", fullWord: "Fermuar", clue: "Çekilerek kapanan düzenek" },
    { word: "Kemer", fullWord: "Kemer", clue: "Pantolonu tutmaya yarayan aksesuar" },
    { word: "Gözlük", fullWord: "Gözlük", clue: "İyi görmemizi sağlayan araç" },
    { word: "Saat", fullWord: "Saat", clue: "Zamanı gösteren araç" },
    { word: "Cüzdan", fullWord: "Cüzdan", clue: "Para konulan küçük çanta" },
    { word: "Çanta", fullWord: "Çanta", clue: "Eşyaları taşımaya yarayan nesne" },
    { word: "Şemsiye", fullWord: "Şemsiye", clue: "Yağmurdan koruyan araç" },
    { word: "Öğrenci", fullWord: "Öğrenci", clue: "Okula gidip ders çalışan" },
    { word: "Sınıf", fullWord: "Sınıf", clue: "Ders işlenen oda" },
    { word: "Sıra", fullWord: "Sıra", clue: "Okulda üzerine oturulan eşya" },
    { word: "Tahta", fullWord: "Tahta", clue: "Öğretmenin yazı yazdığı yer" },
    { word: "Tebeşir", fullWord: "Tebeşir", clue: "Tahtaya yazı yazmaya yarayan taş" },
    { word: "Kapak", fullWord: "Kapak", clue: "Şişenin veya kabın üstü" },
    { word: "Kutu", fullWord: "Kutu", clue: "İçine eşya konan nesne" },
    { word: "Sepet", fullWord: "Sepet", clue: "Örme taşıma aracı" },
    { word: "Torba", fullWord: "Torba", clue: "Plastik veya bez taşıma nesnesi" }
];
