import { KelimeTamamlamaItem } from '../../types/kelimeCumle';

export const KELIME_TAMAMLAMA_SOURCES: KelimeTamamlamaItem[] = [
    { word: "Silgi", fullWord: "Silgi", clue: "Silmeye yarayan ders aracı" },
    { word: "İnek", fullWord: "İnek", clue: "Süt veren hayvan" },
    { word: "Horoz", fullWord: "Horoz", clue: "Kümeste yaşar" },
    { word: "Halı", fullWord: "Halı", clue: "Evde yere sereriz" },
    { word: "Gözlük", fullWord: "Gözlük", clue: "Gözümüze takarız" },
    { word: "Gazete", fullWord: "Gazete", clue: "Okuruz" },
    { word: "Ekmek", fullWord: "Ekmek", clue: "Yemekte yeriz" },
    { word: "Domuz", fullWord: "Domuz", clue: "Bir hayvan" },
    { word: "Çorba", fullWord: "Çorba", clue: "Yemekte içeriz" },
    { word: "Çilek", fullWord: "Çilek", clue: "Bir meyve adı" },
    { word: "Cüzdan", fullWord: "Cüzdan", clue: "İçine para koyarız" },
    { word: "Cetvel", fullWord: "Cetvel", clue: "Çizgi çizeriz" },
    { word: "Bıçak", fullWord: "Bıçak", clue: "Kesme aracı" },
    { word: "Ayran", fullWord: "Ayran", clue: "Beyaz bir içecek" },
    { word: "Bakkal", fullWord: "Bakkal", clue: "Alışveriş yapılan yer" },
    { word: "Bardak", fullWord: "Bardak", clue: "Su içeriz" },
    { word: "Yağmur", fullWord: "Yağmur", clue: "Gökyüzünden yağar" },
    { word: "Toka", fullWord: "Toka", clue: "Kızlar saçına takar" },
    { word: "Telefon", fullWord: "Telefon", clue: "Konuşuruz" },
    { word: "Tavuk", fullWord: "Tavuk", clue: "Bir hayvan" },
    { word: "Salı", fullWord: "Salı", clue: "Haftanın bir günü" },
    { word: "Şeftali", fullWord: "Şeftali", clue: "Bir meyve" },
    { word: "Şapka", fullWord: "Şapka", clue: "Başımıza giyeriz" },
    { word: "Sucuk", fullWord: "Sucuk", clue: "Bir yiyecek" },
    { word: "Simit", fullWord: "Simit", clue: "Unlu bir yiyecek" },
    { word: "Sabun", fullWord: "Sabun", clue: "Ellerimizi yıkarız" },
    { word: "Pusula", fullWord: "Pusula", clue: "Yönleri gösterir" },
    { word: "Portakal", fullWord: "Portakal", clue: "Bir meyve" },
    { word: "Pilav", fullWord: "Pilav", clue: "Bir yemek adı" },
    { word: "Peynir", fullWord: "Peynir", clue: "Kahvaltıda yeriz" },
    { word: "Pasta", fullWord: "Pasta", clue: "Doğum gününde yeriz" },
    { word: "Öğretmen", fullWord: "Öğretmen", clue: "Sınıfta ders anlatır" },
    { word: "Orman", fullWord: "Orman", clue: "Çok ağaç olan yer" },
    { word: "Olta", fullWord: "Olta", clue: "Balık tutarız" },
    { word: "Müdür", fullWord: "Müdür", clue: "Okulu yönetir" },
    { word: "Mutfak", fullWord: "Mutfak", clue: "Evin bir bölümü" },
    { word: "Makas", fullWord: "Makas", clue: "Kağıt kesme aracı" },
    { word: "Limon", fullWord: "Limon", clue: "Sarı renkli ekşi bir meyve" },
    { word: "Leylek", fullWord: "Leylek", clue: "Uçan büyük bir hayvan" },
    { word: "Lamba", fullWord: "Lamba", clue: "Işık verir" },
    { word: "Küpe", fullWord: "Küpe", clue: "Kızlar kulağa takar" }
];
