import { TestItem } from '../../types/kelimeCumle';

export const TEST_SOURCES: TestItem[] = [
    { question: "İbrahim fırından …… taze …… simit aldı.", options: ["yaşlı", "taze", "spor", "hasta"], answer: "taze" },
    { question: "Dedem tarlaya …… ekti.", options: ["yorgan", "şimşek", "balık", "buğday"], answer: "buğday" },
    { question: "Dün akşam …… kar …… yağdı.", options: ["fiş", "tişört", "defter", "kar"], answer: "kar" },
    { question: "Hatice kümesteki …… yem verdi.", options: ["yoğurtlara", "kazaklara", "aslanlara", "horozlara"], answer: "horozlara" },
    { question: "Dayım ağaçları …… ile kesti.", options: ["kilit", "şişe", "makas", "balta"], answer: "balta" },
    { question: "Mustafa bavula …… koydu.", options: ["halı", "elbise", "soba", "ahtapot"], answer: "elbise" },
    { question: "Arabanın …… bitti.", options: ["benzini", "çadırı", "kömürü", "örtüsü"], answer: "benzini" },
    { question: "Banyodan sonra …… giydim.", options: ["cımbız", "perde", "kilim", "bornoz"], answer: "bornoz" },
    { question: "Paralarımı …… koydum.", options: ["internete", "cüzdana", "tokama", "klimaya"], answer: "cüzdana" },
    { question: "Gökhan, hasta arkadaşına …… dedi.", options: ["iyi geceler", "kolay gelsin", "günaydın", "geçmiş olsun"], answer: "geçmiş olsun" },
    { question: "Meral manavdan …… aldı.", options: ["perde", "kağıt", "terlik", "pırasa"], answer: "pırasa" },
    { question: "Ömer bugün yirmi …… kitap okudu.", options: ["takvim", "yunus", "sayfa", "toka"], answer: "sayfa" },
    { question: "Yağmur yağınca …… açtım.", options: ["şemsiyemi", "dosyamı", "çatıyı", "kilimi"], answer: "şemsiyemi" },
    { question: "Pazar günü arkadaşımla …… gittik.", options: ["hırka", "sürahiye", "ödeve", "sinemaya"], answer: "sinemaya" },
    { question: "Fenerbahçe-Galatasaray …… izledim.", options: ["maçını", "kumanda", "ehliyet", "döneri"], answer: "maçını" },
    { question: "Babam Kurban Bayramında …… kesti.", options: ["çekirdek", "yunus", "koyun", "maymun"], answer: "koyun" },
    { question: "Fatih pazar günü toprağa …… dikti.", options: ["fidan", "traktör", "sepet", "fiş"], answer: "fidan" },
    { question: "Babamın kız kardeşine …… derim.", options: ["kuzen", "enişte", "yenge", "hala"], answer: "hala" },
    { question: "Dedem camide …… kıldı.", options: ["banka", "kivi", "namaz", "hediye"], answer: "namaz" },
    { question: "Bayramda ninem bana …… verdi.", options: ["saman", "şeker", "yastık", "kalorifer"], answer: "şeker" },
    { question: "Akşam televizyonda …… seyrettim.", options: ["vagon", "süpürge", "banyo", "film"], answer: "film" },
    { question: "Arabanın lastiği …… .", options: ["patladı", "hasta oldu", "koştu", "ağladı"], answer: "patladı" },
    { question: "Çorbanın içine …… attım.", options: ["kum", "taş", "tuz", "hap"], answer: "tuz" },
    { question: "Çocuklar …… uçuruyor.", options: ["kabak", "tencere", "balina", "uçurtma"], answer: "uçurtma" },
    { question: "Fatma evde annesine …… etti.", options: ["hasta", "yardım", "spor", "rüya"], answer: "yardım" },
    { question: "Ömer mendil ile …… sildi.", options: ["yolunu", "ödevini", "burnunu", "kalbini"], answer: "burnunu" },
    { question: "Arabalar …… ışık yanınca geçti.", options: ["yeşil", "mavi", "sarı", "pembe"], answer: "yeşil" },
    { question: "Pazar günü pikniğe gittik, …… yaktık.", options: ["fındık", "toprak", "benzin", "mangal"], answer: "mangal" },
    { question: "Akvaryumun içinde …… yüzüyor.", options: ["laleler", "kargalar", "çekirgeler", "balıklar"], answer: "balıklar" },
    { question: "Dün tren ile …… gittik.", options: ["perdeye", "yaprağa", "İzmir’e", "masala"], answer: "İzmir’e" },
    { question: "Amcam balta ile …… kesti.", options: ["ağacı", "tokayı", "gömleğe", "mektuba"], answer: "ağacı" },
    { question: "En çok sevdiğim meslek …… .", options: ["grup", "doktor", "yastık", "metre"], answer: "doktor" }
];
