import { TestItem } from '../../types/kelimeCumle';

export const TEST_SOURCES: TestItem[] = [
    { question: "İbrahim fırından …… taze …… simit aldı.", options: ["yaşlı", "taze", "spor", "hasta"], answer: "taze" },
    { question: "Dedem tarlaya …… ekti.", options: ["yorgan", "şimşek", "balık", "buğday"], answer: "buğday" },
    { question: "Dün akşam …… kar …… yağdı.", options: ["fiş", "tişört", "defter", "kar"], answer: "kar" },
    { question: "Hatice kümesteki …… yem verdi.", options: ["yoğurtlara", "kazaklara", "aslanlara", "horozlara"], answer: "horozlara" },
    { question: "Dayım ağaçları …… ile kesti.", options: ["kilit", "şişe", "makas", "balta"], answer: "balta" },
    { question: "Mustafa bavula …… koydu.", options: ["halı", "elbise", "soba", "ahtapot"], answer: "elbise" },
    { question: "Arabanın …… bitti.", options: ["benzini", "çadırı", "kömürü", "örtüsü"], answer: "benzini" },
    { question: "Banyodan sonra …… giydim.", options: ["cımbız", "perde", "kilim", "bornoz"], answer: "bornoz" },
    { question: "Paralarımı …… koydum.", options: ["internete", "cüzdana", "tokama", "klimaya"], answer: "cüzdana" },
    { question: "Gökhan, hasta arkadaşına …… dedi.", options: ["iyi geceler", "kolay gelsin", "günaydın", "geçmiş olsun"], answer: "geçmiş olsun" },
    { question: "Meral manavdan …… aldı.", options: ["perde", "kağıt", "terlik", "pırasa"], answer: "pırasa" },
    { question: "Ömer bugün yirmi …… kitap okudu.", options: ["takvim", "yunus", "sayfa", "toka"], answer: "sayfa" },
    { question: "Yağmur yağınca …… açtım.", options: ["şemsiyemi", "dosyamı", "çatıyı", "kilimi"], answer: "şemsiyemi" },
    { question: "Pazar günü arkadaşımla …… gittik.", options: ["hırka", "sürahiye", "ödeve", "sinemaya"], answer: "sinemaya" },
    { question: "Fenerbahçe-Galatasaray …… izledim.", options: ["maçını", "kumanda", "ehliyet", "döneri"], answer: "maçını" },
    { question: "Babam Kurban Bayramında …… kesti.", options: ["çekirdek", "yunus", "koyun", "maymun"], answer: "koyun" },
    { question: "Fatih pazar günü toprağa …… dikti.", options: ["fidan", "traktör", "sepet", "fiş"], answer: "fidan" },
    { question: "Babamın kız kardeşine …… derim.", options: ["kuzen", "enişte", "yenge", "hala"], answer: "hala" },
    { question: "Dedem camide …… kıldı.", options: ["banka", "kivi", "namaz", "hediye"], answer: "namaz" },
    { question: "Bayramda ninem bana …… verdi.", options: ["saman", "şeker", "yastık", "kalorifer"], answer: "şeker" },
    { question: "Akşam televizyonda …… seyrettim.", options: ["vagon", "süpürge", "banyo", "film"], answer: "film" },
    { question: "Arabanın lastiği …… .", options: ["patladı", "hasta oldu", "koştu", "ağladı"], answer: "patladı" },
    { question: "Çorbanın içine …… attım.", options: ["kum", "taş", "tuz", "hap"], answer: "tuz" },
    { question: "Çocuklar …… uçuruyor.", options: ["kabak", "tencere", "balina", "uçurtma"], answer: "uçurtma" },
    { question: "Fatma evde annesine …… etti.", options: ["hasta", "yardım", "spor", "rüya"], answer: "yardım" },
    { question: "Ömer mendil ile …… sildi.", options: ["yolunu", "ödevini", "burnunu", "kalbini"], answer: "burnunu" },
    { question: "Arabalar …… ışık yanınca geçti.", options: ["yeşil", "mavi", "sarı", "pembe"], answer: "yeşil" },
    { question: "Pazar günü pikniğe gittik, …… yaktık.", options: ["fındık", "toprak", "benzin", "mangal"], answer: "mangal" },
    { question: "Akvaryumun içinde …… yüzüyor.", options: ["laleler", "kargalar", "çekirgeler", "balıklar"], answer: "balıklar" },
    { question: "Dün tren ile …… gittik.", options: ["perdeye", "yaprağa", "İzmir’e", "masala"], answer: "İzmir’e" },
    { question: "Amcam balta ile …… kesti.", options: ["ağacı", "tokayı", "gömleğe", "mektuba"], answer: "ağacı" },
    { question: "En çok sevdiğim meslek …… .", options: ["grup", "doktor", "yastık", "metre"], answer: "doktor" },
    { question: "Kitap okumayı çok …… .", options: ["içerim", "koşarım", "severim", "uyurum"], answer: "severim" },
    { question: "Sabah kahvaltısında …… yedim.", options: ["kömür", "zeytin", "kum", "kağıt"], answer: "zeytin" },
    { question: "Gökyüzünde parlak …… parlıyor.", options: ["toprak", "yıldız", "taş", "çiçek"], answer: "yıldız" },
    { question: "Denizde …… yüzüyor.", options: ["tavuklar", "gemiler", "inekler", "aslanlar"], answer: "gemiler" },
    { question: "Kırmızı …… yanınca durmalıyız.", options: ["lamba", "ışık", "ayna", "masa"], answer: "ışık" },
    { question: "Meyveleri yemeden önce …… .", options: ["boyamalıyız", "yıkamalıyız", "kırmalıyız", "atmalıyız"], answer: "yıkamalıyız" },
    { question: "Pazardan iki kilo …… aldım.", options: ["elbise", "muz", "defter", "bardak"], answer: "muz" },
    { question: "Kışın …… giyeriz.", options: ["tişört", "kazak", "mayo", "terlik"], answer: "kazak" },
    { question: "Uçak …… uçar.", options: ["denizde", "havada", "yolda", "yerde"], answer: "havada" },
    { question: "Tren …… üzerinde gider.", options: ["suyun", "rayların", "çimenin", "kumun"], answer: "rayların" },
    { question: "Arılar …… yapar.", options: ["peynir", "bal", "süt", "yoğurt"], answer: "bal" },
    { question: "İnekler bize …… verir.", options: ["su", "süt", "çay", "meyve suyu"], answer: "süt" },
    { question: "Tavuklar …… yumurtlar.", options: ["elma", "yumurta", "taş", "şeker"], answer: "yumurta" },
    { question: "Elimizi …… ile yıkamalıyız.", options: ["tuz", "sabun", "şeker", "un"], answer: "sabun" },
    { question: "Dişlerimizi …… ile fırçalarız.", options: ["kaşık", "fırça", "kalem", "çatal"], answer: "fırça" },
    { question: "Okula …… ile giderim.", options: ["gemi", "servis", "uçak", "helikopter"], answer: "servis" },
    { question: "Öğretmen …… ders anlatır.", options: ["bahçede", "sınıfta", "mutfakta", "banyoda"], answer: "sınıfta" },
    { question: "Doktor …… tedavi eder.", options: ["oyuncakları", "hastaları", "çiçekleri", "taşları"], answer: "hastaları" },
    { question: "Pilot …… kullanır.", options: ["araba", "uçak", "bisiklet", "traktör"], answer: "uçak" },
    { question: "Aşçı …… yapar.", options: ["resim", "yemek", "ayakkabı", "ev"], answer: "yemek" },
    { question: "Terzi …… diker.", options: ["ekmek", "elbise", "duvar", "yol"], answer: "elbise" },
    { question: "İtfaiyeci …… söndürür.", options: ["lambayı", "yangını", "güneşi", "yıldızı"], answer: "yangını" },
    { question: "Postacı …… getirir.", options: ["ekmek", "mektup", "meyve", "su"], answer: "mektup" },
    { question: "Baklava …… bir tatlıdır.", options: ["tuzlu", "tatlı", "ekşi", "acı"], answer: "tatlı" },
    { question: "Limon …… bir meyvedir.", options: ["tatlı", "ekşi", "tuzlu", "acı"], answer: "ekşi" },
    { question: "Biber …… olabilir.", options: ["yumuşak", "acı", "tatlı", "ekşi"], answer: "acı" },
    { question: "Yaz mevsimi çok …… geçer.", options: ["soğuk", "sıcak", "karlı", "fırtınalı"], answer: "sıcak" },
    { question: "Kış mevsiminde …… yağar.", options: ["güneş", "kar", "çiçek", "kum"], answer: "kar" },
    { question: "İlkbaharda …… açar.", options: ["kar", "çiçekler", "soba", "buz"], answer: "çiçekler" },
    { question: "Sonbaharda yapraklar …… .", options: ["açar", "sararır", "donar", "yanar"], answer: "sararır" },
    { question: "Bir yılda …… mevsim vardır.", options: ["iki", "dört", "altı", "on"], answer: "dört" },
    { question: "Haftanın ilk günü …… .", options: ["Cuma", "Pazartesi", "Salı", "Pazar"], answer: "Pazartesi" },
    { question: "Tatil günleri …… .", options: ["Salı-Çarşamba", "Cumartesi-Pazar", "Pazartesi-Salı", "Perşembe-Cuma"], answer: "Cumartesi-Pazar" },
    { question: "Ay gökyüzünde …… görülür.", options: ["gündüz", "gece", "sabah", "öğlen"], answer: "gece" },
    { question: "Yıldızlar …… parlar.", options: ["bulutta", "gece", "toprakta", "denizde"], answer: "gece" },
    { question: "Güneş …… doğar.", options: ["batıdan", "doğudan", "kuzeyden", "güneyden"], answer: "doğudan" },
    { question: "Yağmur yağınca …… ıslanır.", options: ["güneş", "yerler", "bulutlar", "yıldızlar"], answer: "yerler" },
    { question: "Rüzgar esince …… sallanır.", options: ["taşlar", "ağaçlar", "dağlar", "yollar"], answer: "ağaçlar" },
    { question: "Gökkuşağı …… renklidir.", options: ["tek", "çok", "iki", "sıfır"], answer: "çok" },
    { question: "Karabaş benim …… adıdır.", options: ["kedimin", "köpeğimin", "kuşumun", "balığımın"], answer: "köpeğimin" },
    { question: "Pamuk benim …… adıdır.", options: ["aslanımın", "kedimin", "ayıcığımın", "zürafamın"], answer: "kedimin" },
    { question: "Balıklar …… nefes alır.", options: ["akciğerle", "solungaçla", "burunla", "ağızla"], answer: "solungaçla" },
    { question: "Kuşlar …… yapar.", options: ["ev", "yuva", "mağara", "saray"], answer: "yuva" },
    { question: "Arslan ormanların …… .", options: ["hizmetçisidir", "kralıdır", "çocuğudur", "misafiridir"], answer: "kralıdır" },
    { question: "Zürafa …… bir hayvandır.", options: ["kısa", "uzun", "küçük", "zayıf"], answer: "uzun" },
    { question: "Filin …… çok uzundur.", options: ["kuyruğu", "hortumu", "kulağı", "ayağı"], answer: "hortumu" },
    { question: "Maymunlar …… yemeyi sever.", options: ["et", "muz", "taş", "ot"], answer: "muz" },
    { question: "Tavşan …… çok hızlı koşar.", options: ["kaplumbağadan", "aslandan", "filden", "ayıdan"], answer: "kaplumbağadan" },
    { question: "Yılan …… ilerler.", options: ["koşarak", "sürünerek", "uçarak", "yüzerek"], answer: "sürünerek" },
    { question: "Kurbağa …… .", options: ["öter", "zıplar", "uçar", "koşar"], answer: "zıplar" },
    { question: "Ördekler vak vak …… .", options: ["konuşur", "der", "ağlar", "güler"], answer: "der" },
    { question: "Arı vız vız …… .", options: ["gezer", "eder", "uyur", "yer"], answer: "eder" },
    { question: "Ekmek …… yapılır.", options: ["sütle", "undan", "şekerden", "tuzdan"], answer: "undan" },
    { question: "Peynir …… yapılır.", options: ["sudan", "sütten", "meyveden", "sebzeden"], answer: "sütten" },
    { question: "Yoğurt …… bir yiyecektir.", options: ["beyaz", "kırmızı", "mavi", "yeşil"], answer: "beyaz" },
    { question: "Yumurta …… alınır.", options: ["marketten", "kümesten", "tarladan", "bahçeden"], answer: "kümesten" },
    { question: "Elma …… bir meyvedir.", options: ["sebze", "meyve", "et", "süt"], answer: "meyve" },
    { question: "Ispanak …… bir sebzedir.", options: ["meyve", "sebze", "tatlı", "içecek"], answer: "sebze" },
    { question: "Su …… bir ihtiyaçtır.", options: ["gereksiz", "temel", "pahalı", "zor"], answer: "temel" },
    { question: "Çay …… içilir.", options: ["soğuk", "sıcak", "donmuş", "katı"], answer: "sıcak" },
    { question: "Dondurma …… yenir.", options: ["sıcak", "soğuk", "pişmiş", "haşlanmış"], answer: "soğuk" },
    { question: "Çorba …… içilir.", options: ["çatalla", "kaşıkla", "bıçakla", "elle"], answer: "kaşıkla" },
    { question: "Et …… ile kesilir.", options: ["kaşıkla", "bıçakla", "çatalla", "bardakla"], answer: "bıçakla" },
    { question: "Makarna …… çok sevilir.", options: ["çocuklarca", "taşlarca", "ağaçlarca", "yollarca"], answer: "çocuklarca" },
    { question: "Pizza …… bir yiyecektir.", options: ["yuvarlak", "kare", "çizgi", "nokta"], answer: "yuvarlak" },
    { question: "Sandviç …… hazırlanır.", options: ["hızlıca", "yavaşça", "zorla", "uzun sürede"], answer: "hızlıca" },
    { question: "Okul çantası …… takılır.", options: ["başa", "sirta", "ayağa", "ele"], answer: "sirta" },
    { question: "Kalemlikte …… olur.", options: ["ayakkabı", "kalemler", "çatal", "tabak"], answer: "kalemler" },
    { question: "Deftere …… yazılır.", options: ["boyayla", "yazı", "su", "yemek"], answer: "yazı" },
    { question: "Kitap …… için okunur.", options: ["uyumak", "öğrenmek", "koşmak", "yemek"], answer: "öğrenmek" },
    { question: "Silgi …… siler.", options: ["duvarı", "hatayı", "yazıyı", "yolu"], answer: "yazıyı" },
    { question: "Cetvel …… çizer.", options: ["daire", "düz çizgi", "bulut", "çiçek"], answer: "düz çizgi" },
    { question: "Sınıf başkanı …… seçilir.", options: ["zorla", "oyla", "kavgayla", "şansla"], answer: "oyla" },
    { question: "Okul müdürü okulu …… .", options: ["temizler", "yönetir", "boyar", "yıkar"], answer: "yönetir" },
    { question: "Kütüphane …… doludur.", options: ["taşla", "kitapla", "suyla", "oyuncakla"], answer: "kitapla" },
    { question: "Spor salonunda …… yapılır.", options: ["yemek", "spor", "uyku", "banyo"], answer: "spor" },
    { question: "Bahçede …… oynanır.", options: ["ders", "oyun", "sınav", "kitap"], answer: "oyun" },
    { question: "Kantin …… satılır.", options: ["araba", "yiyecek", "ev", "elbise"], answer: "yiyecek" },
    { question: "Sınıfımız …… .", options: ["karanlıktır", "aydınlıktır", "soğuktur", "boştur"], answer: "aydınlıktır" },
    { question: "Sıralarımızda …… .", options: ["uyuruz", "otururuz", "koşarız", "zıplarız"], answer: "otururuz" },
    { question: "Tahtaya …… ile yazılır.", options: ["suyla", "tebeşirle", "fırçayla", "elle"], answer: "tebeşirle" },
    { question: "Dosyalar …… saklanır.", options: ["yerde", "klasörde", "çantada", "cepte"], answer: "klasörde" },
    { question: "Bilgisayar …… girilir.", options: ["bahçeye", "internete", "mutfağa", "banyoya"], answer: "internete" },
    { question: "Tablet …… bir cihazdır.", options: ["ağır", "elektronik", "canlı", "bitkisel"], answer: "elektronik" },
    { question: "Televizyon …… izlenir.", options: ["dinlenerek", "bakılarak", "koşularak", "uyunarak"], answer: "bakılarak" },
    { question: "Radyo …… dinlenir.", options: ["bakılarak", "kulakla", "elle", "ayakla"], answer: "kulakla" },
    { question: "Gazete …… okunur.", options: ["her gün", "hiç", "yılda bir", "geceleri"], answer: "her gün" },
    { question: "Dergi …… doludur.", options: ["boş", "renkli resimlerle", "taşla", "suyla"], answer: "renkli resimlerle" },
    { question: "Mektup …… gönderilir.", options: ["elle", "postayla", "rüzgarla", "kuşla"], answer: "postayla" },
    { question: "Sinema …… izlenir.", options: ["evde", "salonda", "yolda", "bahçede"], answer: "salonda" },
    { question: "Tiyatro …… sergilenir.", options: ["sahnede", "mutfakta", "banyoda", "yerde"], answer: "sahnede" },
    { question: "Müze …… doludur.", options: ["çöple", "tarihi eserlerle", "oyuncakla", "meyveyle"], answer: "tarihi eserlerle" },
    { question: "Parkta …… sallanır.", options: ["arabalar", "salıncaklar", "evler", "yollar"], answer: "salıncaklar" },
    { question: "Kaydıraktan …… .", options: ["çıkılır", "kayılır", "atlanır", "koşulur"], answer: "kayılır" },
    { question: "Tahterevalli …… oynanır.", options: ["tek başına", "iki kişiyle", "on kişiyle", "hiç"], answer: "iki kişiyle" },
    { question: "Kum havuzunda …… yapılır.", options: ["yemek", "kale", "banyo", "uyku"], answer: "kale" },
    { question: "Top ile …… oynanır.", options: ["kitap", "futbol", "ders", "sınav"], answer: "futbol" },
    { question: "Basketbol …… ile oynanır.", options: ["elle", "ayakla", "başla", "omuzla"], answer: "elle" },
    { question: "Voleybol …… üzerinden atılır.", options: ["duvar", "file", "ip", "çizgi"], answer: "file" },
    { question: "Yüzme …… yapılır.", options: ["yolda", "havuzda", "dağda", "ormanda"], answer: "havuzda" },
    { question: "Koşu …… yapılır.", options: ["yerde", "pistte", "suda", "havada"], answer: "pistte" },
    { question: "Bisiklet …… sürülür.", options: ["yolda", "denizde", "bulutta", "evde"], answer: "yolda" },
    { question: "Paten …… takılır.", options: ["ele", "ayağa", "başa", "bele"], answer: "ayağa" },
    { question: "Kaykay …… üzerinde durulur.", options: ["elle", "ayakla", "dizle", "başla"], answer: "ayakla" },
    { question: "Satranç …… bir oyundur.", options: ["hızlı", "zekâ", "şans", "kaba"], answer: "zekâ" },
    { question: "Dama …… oynanır.", options: ["taşlarla", "topla", "suyla", "ateşle"], answer: "taşlarla" },
    { question: "Saklambaçta …… sayılır.", options: ["on", "yüz", "ebelenene kadar", "hiç"], answer: "ebelenene kadar" },
    { question: "Körebe …… bağlanır.", options: ["eller", "gözler", "ayaklar", "kollar"], answer: "gözler" },
    { question: "Yakar top …… ile oynanır.", options: ["topla", "taşla", "suyla", "sopayla"], answer: "topla" },
    { question: "İp …… .", options: ["atlanır", "yenir", "içilir", "okunur"], answer: "atlanır" },
    { question: "Seksek …… oynanır.", options: ["zıplayarak", "uyuyarak", "koşarak", "uçarak"], answer: "zıplayarak" },
    { question: "Misket …… bir oyundur.", options: ["eski", "yeni", "zor", "pahalı"], answer: "eski" },
    { question: "Uçurtma …… uçar.", options: ["yerde", "gökyüzünde", "suda", "evde"], answer: "gökyüzünde" },
    { question: "Balon …… doludur.", options: ["suyla", "havayla", "taşla", "meyveyle"], answer: "havayla" },
    { question: "Oyuncak bebek …… .", options: ["konuşur", "oynatılır", "yemek yer", "koşar"], answer: "oynatılır" },
    { question: "Oyuncak araba …… .", options: ["sürülür", "uçar", "yüzer", "uyur"], answer: "sürülür" },
    { question: "Lego …… yapılır.", options: ["evler", "yemekler", "kitaplar", "meyveler"], answer: "evler" },
    { question: "Yapboz …… birleştirilir.", options: ["parçalar", "taşlar", "sular", "yollar"], answer: "parçalar" },
    { question: "Boyama …… yapılır.", options: ["kalemlerle", "taşlarla", "sularla", "ekmekle"], answer: "kalemlerle" },
    { question: "Resim …… üzerine çizilir.", options: ["yola", "kağıda", "havaya", "suya"], answer: "kağıda" },
    { question: "Hamur …… oynanır.", options: ["şekil verilerek", "yenerek", "içilerek", "atılarak"], answer: "şekil verilerek" },
    { question: "Kil …… bir malzemedir.", options: ["sert", "yumuşak", "parlak", "şeffaf"], answer: "yumuşak" },
    { question: "Elişi kağıdı …… renklidir.", options: ["tek", "renk renk", "siyah", "beyaz"], answer: "renk renk" },
    { question: "Yapıştırıcı …… .", options: ["ayırır", "birleştirir", "böler", "yakar"], answer: "birleştirir" },
    { question: "Sulu boya …… ile kullanılır.", options: ["suyla", "yağla", "sütle", "tuzla"], answer: "suyla" },
    { question: "Pastel boya …… bir boyadır.", options: ["yağlı", "kuru", "toz", "sıvı"], answer: "kuru" },
    { question: "Kurşun kalem …… uca sahiptir.", options: ["yumuşak", "sert", "siyah", "parlak"], answer: "siyah" },
    { question: "Tükenmez kalem …… .", options: ["biter", "bitmez", "silinir", "akar"], answer: "biter" },
    { question: "Pilot kalem …… yazar.", options: ["kalın", "ince", "mavi", "silik"], answer: "ince" },
    { question: "Dolma kalem …… ile dolar.", options: ["suyla", "mürekkeple", "sütle", "yağla"], answer: "mürekkeple" }
];
