import { StyleSettings } from '../types';

export const initialStyleSettings: StyleSettings = {
  fontSize: 18,
  scale: 1,
  borderColor: '#3f3f46',
  borderWidth: 1,
  margin: 10,
  columns: 1,
  gap: 15,
  orientation: 'portrait',
  themeBorder: 'simple',
  contentAlign: 'left',
  fontWeight: 'normal',
  fontStyle: 'normal',
  visualStyle: 'card',
  showPedagogicalNote: false,
  showMascot: false,
  showStudentInfo: true,
  showTitle: true,
  showInstruction: true,
  showImage: true,
  showFooter: true,
  smartPagination: true,
  fontFamily: 'Lexend',
  lineHeight: 1.6,
  letterSpacing: 0,
  wordSpacing: 2,
  paragraphSpacing: 24,
  focusMode: false,
  rulerColor: '#6366f1',
  rulerHeight: 80,
  maskOpacity: 0.4,
  footerText: '',
  showAnswers: false,
  showClues: false,
};
