export const TURKEY_REGIONS: Record<string, string> = {
    '01': 'Akdeniz',
    '02': 'Güneydoğu',
    '03': 'Ege',
    '04': 'Doğu Anadolu',
    '05': 'Karadeniz',
    '06': 'İç Anadolu',
    '07': 'Akdeniz',
    '08': 'Karadeniz',
    '09': 'Ege',
    '10': 'Marmara',
    '11': 'Marmara',
    '12': 'Doğu Anadolu',
    '13': 'Doğu Anadolu',
    '14': 'Karadeniz',
    '15': 'Akdeniz',
    '16': 'Marmara',
    '17': 'Marmara',
    '18': 'İç Anadolu',
    '19': 'Karadeniz',
    '20': 'Ege',
    '21': 'Güneydoğu',
    '22': 'Marmara',
    '23': 'Doğu Anadolu',
    '24': 'Doğu Anadolu',
    '25': 'Doğu Anadolu',
    '26': 'İç Anadolu',
    '27': 'Güneydoğu',
    '28': 'Karadeniz',
    '29': 'Karadeniz',
    '30': 'Doğu Anadolu',
    '31': 'Akdeniz',
    '32': 'Akdeniz',
    '33': 'Akdeniz',
    '34': 'Marmara',
    '35': 'Ege',
    '36': 'Doğu Anadolu',
    '37': 'Karadeniz',
    '38': 'İç Anadolu',
    '39': 'Marmara',
    '40': 'İç Anadolu',
    '41': 'Marmara',
    '42': 'İç Anadolu',
    '43': 'Ege',
    '44': 'Doğu Anadolu',
    '45': 'Ege',
    '46': 'Akdeniz',
    '47': 'Güneydoğu',
    '48': 'Ege',
    '49': 'Doğu Anadolu',
    '50': 'İç Anadolu',
    '51': 'İç Anadolu',
    '52': 'Karadeniz',
    '53': 'Karadeniz',
    '54': 'Marmara',
    '55': 'Karadeniz',
    '56': 'Güneydoğu',
    '57': 'Karadeniz',
    '58': 'İç Anadolu',
    '59': 'Marmara',
    '60': 'Karadeniz',
    '61': 'Karadeniz',
    '62': 'Doğu Anadolu',
    '63': 'Güneydoğu',
    '64': 'Ege',
    '65': 'Doğu Anadolu',
    '66': 'İç Anadolu',
    '67': 'Karadeniz',
    '68': 'İç Anadolu',
    '69': 'Karadeniz',
    '70': 'İç Anadolu',
    '71': 'İç Anadolu',
    '72': 'Güneydoğu',
    '73': 'Güneydoğu',
    '74': 'Karadeniz',
    '75': 'Doğu Anadolu',
    '76': 'Doğu Anadolu',
    '77': 'Marmara',
    '78': 'Karadeniz',
    '79': 'Güneydoğu',
    '80': 'Akdeniz',
    '81': 'Karadeniz',
};
