export enum ActivityType {
  HECE_PARKURU = 'HECE_PARKURU',
  FIND_LETTER_PAIR = 'FIND_LETTER_PAIR',
  READING_SUDOKU = 'READING_SUDOKU',
  SYLLABLE_MASTER_LAB = 'SYLLABLE_MASTER_LAB',
  READING_STROOP = 'READING_STROOP',
  FAMILY_RELATIONS = 'FAMILY_RELATIONS',
  FAMILY_LOGIC_TEST = 'FAMILY_LOGIC_TEST',
  SYNONYM_ANTONYM_MATCH = 'SYNONYM_ANTONYM_MATCH',
  LETTER_VISUAL_MATCHING = 'LETTER_VISUAL_MATCHING',
  SYLLABLE_WORD_BUILDER = 'SYLLABLE_WORD_BUILDER',
  MAP_INSTRUCTION = 'MAP_INSTRUCTION',
  ALGORITHM_GENERATOR = 'ALGORITHM_GENERATOR',
  AI_WORKSHEET_CONVERTER = 'AI_WORKSHEET_CONVERTER',
  HIDDEN_PASSWORD_GRID = 'HIDDEN_PASSWORD_GRID',
  NUMBER_LOGIC_RIDDLES = 'NUMBER_LOGIC_RIDDLES',
  MATH_PUZZLE = 'MATH_PUZZLE',
  CLOCK_READING = 'CLOCK_READING',
  MONEY_COUNTING = 'MONEY_COUNTING',
  MATH_MEMORY_CARDS = 'MATH_MEMORY_CARDS',
  FIND_THE_DIFFERENCE = 'FIND_THE_DIFFERENCE',
  VISUAL_ODD_ONE_OUT = 'VISUAL_ODD_ONE_OUT',
  GRID_DRAWING = 'GRID_DRAWING',
  SYMMETRY_DRAWING = 'SYMMETRY_DRAWING',
  WORD_SEARCH = 'WORD_SEARCH',
  SHAPE_COUNTING = 'SHAPE_COUNTING',
  MORPHOLOGY_MATRIX = 'MORPHOLOGY_MATRIX',
  READING_PYRAMID = 'READING_PYRAMID',
  NUMBER_PATH_LOGIC = 'NUMBER_PATH_LOGIC',
  DIRECTIONAL_TRACKING = 'DIRECTIONAL_TRACKING',
  STORY_COMPREHENSION = 'STORY_COMPREHENSION',
  STORY_ANALYSIS = 'STORY_ANALYSIS',
  STORY_CREATION_PROMPT = 'STORY_CREATION_PROMPT',
  WORDS_IN_STORY = 'WORDS_IN_STORY',
  STORY_SEQUENCING = 'STORY_SEQUENCING',
  PROVERB_SAYING_SORT = 'PROVERB_SAYING_SORT',
  PROVERB_WORD_CHAIN = 'PROVERB_WORD_CHAIN',
  PROVERB_FILL_IN_THE_BLANK = 'PROVERB_FILL_IN_THE_BLANK',
  PROVERB_SEARCH = 'PROVERB_SEARCH',
  PROVERB_SENTENCE_FINDER = 'PROVERB_SENTENCE_FINDER',
  MISSING_PARTS = 'MISSING_PARTS',
  OCR_CONTENT = 'OCR_CONTENT',
  ASSESSMENT_REPORT = 'ASSESSMENT_REPORT',
  WORKBOOK = 'WORKBOOK',
  FUTOSHIKI = 'FUTOSHIKI',
  KENDOKU = 'KENDOKU',
  NUMBER_PYRAMID = 'NUMBER_PYRAMID',
  NUMBER_PATTERN = 'NUMBER_PATTERN',
  REAL_LIFE_MATH_PROBLEMS = 'REAL_LIFE_MATH_PROBLEMS',
  MATH_STUDIO = 'MATH_STUDIO',
  WORD_MEMORY = 'WORD_MEMORY',
  VISUAL_MEMORY = 'VISUAL_MEMORY',
  CHARACTER_MEMORY = 'CHARACTER_MEMORY',
  COLOR_WHEEL_MEMORY = 'COLOR_WHEEL_MEMORY',
  IMAGE_COMPREHRENSION = 'IMAGE_COMPREHRENSION',
  STROOP_TEST = 'STROOP_TEST',
  BURDON_TEST = 'BURDON_TEST',
  NUMBER_SEARCH = 'NUMBER_SEARCH',
  CHAOTIC_NUMBER_SEARCH = 'CHAOTIC_NUMBER_SEARCH',
  ATTENTION_DEVELOPMENT = 'ATTENTION_DEVELOPMENT',
  ATTENTION_FOCUS = 'ATTENTION_FOCUS',
  FIND_IDENTICAL_WORD = 'FIND_IDENTICAL_WORD',
  LETTER_GRID_TEST = 'LETTER_GRID_TEST',
  TARGET_SEARCH = 'TARGET_SEARCH',
  READING_FLOW = 'READING_FLOW',
  PHONOLOGICAL_AWARENESS = 'PHONOLOGICAL_AWARENESS',
  RAPID_NAMING = 'RAPID_NAMING',
  LETTER_DISCRIMINATION = 'LETTER_DISCRIMINATION',
  MIRROR_LETTERS = 'MIRROR_LETTERS',
  SYLLABLE_TRAIN = 'SYLLABLE_TRAIN',
  VISUAL_TRACKING_LINES = 'VISUAL_TRACKING_LINES',
  BACKWARD_SPELLING = 'BACKWARD_SPELLING',
  CODE_READING = 'CODE_READING',
  ATTENTION_TO_QUESTION = 'ATTENTION_TO_QUESTION',
  HANDWRITING_PRACTICE = 'HANDWRITING_PRACTICE',
  ANAGRAM = 'ANAGRAM',
  CROSSWORD = 'CROSSWORD',
  ODD_ONE_OUT = 'ODD_ONE_OUT',
  THEMATIC_ODD_ONE_OUT = 'THEMATIC_ODD_ONE_OUT',
  CONCEPT_MATCH = 'CONCEPT_MATCH',
  ESTIMATION = 'ESTIMATION',
  SPATIAL_GRID = 'SPATIAL_GRID',
  ODD_EVEN_SUDOKU = 'ODD_EVEN_SUDOKU',
  PUNCTUATION_MAZE = 'PUNCTUATION_MAZE',
  LOGIC_GRID_PUZZLE = 'LOGIC_GRID_PUZZLE',
  DOT_PAINTING = 'DOT_PAINTING',
  SHAPE_SUDOKU = 'SHAPE_SUDOKU',
  VISUAL_ARITHMETIC = 'VISUAL_ARITHMETIC',
  NUMBER_SENSE = 'NUMBER_SENSE',
  ABC_CONNECT = 'ABC_CONNECT',
  MAGIC_PYRAMID = 'MAGIC_PYRAMID',
  CAPSULE_GAME = 'CAPSULE_GAME',
  FIVE_W_ONE_H = 'FIVE_W_ONE_H',
  COLORFUL_SYLLABLE_READING = 'COLORFUL_SYLLABLE_READING',
  FAMILY_TREE_MATRIX = 'FAMILY_TREE_MATRIX',
  APARTMENT_LOGIC_PUZZLE = 'APARTMENT_LOGIC_PUZZLE',
  FINANCIAL_MARKET_CALCULATOR = 'FINANCIAL_MARKET_CALCULATOR',
  DIRECTIONAL_CODE_READING = 'DIRECTIONAL_CODE_READING',
  LOGIC_ERROR_HUNTER = 'LOGIC_ERROR_HUNTER',
  PATTERN_COMPLETION = 'PATTERN_COMPLETION',
  VISUAL_INTERPRETATION = 'VISUAL_INTERPRETATION',
  BRAIN_TEASERS = 'BRAIN_TEASERS',
  KAVRAM_HARITASI = 'KAVRAM_HARITASI',
  BOX_MATH = 'BOX_MATH',
  SINAV = 'SINAV',
  MAT_SINAV = 'MAT_SINAV',
  /** @deprecated Kaldırıldı — super-turkce modülü silindi (b6df8d74) */
  SUPER_TURKCE_MATCHING = 'SUPER_TURKCE_MATCHING',
  PREMIUM_STUDIO = 'PREMIUM_STUDIO',
  /** @deprecated Kaldırıldı — super-turkce modülü silindi (b6df8d74) */
  SUPER_TURKCE_V2 = 'SUPER_TURKCE_V2',

  // ── İNFOGRAFİK STÜDYOSUv3 — 96 Premium Aktivite Türü ───────────────────────
  // Kategori 1: Görsel & Mekansal (10 tip)
  INFOGRAPHIC_CONCEPT_MAP = 'INFOGRAPHIC_CONCEPT_MAP',
  INFOGRAPHIC_COMPARE = 'INFOGRAPHIC_COMPARE',
  INFOGRAPHIC_VISUAL_LOGIC = 'INFOGRAPHIC_VISUAL_LOGIC',
  INFOGRAPHIC_VENN_DIAGRAM = 'INFOGRAPHIC_VENN_DIAGRAM',
  INFOGRAPHIC_MIND_MAP = 'INFOGRAPHIC_MIND_MAP',
  INFOGRAPHIC_FLOWCHART = 'INFOGRAPHIC_FLOWCHART',
  INFOGRAPHIC_MATRIX_ANALYSIS = 'INFOGRAPHIC_MATRIX_ANALYSIS',
  INFOGRAPHIC_CAUSE_EFFECT = 'INFOGRAPHIC_CAUSE_EFFECT',
  INFOGRAPHIC_FISHBONE = 'INFOGRAPHIC_FISHBONE',
  INFOGRAPHIC_CLUSTER_MAP = 'INFOGRAPHIC_CLUSTER_MAP',

  // Kategori 2: Okuduğunu Anlama (10 tip)
  INFOGRAPHIC_5W1H_BOARD = 'INFOGRAPHIC_5W1H_BOARD',
  INFOGRAPHIC_READING_FLOW = 'INFOGRAPHIC_READING_FLOW',
  INFOGRAPHIC_SEQUENCE = 'INFOGRAPHIC_SEQUENCE',
  INFOGRAPHIC_STORY_MAP = 'INFOGRAPHIC_STORY_MAP',
  INFOGRAPHIC_CHARACTER_ANALYSIS = 'INFOGRAPHIC_CHARACTER_ANALYSIS',
  INFOGRAPHIC_INFERENCE_CHAIN = 'INFOGRAPHIC_INFERENCE_CHAIN',
  INFOGRAPHIC_SUMMARY_PYRAMID = 'INFOGRAPHIC_SUMMARY_PYRAMID',
  INFOGRAPHIC_PREDICTION_BOARD = 'INFOGRAPHIC_PREDICTION_BOARD',
  INFOGRAPHIC_COMPARE_TEXTS = 'INFOGRAPHIC_COMPARE_TEXTS',
  INFOGRAPHIC_THEME_WEB = 'INFOGRAPHIC_THEME_WEB',

  // Kategori 3: Okuma & Dil (10 tip)
  INFOGRAPHIC_SYLLABLE_MAP = 'INFOGRAPHIC_SYLLABLE_MAP',
  INFOGRAPHIC_VOCAB_TREE = 'INFOGRAPHIC_VOCAB_TREE',
  INFOGRAPHIC_TIMELINE_EVENT = 'INFOGRAPHIC_TIMELINE_EVENT',
  INFOGRAPHIC_WORD_FAMILY = 'INFOGRAPHIC_WORD_FAMILY',
  INFOGRAPHIC_PREFIX_SUFFIX = 'INFOGRAPHIC_PREFIX_SUFFIX',
  INFOGRAPHIC_SENTENCE_BUILDER = 'INFOGRAPHIC_SENTENCE_BUILDER',
  INFOGRAPHIC_ANTONYM_SYNONYM = 'INFOGRAPHIC_ANTONYM_SYNONYM',
  INFOGRAPHIC_WORD_ORIGIN = 'INFOGRAPHIC_WORD_ORIGIN',
  INFOGRAPHIC_COMPOUND_WORD = 'INFOGRAPHIC_COMPOUND_WORD',
  INFOGRAPHIC_GENRE_CHART = 'INFOGRAPHIC_GENRE_CHART',

  // Kategori 4: Matematik & Mantık (10 tip)
  INFOGRAPHIC_MATH_STEPS = 'INFOGRAPHIC_MATH_STEPS',
  INFOGRAPHIC_NUMBER_LINE = 'INFOGRAPHIC_NUMBER_LINE',
  INFOGRAPHIC_FRACTION_VISUAL = 'INFOGRAPHIC_FRACTION_VISUAL',
  INFOGRAPHIC_MULTIPLICATION_MAP = 'INFOGRAPHIC_MULTIPLICATION_MAP',
  INFOGRAPHIC_GEOMETRY_EXPLORER = 'INFOGRAPHIC_GEOMETRY_EXPLORER',
  INFOGRAPHIC_DATA_CHART = 'INFOGRAPHIC_DATA_CHART',
  INFOGRAPHIC_ALGEBRA_BALANCE = 'INFOGRAPHIC_ALGEBRA_BALANCE',
  INFOGRAPHIC_MEASUREMENT_GUIDE = 'INFOGRAPHIC_MEASUREMENT_GUIDE',
  INFOGRAPHIC_PATTERN_RULE = 'INFOGRAPHIC_PATTERN_RULE',
  INFOGRAPHIC_WORD_PROBLEM_MAP = 'INFOGRAPHIC_WORD_PROBLEM_MAP',

  // Kategori 5: Fen Bilimleri (8 tip)
  INFOGRAPHIC_LIFE_CYCLE = 'INFOGRAPHIC_LIFE_CYCLE',
  INFOGRAPHIC_FOOD_CHAIN = 'INFOGRAPHIC_FOOD_CHAIN',
  INFOGRAPHIC_SCIENTIFIC_METHOD = 'INFOGRAPHIC_SCIENTIFIC_METHOD',
  INFOGRAPHIC_CELL_DIAGRAM = 'INFOGRAPHIC_CELL_DIAGRAM',
  INFOGRAPHIC_ECOSYSTEM_WEB = 'INFOGRAPHIC_ECOSYSTEM_WEB',
  INFOGRAPHIC_STATES_MATTER = 'INFOGRAPHIC_STATES_MATTER',
  INFOGRAPHIC_SOLAR_SYSTEM = 'INFOGRAPHIC_SOLAR_SYSTEM',
  INFOGRAPHIC_HUMAN_BODY = 'INFOGRAPHIC_HUMAN_BODY',

  // Kategori 6: Sosyal Bilgiler & Tarih (8 tip)
  INFOGRAPHIC_HISTORICAL_TIMELINE = 'INFOGRAPHIC_HISTORICAL_TIMELINE',
  INFOGRAPHIC_MAP_EXPLORER = 'INFOGRAPHIC_MAP_EXPLORER',
  INFOGRAPHIC_CULTURE_COMPARE = 'INFOGRAPHIC_CULTURE_COMPARE',
  INFOGRAPHIC_GOVERNMENT_CHART = 'INFOGRAPHIC_GOVERNMENT_CHART',
  INFOGRAPHIC_ECONOMIC_FLOW = 'INFOGRAPHIC_ECONOMIC_FLOW',
  INFOGRAPHIC_BIOGRAPHY_BOARD = 'INFOGRAPHIC_BIOGRAPHY_BOARD',
  INFOGRAPHIC_EVENT_ANALYSIS = 'INFOGRAPHIC_EVENT_ANALYSIS',
  INFOGRAPHIC_GEOGRAPHY_PROFILE = 'INFOGRAPHIC_GEOGRAPHY_PROFILE',

  // Kategori 7: Yaratıcı Düşünme (8 tip)
  INFOGRAPHIC_BRAINSTORM_WEB = 'INFOGRAPHIC_BRAINSTORM_WEB',
  INFOGRAPHIC_SCAMPER = 'INFOGRAPHIC_SCAMPER',
  INFOGRAPHIC_DESIGN_THINKING = 'INFOGRAPHIC_DESIGN_THINKING',
  INFOGRAPHIC_ALTERNATIVE_ENDS = 'INFOGRAPHIC_ALTERNATIVE_ENDS',
  INFOGRAPHIC_INVENTION_PLAN = 'INFOGRAPHIC_INVENTION_PLAN',
  INFOGRAPHIC_ASSOCIATIONS = 'INFOGRAPHIC_ASSOCIATIONS',
  INFOGRAPHIC_ROLE_PLAY_SCENARIO = 'INFOGRAPHIC_ROLE_PLAY_SCENARIO',
  INFOGRAPHIC_FUTURE_VISION = 'INFOGRAPHIC_FUTURE_VISION',

  // Kategori 8: Öğrenme Stratejileri (8 tip)
  INFOGRAPHIC_GOAL_SETTING = 'INFOGRAPHIC_GOAL_SETTING',
  INFOGRAPHIC_TIME_MANAGEMENT = 'INFOGRAPHIC_TIME_MANAGEMENT',
  INFOGRAPHIC_STUDY_PLAN = 'INFOGRAPHIC_STUDY_PLAN',
  INFOGRAPHIC_EMOTION_GAUGE = 'INFOGRAPHIC_EMOTION_GAUGE',
  INFOGRAPHIC_SELF_REFLECTION = 'INFOGRAPHIC_SELF_REFLECTION',
  INFOGRAPHIC_MOTIVATION_BOARD = 'INFOGRAPHIC_MOTIVATION_BOARD',
  INFOGRAPHIC_NOTE_TAKING = 'INFOGRAPHIC_NOTE_TAKING',
  INFOGRAPHIC_TEST_PREPARATION = 'INFOGRAPHIC_TEST_PREPARATION',

  // Kategori 9: SpLD / Özel Destek (10 tip)
  INFOGRAPHIC_DYSLEXIA_READING = 'INFOGRAPHIC_DYSLEXIA_READING',
  INFOGRAPHIC_DYSGRAPHIA_WRITING = 'INFOGRAPHIC_DYSGRAPHIA_WRITING',
  INFOGRAPHIC_DYSCALCULIA_MATH = 'INFOGRAPHIC_DYSCALCULIA_MATH',
  INFOGRAPHIC_ADHD_FOCUS = 'INFOGRAPHIC_ADHD_FOCUS',
  INFOGRAPHIC_EXECUTIVE_FUNCTION = 'INFOGRAPHIC_EXECUTIVE_FUNCTION',
  INFOGRAPHIC_SENSORY_INTEGRATION = 'INFOGRAPHIC_SENSORY_INTEGRATION',
  INFOGRAPHIC_ANXIETY_RELIEF = 'INFOGRAPHIC_ANXIETY_RELIEF',
  INFOGRAPHIC_SOCIAL_SKILLS = 'INFOGRAPHIC_SOCIAL_SKILLS',
  INFOGRAPHIC_ROUTINE_BUILDER = 'INFOGRAPHIC_ROUTINE_BUILDER',
  INFOGRAPHIC_BEHAVIOR_TRACKER = 'INFOGRAPHIC_BEHAVIOR_TRACKER',

  // Kategori 10: Klinik & BEP (12 tip) — Dr. Ahmet Kaya klinik onayı zorunlu
  INFOGRAPHIC_BEP_GOAL_MAP = 'INFOGRAPHIC_BEP_GOAL_MAP',
  INFOGRAPHIC_IEP_PROGRESS = 'INFOGRAPHIC_IEP_PROGRESS',
  INFOGRAPHIC_OBSERVATION_MATRIX = 'INFOGRAPHIC_OBSERVATION_MATRIX',
  INFOGRAPHIC_COGNITIVE_PROFILE = 'INFOGRAPHIC_COGNITIVE_PROFILE',
  INFOGRAPHIC_BEHAVIOR_INTERVENTION = 'INFOGRAPHIC_BEHAVIOR_INTERVENTION',
  INFOGRAPHIC_SENSORY_DIET = 'INFOGRAPHIC_SENSORY_DIET',
  INFOGRAPHIC_PARENT_GUIDE = 'INFOGRAPHIC_PARENT_GUIDE',
  INFOGRAPHIC_ACCOMMODATION_LIST = 'INFOGRAPHIC_ACCOMMODATION_LIST',
  INFOGRAPHIC_TRANSITION_PLAN = 'INFOGRAPHIC_TRANSITION_PLAN',
  INFOGRAPHIC_SPEECH_THERAPY_TARGET = 'INFOGRAPHIC_SPEECH_THERAPY_TARGET',
  INFOGRAPHIC_MOTOR_SKILLS = 'INFOGRAPHIC_MOTOR_SKILLS',
  INFOGRAPHIC_EVALUATION_SUMMARY = 'INFOGRAPHIC_EVALUATION_SUMMARY',

  // ── WORKBOOK AI GEÇİCİ TİPLERİ (TS Hatalarını Önlemek İçin) ──────────────
  MATH_BASIC_OPERATIONS = 'MATH_BASIC_OPERATIONS',
  MATH_WORD_PROBLEMS = 'MATH_WORD_PROBLEMS',
  MATH_GEOMETRY = 'MATH_GEOMETRY',
  READING_COMPREHENSION = 'READING_COMPREHENSION',
  GRAMMAR_EXERCISE = 'GRAMMAR_EXERCISE',
  VOCABULARY_BUILDING = 'VOCABULARY_BUILDING',
  LOGIC_PUZZLE = 'LOGIC_PUZZLE',
  PATTERN_RECOGNITION = 'PATTERN_RECOGNITION',
  VISUAL_PERCEPTION = 'VISUAL_PERCEPTION',
  DYSLEXIA_SYLLABLE_BREAK = 'DYSLEXIA_SYLLABLE_BREAK',
  DYSLEXIA_WORD_RECOGNITION = 'DYSLEXIA_WORD_RECOGNITION',
  ANAGRAM_PUZZLE = 'ANAGRAM_PUZZLE',
  DYSCALCULIA_NUMBER_SENSE = 'DYSCALCULIA_NUMBER_SENSE',
  DYSCALCULIA_MAGNITUDE_COMPARISON = 'DYSCALCULIA_MAGNITUDE_COMPARISON',
  MEMORY_GAME = 'MEMORY_GAME',
  QUICK_RECALL = 'QUICK_RECALL',
  MATH_ALGEBRA = 'MATH_ALGEBRA',
  TEXT_ANALYSIS = 'TEXT_ANALYSIS',
  SCIENCE_EXPERIMENT = 'SCIENCE_EXPERIMENT',
  LOGIC_REASONING = 'LOGIC_REASONING',
  SPELLING_PRACTICE = 'SPELLING_PRACTICE',
  WRITING_PROMPT = 'WRITING_PROMPT',
  DIAGNOSTIC_TEST = 'DIAGNOSTIC_TEST',
  SKILL_ASSESSMENT = 'SKILL_ASSESSMENT',
  PROGRESS_MONITORING = 'PROGRESS_MONITORING',
  SELF_ASSESSMENT = 'SELF_ASSESSMENT',
  CREATIVE_WRITING = 'CREATIVE_WRITING',
  STORY_STARTER = 'STORY_STARTER',
  DRAWING_EXERCISE = 'DRAWING_EXERCISE',
  COLLAGE_ACTIVITY = 'COLLAGE_ACTIVITY',
  REFLECTION_PROMPT = 'REFLECTION_PROMPT',
  OBSERVATION_TASK = 'OBSERVATION_TASK',
  HISTORY_TIMELINE = 'HISTORY_TIMELINE',
  MAP_READING = 'MAP_READING',
  GOAL_SETTING = 'GOAL_SETTING',
}

export interface Activity {
  id: ActivityType;
  title: string;
  description: string;
  icon: string;
  defaultStyle?: Record<string, unknown>;
  promptId?: string;
}

export interface ActivityCategory {
  id: string;
  title: string;
  description: string;
  icon: string;
  activities: ActivityType[];
}

export interface WorksheetBlock {
  type:
    | 'header'
    | 'text'
    | 'grid'
    | 'table'
    | 'svg_shape'
    | 'dual_column'
    | 'image'
    | 'question'
    | 'logic_card'
    | 'footer_validation'
    | 'cloze_test'
    | 'categorical_sorting'
    | 'match_columns'
    | 'visual_clue_card'
    | 'neuro_marker';
  content: unknown;
  id?: string;
  style?: {
    textAlign?: string;
    fontWeight?: string;
    fontSize?: number;
    backgroundColor?: string;
    borderRadius?: number;
    color?: string;
  };
  weight?: number;
}

export type CognitiveErrorTag =
  | 'visual_discrimination'
  | 'attention_lapse'
  | 'impulsivity_error'
  | 'phonological_substitution'
  | 'sequencing_error'
  | 'visual_reversal'
  | 'visual_inversion'
  | 'working_memory_overflow'
  | 'logical_reasoning'
  | 'visual_spatial_memory'
  | 'selective_attention'
  | 'processing_speed'
  | 'phonological_loop';
