import { ActivityType } from '../types/activity';
import { ACTIVITIES } from '../constants/activities';

/**
 * BDMIND — Tüm Aktivite Tipleri için Türkçe İsim Haritası
 */
const TURKISH_ACTIVITY_NAMES: Record<string, string> = {
  [ActivityType.HECE_PARKURU]: 'Hece Parkuru',
  [ActivityType.FIND_LETTER_PAIR]: 'Harf İkilisi Dedektifi',
  [ActivityType.READING_SUDOKU]: 'Dil ve Mantık Sudokusu',
  [ActivityType.SYLLABLE_MASTER_LAB]: 'Hece Ustası Laboratuvarı',
  [ActivityType.READING_STROOP]: 'Sözel Stroop Testi',
  [ActivityType.FAMILY_RELATIONS]: 'Akrabalık İlişkileri',
  [ActivityType.FAMILY_LOGIC_TEST]: 'Akrabalık Mantık Testi',
  [ActivityType.SYNONYM_ANTONYM_MATCH]: 'Eş ve Zıt Anlamlılar',
  [ActivityType.LETTER_VISUAL_MATCHING]: 'Harf-Görsel Eşleme',
  [ActivityType.SYLLABLE_WORD_BUILDER]: 'Hece Dedektifi',
  [ActivityType.MAP_INSTRUCTION]: 'Harita Dedektifi',
  [ActivityType.ALGORITHM_GENERATOR]: 'Algoritma Üretici',
  [ActivityType.AI_WORKSHEET_CONVERTER]: 'Akıllı Dönüştürücü',
  [ActivityType.HIDDEN_PASSWORD_GRID]: 'Gizli Şifre Matrisi',
  [ActivityType.NUMBER_LOGIC_RIDDLES]: 'Sayısal Mantık Bilmeceleri',
  [ActivityType.MATH_PUZZLE]: 'Matematik Bulmacaları',
  [ActivityType.CLOCK_READING]: 'Saat Okuma',
  [ActivityType.MONEY_COUNTING]: 'Paralarımız',
  [ActivityType.MATH_MEMORY_CARDS]: 'Matematik Hafıza Kartları',
  [ActivityType.FIND_THE_DIFFERENCE]: 'Farkı Bul',
  [ActivityType.VISUAL_ODD_ONE_OUT]: 'Görsel Farklıyı Bul',
  [ActivityType.GRID_DRAWING]: 'Kare Kopyalama',
  [ActivityType.SYMMETRY_DRAWING]: 'Simetri Tamamlama',
  [ActivityType.WORD_SEARCH]: 'Kelime Bulmaca',
  [ActivityType.SHAPE_COUNTING]: 'Kaç Tane Üçgen Var?',
  [ActivityType.MORPHOLOGY_MATRIX]: 'Morfolojik Kelime İnşaatı',
  [ActivityType.READING_PYRAMID]: 'Akıcı Okuma Piramidi',
  [ActivityType.NUMBER_PATH_LOGIC]: 'Sembolik İşlem Zinciri',
  [ActivityType.DIRECTIONAL_TRACKING]: 'Yönsel İz Sürme (Kod Çözme)',
  [ActivityType.STORY_COMPREHENSION]: 'Hikaye Kavrama',
  [ActivityType.STORY_ANALYSIS]: 'Hikaye Analizi (Ultra Pro)',
  [ActivityType.STORY_CREATION_PROMPT]: 'Hikaye Yazma Konusu',
  [ActivityType.WORDS_IN_STORY]: 'Hikayedeki Kelimeler',
  [ActivityType.STORY_SEQUENCING]: 'Olay Sıralama (Hikaye)',
  [ActivityType.PROVERB_SAYING_SORT]: 'Atasözü Sıralama',
  [ActivityType.PROVERB_WORD_CHAIN]: 'Atasözü Kelime Zinciri',
  [ActivityType.PROVERB_FILL_IN_THE_BLANK]: 'Atasözü Boşluk Doldurma',
  [ActivityType.PROVERB_SEARCH]: 'Atasözü Bulmaca',
  [ActivityType.PROVERB_SENTENCE_FINDER]: 'Atasözü Cümle Bulma',
  [ActivityType.MISSING_PARTS]: 'Eksik Parçaları Tamamlama',
  [ActivityType.OCR_CONTENT]: 'Görsel Okuma ve İçerik',
  [ActivityType.ASSESSMENT_REPORT]: 'Değerlendirme Raporu',
  [ActivityType.FUTOSHIKI]: 'Futoşhiki',
  [ActivityType.KENDOKU]: 'Kendoku (İşlem Blokları)',
  [ActivityType.NUMBER_PYRAMID]: 'Sayı Piramidi',
  [ActivityType.NUMBER_PATTERN]: 'Sayı Örüntüleri',
  [ActivityType.REAL_LIFE_MATH_PROBLEMS]: 'Gerçek Hayat Matematiği',
  [ActivityType.MATH_STUDIO]: 'Matematik Stüdyosu',
  [ActivityType.WORD_MEMORY]: 'Kelime Hafızası Testi',
  [ActivityType.VISUAL_MEMORY]: 'Görsel Hafıza Testi',
  [ActivityType.CHARACTER_MEMORY]: 'Karakter Hafızası',
  [ActivityType.COLOR_WHEEL_MEMORY]: 'Renk Çarkı Hafızası',
  [ActivityType.IMAGE_COMPREHRENSION]: 'Görsel Anlama Testi',
  [ActivityType.STROOP_TEST]: 'Stroop Dikkat Testi',
  [ActivityType.BURDON_TEST]: 'Burdon Dikkat Testi',
  [ActivityType.NUMBER_SEARCH]: 'Sayı Arama Testi',
  [ActivityType.CHAOTIC_NUMBER_SEARCH]: 'Karışık Sayı Arama',
  [ActivityType.ATTENTION_DEVELOPMENT]: 'Dikkat Geliştirme Egzersizi',
  [ActivityType.ATTENTION_FOCUS]: 'Odaklanma Egzersizi',
  [ActivityType.FIND_IDENTICAL_WORD]: 'Aynı Kelimeyi Bul',
  [ActivityType.LETTER_GRID_TEST]: 'Harf Izgara Testi',
  [ActivityType.SEMANTIC_LINKER]: 'Anlamsal İlişki Kurma',
  [ActivityType.TARGET_SEARCH]: 'Hedef Arama Testi',
  [ActivityType.READING_FLOW]: 'Okuma Akışı Egzersizi',
  [ActivityType.PHONOLOGICAL_AWARENESS]: 'Fonolojik Farkındalık',
  [ActivityType.RAPID_NAMING]: 'Hızlı İsimlendirme Testi',
  [ActivityType.LETTER_DISCRIMINATION]: 'Harf Ayırt Etme',
  [ActivityType.MIRROR_LETTERS]: 'Ayna Harfler Alıştırması',
  [ActivityType.SYLLABLE_TRAIN]: 'Hece Treni',
  [ActivityType.VISUAL_TRACKING_LINES]: 'Görsel Çizgi İzleme',
  [ActivityType.BACKWARD_SPELLING]: 'Tersten Kodlama',
  [ActivityType.CODE_READING]: 'Şifreli Kod Okuma',
  [ActivityType.ATTENTION_TO_QUESTION]: 'Soruya Odaklanma',
  [ActivityType.HANDWRITING_PRACTICE]: 'El Yazısı Alıştırması',
  [ActivityType.ANAGRAM]: 'Anagram Kelime Bulmaca',
  [ActivityType.CROSSWORD]: 'Kare Bulmaca',
  [ActivityType.ODD_ONE_OUT]: 'Farklı Olanı Bul',
  [ActivityType.THEMATIC_ODD_ONE_OUT]: 'Tematik Farklı Öğe',
  [ActivityType.CONCEPT_MATCH]: 'Kavram Eşleştirme',
  [ActivityType.ESTIMATION]: 'Tahmin Etme Çalışması',
  [ActivityType.SPATIAL_GRID]: 'Uzamsal Izgara Alıştırması',
  [ActivityType.ODD_EVEN_SUDOKU]: 'Tek ve Çift Sudoku',
  [ActivityType.PUNCTUATION_MAZE]: 'Noktalama İşaretleri Labirenti',
  [ActivityType.LOGIC_GRID_PUZZLE]: 'Mantık Izgarası Bulmacası',
  [ActivityType.DOT_PAINTING]: 'Nokta Birleştirme & Boyama',
  [ActivityType.SHAPE_SUDOKU]: 'Şekil Sudokusu',
  [ActivityType.VISUAL_ARITHMETIC]: 'Görsel Aritmetik',
  [ActivityType.NUMBER_SENSE]: 'Sayı Hissi ve Algısı',
  [ActivityType.ABC_CONNECT]: 'ABC Bağlama (Romenler)',
  [ActivityType.MAGIC_PYRAMID]: 'Sihirli Piramit',
  [ActivityType.CAPSULE_GAME]: 'Kapsül Oyunu',
  [ActivityType.FIVE_W_ONE_H]: '5N1K Okuma Anlama Simülatörü',
  [ActivityType.SENTENCE_5W1H]: 'Cümlede 5N1K',
  [ActivityType.COLORFUL_SYLLABLE_READING]: 'Renkli Hece / Odaklı Okuma',
  [ActivityType.FAMILY_TREE_MATRIX]: 'Akrabalık ve Soy Ağacı Matrisi',
  [ActivityType.APARTMENT_LOGIC_PUZZLE]: 'Nerede Oturuyor? (Einstein Apartmanı)',
  [ActivityType.FINANCIAL_MARKET_CALCULATOR]: 'Pazar Yeri & Finans',
  [ActivityType.DIRECTIONAL_CODE_READING]: 'Şifreli Kod & Rota',
  [ActivityType.LOGIC_ERROR_HUNTER]: 'Mantık Hataları Avcısı',
  [ActivityType.WORKBOOK]: 'Çalışma Kitapçığı',
  [ActivityType.SHORT_ANSWER]: 'Kısa Cevaplı Sorular',
  [ActivityType.PATTERN_COMPLETION]: 'Kafayı Çalıştır (Desen Tamamla)',
  [ActivityType.VISUAL_INTERPRETATION]: 'Resim Yorumlama ve Analiz',
  [ActivityType.BRAIN_TEASERS]: 'Kafayı Çalıştır (Zeka Oyunları)',
  [ActivityType.KAVRAM_HARITASI]: 'Kavram Haritası',
  [ActivityType.ES_ANLAMLI_KELIMELER]: 'Eş Anlamlı Kelimeler',
  [ActivityType.BOX_MATH]: 'Kutularla Matematik',
  [ActivityType.SINAV]: 'Sınav Stüdyosu',
  [ActivityType.MAT_SINAV]: 'Matematik Sınavı',
  [ActivityType.MAT_PROBLEM]: 'Matematik Problemleri',
  [ActivityType.QUEUE_ORDERING]: 'Sıralama (Sıra Alma Becerisi)',
  [ActivityType.SUPER_TURKCE_MATCHING]: 'Süper Türkçe Eşleştirme',
  [ActivityType.PREMIUM_STUDIO]: 'Süper Türkçe Stüdyosu',
  [ActivityType.SUPER_STUDIO]: 'Ultra Etkinlik Stüdyosu',
  [ActivityType.ACTIVITY_STUDIO]: 'Etkinlik Havuzu Stüdyosu',
  [ActivityType.SUPER_TURKCE_V2]: 'Süper Türkçe v2',
  [ActivityType.KELIME_CUMLE]: 'Kelime & Cümle Stüdyosu',
  [ActivityType.CURRICULUM]: 'Plan & Müfredat Stüdyosu',
  [ActivityType.FASCICLE]: 'Fasikül Stüdyosu',
  // İnfografik Stüdyosu Türleri
  [ActivityType.INFOGRAPHIC_CONCEPT_MAP]: 'Kavram Haritası (İnfografik)',
  [ActivityType.INFOGRAPHIC_COMPARE]: 'Karşılaştırma Tablosu',
  [ActivityType.INFOGRAPHIC_VISUAL_LOGIC]: 'Görsel Mantık Şeması',
  [ActivityType.INFOGRAPHIC_VENN_DIAGRAM]: 'Venn Şeması',
  [ActivityType.INFOGRAPHIC_MIND_MAP]: 'Zihin Haritası',
  [ActivityType.INFOGRAPHIC_FLOWCHART]: 'Akış Şeması',
  [ActivityType.INFOGRAPHIC_MATRIX_ANALYSIS]: 'Matris Analizi',
  [ActivityType.INFOGRAPHIC_CAUSE_EFFECT]: 'Neden-Sonuç Şeması',
  [ActivityType.INFOGRAPHIC_FISHBONE]: 'Balık Kılçığı Diyagramı',
  [ActivityType.INFOGRAPHIC_CLUSTER_MAP]: 'Kümeler Haritası',
  [ActivityType.INFOGRAPHIC_5W1H_BOARD]: '5N1K Panosu',
  [ActivityType.INFOGRAPHIC_READING_FLOW]: 'Okuma Akışı Panosu',
  [ActivityType.INFOGRAPHIC_SEQUENCE]: 'Olay Sıralama Şeması',
  [ActivityType.INFOGRAPHIC_STORY_MAP]: 'Hikaye Haritası',
  [ActivityType.INFOGRAPHIC_CHARACTER_ANALYSIS]: 'Karakter Analizi Şeması',
  [ActivityType.INFOGRAPHIC_INFERENCE_CHAIN]: 'Çıkarım Zinciri',
  [ActivityType.INFOGRAPHIC_SUMMARY_PYRAMID]: 'Özet Piramidi',
  [ActivityType.INFOGRAPHIC_PREDICTION_BOARD]: 'Tahmin Panosu',
  [ActivityType.INFOGRAPHIC_COMPARE_TEXTS]: 'Metin Karşılaştırma',
  [ActivityType.INFOGRAPHIC_THEME_WEB]: 'Tema Ağı',
  [ActivityType.INFOGRAPHIC_SHORT_ANSWER]: 'Kısa Cevaplı Sorular (Premium)',
  [ActivityType.INFOGRAPHIC_SYLLABLE_MAP]: 'Hece Haritası',
  [ActivityType.INFOGRAPHIC_VOCAB_TREE]: 'Kelime Ağacı',
  [ActivityType.INFOGRAPHIC_TIMELINE_EVENT]: 'Zaman Çizelgesi',
  [ActivityType.INFOGRAPHIC_WORD_FAMILY]: 'Kelime Ailesi',
  [ActivityType.INFOGRAPHIC_PREFIX_SUFFIX]: 'Kök ve Ek Şeması',
  [ActivityType.INFOGRAPHIC_SENTENCE_BUILDER]: 'Cümle Kurucu',
  [ActivityType.INFOGRAPHIC_ANTONYM_SYNONYM]: 'Zıt ve Eş Anlam Haritası',
  [ActivityType.INFOGRAPHIC_WORD_ORIGIN]: 'Kelime Kökeni Şeması',
  [ActivityType.INFOGRAPHIC_COMPOUND_WORD]: 'Birleşik Kelimeler Şeması',
  [ActivityType.INFOGRAPHIC_GENRE_CHART]: 'Metin Türleri Tablosu',
  [ActivityType.INFOGRAPHIC_MATH_STEPS]: 'Matematik Adım Şeması',
  [ActivityType.INFOGRAPHIC_NUMBER_LINE]: 'Sayı Doğrusu Şeması',
  [ActivityType.INFOGRAPHIC_FRACTION_VISUAL]: 'Kesir Görselleştirici',
  [ActivityType.INFOGRAPHIC_MULTIPLICATION_MAP]: 'Çarpım Tablosu Haritası',
  [ActivityType.INFOGRAPHIC_GEOMETRY_EXPLORER]: 'Geometri Keşif Panosu',
  [ActivityType.INFOGRAPHIC_DATA_CHART]: 'Veri ve Grafik Şeması',
  [ActivityType.INFOGRAPHIC_ALGEBRA_BALANCE]: 'Cebirsel Terazi Şeması',
  [ActivityType.INFOGRAPHIC_MEASUREMENT_GUIDE]: 'Ölçü Birimleri Rehberi',
  [ActivityType.INFOGRAPHIC_PATTERN_RULE]: 'Örüntü Kuralları Şeması',
  [ActivityType.INFOGRAPHIC_WORD_PROBLEM_MAP]: 'Problem Çözme Haritası',
  [ActivityType.INFOGRAPHIC_LIFE_CYCLE]: 'Yaşam Döngüsü Şeması',
  [ActivityType.INFOGRAPHIC_FOOD_CHAIN]: 'Besin Zinciri Diyagramı',
  [ActivityType.INFOGRAPHIC_SCIENTIFIC_METHOD]: 'Bilimsel Yöntem Basamakları',
  [ActivityType.INFOGRAPHIC_CELL_DIAGRAM]: 'Hücre Diyagramı',
  [ActivityType.INFOGRAPHIC_ECOSYSTEM_WEB]: 'Ekosistem Ağı',
  [ActivityType.INFOGRAPHIC_STATES_MATTER]: 'Maddenin Halleri Şeması',
  [ActivityType.INFOGRAPHIC_SOLAR_SYSTEM]: 'Güneş Sistemi Şeması',
  [ActivityType.INFOGRAPHIC_HUMAN_BODY]: 'Vücudumuz Diyagramı',
  [ActivityType.INFOGRAPHIC_HISTORICAL_TIMELINE]: 'Tarihsel Kronoloji Çizelgesi',
  [ActivityType.INFOGRAPHIC_MAP_EXPLORER]: 'Harita Keşif Panosu',
  [ActivityType.INFOGRAPHIC_CULTURE_COMPARE]: 'Kültür Karşılaştırma Şeması',
  [ActivityType.INFOGRAPHIC_GOVERNMENT_CHART]: 'Yönetim Şeması',
  [ActivityType.INFOGRAPHIC_ECONOMIC_FLOW]: 'Ekonomik Akış Şeması',
  [ActivityType.INFOGRAPHIC_BIOGRAPHY_BOARD]: 'Biyografi Panosu',
  [ActivityType.INFOGRAPHIC_EVENT_ANALYSIS]: 'Olay Analizi Şeması',
  [ActivityType.INFOGRAPHIC_GEOGRAPHY_PROFILE]: 'Coğrafya Profil Panosu',
  [ActivityType.INFOGRAPHIC_BRAINSTORM_WEB]: 'Beyin Fırtınası Ağı',
  [ActivityType.INFOGRAPHIC_SCAMPER]: 'SCAMPER Yaratıcılık Şeması',
  [ActivityType.INFOGRAPHIC_DESIGN_THINKING]: 'Tasarım Odaklı Düşünme',
  [ActivityType.INFOGRAPHIC_ALTERNATIVE_ENDS]: 'Alternatif Sonlar Şeması',
  [ActivityType.INFOGRAPHIC_INVENTION_PLAN]: 'Buluş ve İcat Planı',
  [ActivityType.INFOGRAPHIC_ASSOCIATIONS]: 'Çağrışım Haritası',
  [ActivityType.INFOGRAPHIC_ROLE_PLAY_SCENARIO]: 'Rol Oynama Senaryosu',
  [ActivityType.INFOGRAPHIC_FUTURE_VISION]: 'Gelecek Vizyonu Panosu',
  [ActivityType.INFOGRAPHIC_GOAL_SETTING]: 'Hedef Belirleme Şeması',
  [ActivityType.INFOGRAPHIC_TIME_MANAGEMENT]: 'Zaman Yönetimi Çizelgesi',
  [ActivityType.INFOGRAPHIC_STUDY_PLAN]: 'Ders Çalışma Planı',
  [ActivityType.INFOGRAPHIC_EMOTION_GAUGE]: 'Duygu Göstergesi Panosu',
  [ActivityType.INFOGRAPHIC_SELF_REFLECTION]: 'Öz Değerlendirme Formu',
  [ActivityType.INFOGRAPHIC_MOTIVATION_BOARD]: 'Motivasyon Panosu',
  [ActivityType.INFOGRAPHIC_NOTE_TAKING]: 'Not Alma Şeması',
  [ActivityType.INFOGRAPHIC_TEST_PREPARATION]: 'Sınava Hazırlık Rehberi',
  [ActivityType.INFOGRAPHIC_DYSLEXIA_READING]: 'Disleksi Okuma Desteği',
  [ActivityType.INFOGRAPHIC_DYSGRAPHIA_WRITING]: 'Disgrafi Yazı Desteği',
  [ActivityType.INFOGRAPHIC_DYSCALCULIA_MATH]: 'Diskalkuli Matematik Desteği',
  [ActivityType.INFOGRAPHIC_ADHD_FOCUS]: 'DEHB Odaklanma Desteği',
  [ActivityType.INFOGRAPHIC_EXECUTIVE_FUNCTION]: 'Yürütücü İşlevler Şeması',
  [ActivityType.INFOGRAPHIC_SENSORY_INTEGRATION]: 'Duyusal Bütünleme Panosu',
  [ActivityType.INFOGRAPHIC_ANXIETY_RELIEF]: 'Kaygı Yönetimi Rehberi',
  [ActivityType.INFOGRAPHIC_SOCIAL_SKILLS]: 'Sosyal Beceriler Şeması',
  [ActivityType.INFOGRAPHIC_ROUTINE_BUILDER]: 'Günlük Rutin Oluşturucu',
  [ActivityType.INFOGRAPHIC_BEHAVIOR_TRACKER]: 'Davranış Takip Panosu',
  [ActivityType.INFOGRAPHIC_BEP_GOAL_MAP]: 'BEP Hedef Haritası',
  [ActivityType.INFOGRAPHIC_IEP_PROGRESS]: 'BEP Gelişim Takip Panosu',
  [ActivityType.INFOGRAPHIC_OBSERVATION_MATRIX]: 'Gözlem Matrisi',
  [ActivityType.INFOGRAPHIC_COGNITIVE_PROFILE]: 'Bilişsel Profil Panosu',
  [ActivityType.INFOGRAPHIC_BEHAVIOR_INTERVENTION]: 'Davranış Müdahale Planı',
  [ActivityType.INFOGRAPHIC_SENSORY_DIET]: 'Duyusal Diyet Programı',
  [ActivityType.INFOGRAPHIC_PARENT_GUIDE]: 'Veli Bilgilendirme Rehberi',
  [ActivityType.INFOGRAPHIC_ACCOMMODATION_LIST]: 'Düzenleme ve Uyarlama Listesi',
  [ActivityType.INFOGRAPHIC_TRANSITION_PLAN]: 'Geçiş Planı Şeması',
  [ActivityType.INFOGRAPHIC_SPEECH_THERAPY_TARGET]: 'Dil ve Konuşma Terapisi Hedefleri',
  [ActivityType.INFOGRAPHIC_MOTOR_SKILLS]: 'Motor Beceriler Şeması',
  [ActivityType.INFOGRAPHIC_EVALUATION_SUMMARY]: 'Değerlendirme Özet Panosu',
  [ActivityType.MATH_BASIC_OPERATIONS]: 'Temel Matematik İşlemleri',
  [ActivityType.MATH_WORD_PROBLEMS]: 'Matematik Problemleri',
  [ActivityType.MATH_GEOMETRY]: 'Geometri Şekilleri',
  [ActivityType.READING_COMPREHENSION]: 'Okuduğunu Anlama',
  [ActivityType.GRAMMAR_EXERCISE]: 'Dilbilgisi Alıştırmaları',
  [ActivityType.VOCABULARY_BUILDING]: 'Kelime Dağarcığı Geliştirme',
  [ActivityType.LOGIC_PUZZLE]: 'Mantık Bulmacası',
  [ActivityType.PATTERN_RECOGNITION]: 'Örüntü Tanıma',
  [ActivityType.VISUAL_PERCEPTION]: 'Görsel Algı',
  [ActivityType.DYSLEXIA_SYLLABLE_BREAK]: 'Hece Ayırma Desteği',
  [ActivityType.DYSLEXIA_WORD_RECOGNITION]: 'Kelime Tanıma Desteği',
  [ActivityType.DYSLEXIA_SUPPORT]: 'Disleksi Özel Desteği',
  [ActivityType.ANAGRAM_PUZZLE]: 'Anagram Bulmacaları',
  [ActivityType.DYSCALCULIA_NUMBER_SENSE]: 'Sayı Hissi Desteği',
  [ActivityType.DYSCALCULIA_MAGNITUDE_COMPARISON]: 'Büyüklük Karşılaştırma',
  [ActivityType.MEMORY_GAME]: 'Hafıza Oyunu',
  [ActivityType.QUICK_RECALL]: 'Hızlı Hatırlama',
  [ActivityType.MATH_ALGEBRA]: 'Cebirsel İşlemler',
  [ActivityType.TEXT_ANALYSIS]: 'Metin Analizi',
  [ActivityType.SCIENCE_EXPERIMENT]: 'Fen Deneyleri',
  [ActivityType.LOGIC_REASONING]: 'Mantıksal Muhakeme',
  [ActivityType.SPELLING_PRACTICE]: 'İmla ve Yazım Alıştırması',
  [ActivityType.WRITING_PROMPT]: 'Yazma Konuları',
  [ActivityType.DIAGNOSTIC_TEST]: 'Tanılama Testi',
  [ActivityType.SKILL_ASSESSMENT]: 'Beceri Değerlendirmesi',
  [ActivityType.PROGRESS_MONITORING]: 'Gelişim Takibi',
  [ActivityType.SELF_ASSESSMENT]: 'Öz Değerlendirme',
  [ActivityType.CREATIVE_WRITING]: 'Yaratıcı Yazarlık',
  [ActivityType.STORY_STARTER]: 'Hikaye Başlangıçları',
  [ActivityType.DRAWING_EXERCISE]: 'Çizim Alıştırmaları',
  [ActivityType.COLLAGE_ACTIVITY]: 'Kolaj Etkinliği',
  [ActivityType.REFLECTION_PROMPT]: 'Yansıtma Soruları',
  [ActivityType.OBSERVATION_TASK]: 'Gözlem Görevi',
  [ActivityType.HISTORY_TIMELINE]: 'Tarih Çizelgesi',
  [ActivityType.MAP_READING]: 'Harita Okuma',
  [ActivityType.GOAL_SETTING]: 'Hedef Belirleme',
  [ActivityType.INFOGRAPHIC_STUDIO]: 'İnfografik Stüdyosu',
  [ActivityType.SARI_KITAP_STUDIO]: 'Sarı Kitap Stüdyosu',
  [ActivityType.LETTER_MAZE_TEST]: 'Harf Labirenti Testi',
  [ActivityType.LETTER_CONNECT]: 'Harf Bağlama',
  [ActivityType.HARF_BAGLAMA]: 'Harf Bağlama Etkinliği',
};

/**
 * Aktivite türü için Türkçe başlık döndürür.
 */
export const getActivityTurkishName = (actType: string): string => {
  const found = ACTIVITIES.find(a => a.id === actType);
  if (found?.title) return found.title;

  if (TURKISH_ACTIVITY_NAMES[actType]) {
    return TURKISH_ACTIVITY_NAMES[actType];
  }

  return actType
    .replace(/^INFOGRAPHIC_/, '')
    .replace(/_/g, ' ')
    .toLocaleLowerCase('tr')
    .replace(/\b\w/g, l => l.toLocaleUpperCase('tr'));
};

/**
 * Aktivite türü için Türkçe alt etiket / kod döndürür.
 */
export const getActivityTurkishCode = (actType: string): string => {
  const name = getActivityTurkishName(actType);
  return name.toLocaleUpperCase('tr');
};
