import { ActivityCategory, ActivityType } from './types';

// Difficulty Levels
export const DIFFICULTY_OPTIONS = [
  { value: 'Başlangıç', label: 'Başlangıç' },
  { value: 'Orta', label: 'Orta' },
  { value: 'Zor', label: 'Zor' },
  { value: 'Uzman', label: 'Uzman' },
];

export { ACTIVITIES } from './constants/activities';

// Activity Categories
export const ACTIVITY_CATEGORIES: ActivityCategory[] = [
  {
    id: 'visual-perception',
    title: 'Görsel & Mekansal',
    description: 'Görsel tarama, uzamsal algı ve yön tayini çalışmaları.',
    icon: 'fa-solid fa-eye',
    activities: [
      ActivityType.PATTERN_COMPLETION,
      ActivityType.VISUAL_INTERPRETATION,
      ActivityType.DIRECTIONAL_CODE_READING,
      ActivityType.MAP_INSTRUCTION,
      ActivityType.DIRECTIONAL_TRACKING,
      ActivityType.FIND_THE_DIFFERENCE,
      ActivityType.VISUAL_ODD_ONE_OUT,
      ActivityType.GRID_DRAWING,
      ActivityType.SYMMETRY_DRAWING,
      ActivityType.SHAPE_COUNTING,
      ActivityType.WORD_SEARCH,
      // İnfografik Eklentileri
      ActivityType.INFOGRAPHIC_CONCEPT_MAP,
      ActivityType.INFOGRAPHIC_COMPARE,
      ActivityType.INFOGRAPHIC_VENN_DIAGRAM,
      ActivityType.INFOGRAPHIC_MIND_MAP,
    ],
  },
  {
    id: 'reading-comprehension',
    title: 'Okuduğunu Anlama',
    description: 'Hikaye odaklı, görsel ve metin ilişkilendiren testler.',
    icon: 'fa-solid fa-book-open',
    activities: [
      ActivityType.INFOGRAPHIC_SHORT_ANSWER,
      ActivityType.FIVE_W_ONE_H,
      ActivityType.SENTENCE_5W1H,
      ActivityType.LOGIC_ERROR_HUNTER,
      ActivityType.VISUAL_INTERPRETATION,
      ActivityType.STORY_COMPREHENSION,
      ActivityType.STORY_ANALYSIS,
      ActivityType.MISSING_PARTS,
      // İnfografik Eklentileri
      ActivityType.INFOGRAPHIC_STORY_MAP,
      ActivityType.INFOGRAPHIC_CHARACTER_ANALYSIS,
      ActivityType.PREMIUM_STUDIO, // Süper Türkçe Stüdyosu
    ],
  },
  {
    id: 'reading-verbal',
    title: 'Okuma & Dil',
    description: 'Disleksi dostu okuma ve yazma materyalleri.',
    icon: 'fa-solid fa-book-open',
    activities: [
      ActivityType.FAMILY_TREE_MATRIX,
      ActivityType.COLORFUL_SYLLABLE_READING,
      ActivityType.READING_PYRAMID,
      ActivityType.FIND_LETTER_PAIR,
      ActivityType.SYLLABLE_MASTER_LAB,
      ActivityType.READING_SUDOKU,
      ActivityType.LETTER_VISUAL_MATCHING,
      ActivityType.READING_STROOP,
      ActivityType.SYNONYM_ANTONYM_MATCH,
      ActivityType.SYLLABLE_WORD_BUILDER,
      ActivityType.MORPHOLOGY_MATRIX,
      ActivityType.STORY_COMPREHENSION,
      ActivityType.HIDDEN_PASSWORD_GRID,
      ActivityType.STORY_ANALYSIS,
      ActivityType.MISSING_PARTS,
      ActivityType.FAMILY_RELATIONS,
      ActivityType.FAMILY_LOGIC_TEST,
      // İnfografik Eklentileri
      ActivityType.INFOGRAPHIC_SYLLABLE_MAP,
      ActivityType.INFOGRAPHIC_VOCAB_TREE,
      ActivityType.INFOGRAPHIC_SENTENCE_BUILDER,
      ActivityType.INFOGRAPHIC_SHORT_ANSWER,
      ActivityType.LETTER_CONNECT,
      ActivityType.HARF_BAGLAMA,
      ActivityType.KELIME_CUMLE,
      ActivityType.SINAV,
      ActivityType.SARI_KITAP_STUDIO,
    ],
  },
  {
    id: 'math-logic',
    title: 'Matematik & Mantık',
    description: 'İşlemsel düşünme, şekil şifreleri, uzamsal zeka materyalleri.',
    icon: 'fa-solid fa-calculator',
    activities: [
      ActivityType.FINANCIAL_MARKET_CALCULATOR,
      ActivityType.BRAIN_TEASERS,
      ActivityType.APARTMENT_LOGIC_PUZZLE,
      ActivityType.NUMBER_LOGIC_RIDDLES,
      ActivityType.REAL_LIFE_MATH_PROBLEMS,
      ActivityType.MATH_PUZZLE,
      ActivityType.NUMBER_PATTERN,
      ActivityType.KENDOKU,
      ActivityType.NUMBER_PYRAMID,
      ActivityType.NUMBER_PATH_LOGIC,
      ActivityType.CLOCK_READING,
      ActivityType.MONEY_COUNTING,
      ActivityType.MATH_MEMORY_CARDS,
      ActivityType.ABC_CONNECT,
      ActivityType.ODD_EVEN_SUDOKU,
      ActivityType.FUTOSHIKI,
      ActivityType.MAGIC_PYRAMID,
      ActivityType.CAPSULE_GAME,
      ActivityType.BOX_MATH,
      ActivityType.QUEUE_ORDERING,
      ActivityType.MATH_STUDIO,
      ActivityType.MAT_SINAV,
      // İnfografik Eklentileri
      ActivityType.INFOGRAPHIC_MATH_STEPS,
      ActivityType.INFOGRAPHIC_NUMBER_LINE,
      ActivityType.INFOGRAPHIC_MULTIPLICATION_MAP,
    ],
  },
  {
    id: 'social-history',
    title: 'Sosyal & Tarih',
    description: 'Tarihsel kronolojiler, haritalar ve kültürel analizler.',
    icon: 'fa-solid fa-landmark',
    activities: [
      ActivityType.INFOGRAPHIC_HISTORICAL_TIMELINE,
      ActivityType.INFOGRAPHIC_MAP_EXPLORER,
      ActivityType.INFOGRAPHIC_BIOGRAPHY_BOARD,
      ActivityType.INFOGRAPHIC_GOVERNMENT_CHART,
    ],
  },
  {
    id: 'spld-premium',
    title: 'Özel Destek (ÖÖG)',
    description: 'Disleksi, Diskalkuli ve DEHB için premium görsel materyaller.',
    icon: 'fa-solid fa-star',
    activities: [
      ActivityType.INFOGRAPHIC_STUDIO,
      ActivityType.INFOGRAPHIC_DYSLEXIA_READING,
      ActivityType.INFOGRAPHIC_DYSCALCULIA_MATH,
      ActivityType.INFOGRAPHIC_ADHD_FOCUS,
      ActivityType.INFOGRAPHIC_EXECUTIVE_FUNCTION,
      ActivityType.INFOGRAPHIC_ROUTINE_BUILDER,
    ],
  },
];

// LocalStorage Keys
export const STORAGE_KEYS = {
  GEMINI_API_KEY: 'gemini_api_key',
  USER_FAVORITES: 'user_favorites',
  USER_HISTORY: 'user_history',
  PAPER_SIZE: 'bdmind.paperSize',
  APP_SIDEBAR_WIDTH: 'app-sidebar-width',
  APP_THEME: 'app-theme',
  APP_UI_SETTINGS: 'app-ui-settings',
  ADMIN_ACTIVE_TAB: 'admin_active_tab',
  READING_STUDIO_ARCHIVE: 'reading_studio_archive',
  AUDIT_LOGS: 'audit_logs',
  ACTIVITY_SETTINGS_PREFIX: 'settings_',
};
